hpp::debug::Channel Class Reference
hpp::debug::Channel Class Reference
Receive debugging information.
#include <hpp/util/debug.hh>
Public Types
typedef std::vector< Output * > subscribers_t
Public Member Functions
Channel (char const *label, const subscribers_t &subscribers)
virtual ~Channel ()
void write (char const *file, int line, char const *function, const std::string &data)
void write (char const *file, int line, char const *function, const std::stringstream &data)
const char * label () const
Detailed Description
Receive debugging information.
Receive debugging information and forward it to its subscribers.
By default, there is four channels:
error for fatal problems
warning for non-fatal problems
notice for user information
info for technical information and debugging output
Member Typedef Documentation
typedef std::vector<Output*> hpp::debug::Channel::subscribers_t
Constructor & Destructor Documentation
hpp::debug::Channel::Channel (char const * label, const subscribers_t & subscribers) explicit
hpp::debug::Channel::~Channel () virtual
Member Function Documentation
const char * hpp::debug::Channel::label () const
Referenced by hpp::debug::Output::writePrefix().
void hpp::debug::Channel::write (char const * file, int line, char const * function, const std::string & data)
References hpp::debug::Output::write().
void hpp::debug::Channel::write (char const * file, int line, char const * function, const std::stringstream & data)
References hpp::debug::Output::write().