FROM eur0c.laas.fr:4567/humanoid-path-planner/hpp-doc/master:14.04

COPY script/auto-install-hpp.sh /

RUN /auto-install-hpp.sh --target doxygen-1.8.10.install
RUN /auto-install-hpp.sh --target OpenSceneGraph-dae-plugin.install
