hpp::corbaserver::manipulation::Robot Interface Reference
hpp::corbaserver::manipulation::Robot Interface Reference
import"/local/jmirabel/devel/hpp/src/hpp-manipulation-corba/idl/hpp/corbaserver/manipulation/robot.idl";
Public Member Functions
void create (in string robotName) raises (Error)
Create a manipulation::Device The device automatically has an anchor joint called "base_joint" as root joint.
void insertRobotModel (in string robotName, in string rootJointType, in string packageName, in string modelName, in string urdfSuffix, in string srdfSuffix) raises (Error)
Insert robot model as a child of the root joint of the Device.
void insertRobotSRDFModel (in string robotName, in string packageName, in string modelName, in string srdfSuffix) raises (Error)
Load a SRDF for the robot.
void insertHumanoidModel (in string robotName, in string rootJointType, in string packageName, in string modelName, in string urdfSuffix, in string srdfSuffix) raises (Error)
Insert humanoid robot model as a child of the root joint of the Device.
void insertObjectModel (in string objectName, in string rootJointType, in string packageName, in string modelName, in string urdfSuffix, in string srdfSuffix) raises (Error)
Load object model and store in local map.
void loadEnvironmentModel (in string packageName, in string envModelName, in string urdfSuffix, in string srdfSuffix, in string prefix) raises (Error)
Transform_ getRootJointPosition (in string robotName) raises (Error)
Get the position of root joint of a robot in world frame.
void setRootJointPosition (in string robotName, in Transform_ position) raises (Error)
Set the position of root joint of a robot in world frame.
void addGripper (in string linkName, in string gripperName, in Transform_ handlePositioninJoint, in Names_t bodyInCollisionNames) raises (Error)
Add Gripper to a robot.
void addHandle (in string linkName, in string handleName, in Transform_ localPosition) raises (Error)
Add Handle to an object.
void addAxialHandle (in string linkName, in string handleName, in Transform_ localPosition) raises (Error)
Add axial handle to an object.
string getGripperPositionInJoint (in string gripperName, out Transform_ position) raises (hpp::Error)
Return the joint name in which a gripper is and the position relatively to the joint.
string getHandlePositionInJoint (in string handleName, out Transform_ position) raises (hpp::Error)
Return the joint name in which a handle is and the position relatively to the joint.
Member Function Documentation
void hpp::corbaserver::manipulation::Robot::addAxialHandle (in string linkName, in string handleName, in Transform_ localPosition) raises (Error)
Add axial handle to an object.
Parameters
linkName name of the link (hpp::model::Body) holding the handle,
handleName name of the handle,
localPosition position of the handle in the joint frame, rotation around x-axis is not constrained.
void hpp::corbaserver::manipulation::Robot::addGripper (in string linkName, in string gripperName, in Transform_ handlePositioninJoint, in Names_t bodyInCollisionNames) raises (Error)
Add Gripper to a robot.
Parameters
linkName name of the link (hpp::model::Body) holding the gripper,
gripperName name of the gripper,
handlePositioninJoint position of the handle in the joint frame.
void hpp::corbaserver::manipulation::Robot::addHandle (in string linkName, in string handleName, in Transform_ localPosition) raises (Error)
Add Handle to an object.
Parameters
linkName name of the link (hpp::model::Body) holding the handle,
handleName name of the handle,
localPosition position of the handle in the joint frame.
void hpp::corbaserver::manipulation::Robot::create (in string robotName) raises (Error)
Create a manipulation::Device The device automatically has an anchor joint called "base_joint" as root joint.
Parameters
robotName the name of the robot.
string hpp::corbaserver::manipulation::Robot::getGripperPositionInJoint (in string gripperName, out Transform_ position) raises (hpp::Error)
Return the joint name in which a gripper is and the position relatively to the joint.
string hpp::corbaserver::manipulation::Robot::getHandlePositionInJoint (in string handleName, out Transform_ position) raises (hpp::Error)
Return the joint name in which a handle is and the position relatively to the joint.
Transform_ hpp::corbaserver::manipulation::Robot::getRootJointPosition (in string robotName) raises (Error)
Get the position of root joint of a robot in world frame.
Parameters
robotName key of the robot in ProblemSolver object map.
void hpp::corbaserver::manipulation::Robot::insertHumanoidModel (in string robotName, in string rootJointType, in string packageName, in string modelName, in string urdfSuffix, in string srdfSuffix) raises (Error)
Insert humanoid robot model as a child of the root joint of the Device.
Parameters
robotName key of the robot in ProblemSolver object map (see hpp::manipulation::ProblemSolver::addRobot)
rootJointType type of root joint among "anchor", "freeflyer", "planar",
packageName Name of the ROS package containing the model,
modelName Name of the package containing the model
urdfSuffix suffix for urdf file,
The ros url are built as follows: "package://${packageName}/urdf/${modelName}${urdfSuffix}.urdf" "package://${packageName}/srdf/${modelName}${srdfSuffix}.srdf"
Referenced by manipulation.robot.Robot::loadHumanoidModel(), and manipulation.robot.HumanoidRobot::loadModel().
void hpp::corbaserver::manipulation::Robot::insertObjectModel (in string objectName, in string rootJointType, in string packageName, in string modelName, in string urdfSuffix, in string srdfSuffix) raises (Error)
Load object model and store in local map.
Parameters
robotName key of the object in ProblemSolver object map (see hpp::manipulation::ProblemSolver::addRobot)
rootJointType type of root joint among "anchor", "freeflyer", "planar",
packageName Name of the ROS package containing the model,
modelName Name of the package containing the model
urdfSuffix suffix for urdf file,
The ros url are built as follows: "package://${packageName}/urdf/${modelName}${urdfSuffix}.urdf" "package://${packageName}/srdf/${modelName}${srdfSuffix}.srdf"
void hpp::corbaserver::manipulation::Robot::insertRobotModel (in string robotName, in string rootJointType, in string packageName, in string modelName, in string urdfSuffix, in string srdfSuffix) raises (Error)
Insert robot model as a child of the root joint of the Device.
Parameters
robotName key of the robot in ProblemSolver object map (see hpp::manipulation::ProblemSolver::addRobot)
rootJointType type of root joint among "anchor", "freeflyer", "planar",
packageName Name of the ROS package containing the model,
modelName Name of the package containing the model
urdfSuffix suffix for urdf file,
The ros url are built as follows: "package://${packageName}/urdf/${modelName}${urdfSuffix}.urdf" "package://${packageName}/srdf/${modelName}${srdfSuffix}.srdf"
Referenced by manipulation.robot.Robot::loadModel().
void hpp::corbaserver::manipulation::Robot::insertRobotSRDFModel (in string robotName, in string packageName, in string modelName, in string srdfSuffix) raises (Error)
Load a SRDF for the robot.
Several SRDF can thus be loaded for the same robot
void hpp::corbaserver::manipulation::Robot::loadEnvironmentModel (in string packageName, in string envModelName, in string urdfSuffix, in string srdfSuffix, in string prefix) raises (Error)
void hpp::corbaserver::manipulation::Robot::setRootJointPosition (in string robotName, in Transform_ position) raises (Error)
Set the position of root joint of a robot in world frame.
Parameters
robotName key of the robot in ProblemSolver object map.
position constant position of the root joint in world frame in initial configuration.