hpp::core::SteeringMethod Class Reference
hpp::core::SteeringMethod Class Reference abstract
Steering method and distance functions
Steering method.
#include <hpp/core/steering-method.hh>
Public Member Functions
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
virtual SteeringMethodPtr_t copy () const =0
Copy instance and return shared pointer.
Constraints applicable to the robot.
These constraints are not automatically taken into account.
Child class can use it if they need.
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Protected Member Functions
SteeringMethod (ProblemPtr_t problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const =0
create a path between two configurations
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Protected Attributes
ProblemPtr_t problem_
Detailed Description
Steering method.
A steering method creates paths between pairs of configurations for a robot. They are usually used to take into account nonholonomic constraints of some robots
Constructor & Destructor Documentation
hpp::core::SteeringMethod::SteeringMethod (ProblemPtr_t problem) inline protected
Constructor.
hpp::core::SteeringMethod::SteeringMethod (const SteeringMethod & other) inline protected
Copy constructor.
Constraints are copied
Member Function Documentation
void hpp::core::SteeringMethod::constraints (const ConstraintSetPtr_t & constraints) inline
Set constraint set.
const ConstraintSetPtr_t& hpp::core::SteeringMethod::constraints () const inline
Get constraint set.
virtual SteeringMethodPtr_t hpp::core::SteeringMethod::copy () const pure virtual
Copy instance and return shared pointer.
Implemented in hpp::core::SteeringMethodStraight, hpp::core::steeringMethod::Interpolated, and hpp::core::steeringMethod::ReedsShepp.
virtual PathPtr_t hpp::core::SteeringMethod::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const protected pure virtual
create a path between two configurations
Implemented in hpp::core::SteeringMethodStraight, hpp::core::steeringMethod::Interpolated, and hpp::core::steeringMethod::ReedsShepp.
void hpp::core::SteeringMethod::init (SteeringMethodWkPtr_t weak) inline protected
Store weak pointer to itself.
Referenced by hpp::core::steeringMethod::ReedsShepp::init(), hpp::core::steeringMethod::Interpolated::init(), and hpp::core::SteeringMethodStraight::init().
PathPtr_t hpp::core::SteeringMethod::operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const inline
create a path between two configurations
Returns
a Path from q1 to q2 if found. An empty Path if Path could not be built.
Member Data Documentation
ProblemPtr_t hpp::core::SteeringMethod::problem_ protected