hpp::core::InterpolatedPath Class Reference
hpp::core::InterpolatedPath Class Reference
Linear interpolation between two configurations.
#include <hpp/core/interpolated-path.hh>
Public Types
typedef std::pair< value_type, Configuration_t > InterpolationPoint_t
typedef std::map< value_type, Configuration_t, std::less< value_type >, Eigen::aligned_allocator< InterpolationPoint_t > > InterpolationPoints_t
typedef Path parent_t
Public Member Functions
virtual ~InterpolatedPath () throw ()
Destructor.
virtual PathPtr_t copy () const
Return a shared pointer to this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
virtual PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
Extraction/Reversion of a sub-path See Path::extract.
virtual PathPtr_t reverse () const
Reversion of a path.
DevicePtr_t device () const
Return the internal robot.
void insert (const value_type &time, ConfigurationIn_t config)
Insert interpolation point.
Configuration_t initial () const
Get the initial configuration.
Configuration_t end () const
Get the final configuration.
const InterpolationPoints_t & interpolationPoints () const
Public Member Functions inherited from hpp::core::Path
Configuration_t operator() (const value_type &t) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &t, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &t) const throw ()
bool at (const value_type &t, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
value_type length () const
Get length of definition interval.
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
Static Public Member Functions
static InterpolatedPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length)
Create instance and return shared pointer.
static InterpolatedPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints)
Create instance and return shared pointer.
static InterpolatedPathPtr_t createCopy (const InterpolatedPathPtr_t &path)
Create copy and return shared pointer.
static InterpolatedPathPtr_t create (const PathPtr_t &path, const DevicePtr_t &device, const std::size_t &nbSamples)
Create an interpolation of this path.
static InterpolatedPathPtr_t createCopy (const InterpolatedPathPtr_t &path, const ConstraintSetPtr_t &constraints)
Create copy and return shared pointer.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
InterpolatedPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length)
Constructor.
InterpolatedPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints)
Constructor with constraints.
InterpolatedPath (const InterpolatedPath &path)
Copy constructor.
InterpolatedPath (const InterpolatedPath &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (InterpolatedPathPtr_t self)
void initCopy (InterpolatedPathPtr_t self)
virtual bool impl_compute (ConfigurationOut_t result, value_type param) const
Function evaluation without applying constraints.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathPtr_t &self)
Store weak pointer to itself.
void initCopy (const PathPtr_t &self)
should be called at copy construction of derived class instances
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
void checkPath () const
Should be called by child classes after having init.
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t timeRange_
Interval of definition.
Detailed Description
Linear interpolation between two configurations.
Degrees of freedom are interpolated depending on the type of joint they parameterize:
linear interpolation for translation joints, bounded rotation joints, and translation part of freeflyer joints,
angular interpolation for unbounded rotation joints,
constant angular velocity for SO(3) part of freeflyer joints.
Member Typedef Documentation
typedef std::pair<value_type, Configuration_t> hpp::core::InterpolatedPath::InterpolationPoint_t
typedef std::map<value_type, Configuration_t, std::less <value_type>, Eigen::aligned_allocator <InterpolationPoint_t> > hpp::core::InterpolatedPath::InterpolationPoints_t
typedef Path hpp::core::InterpolatedPath::parent_t
Constructor & Destructor Documentation
virtual hpp::core::InterpolatedPath::~InterpolatedPath () throw () inline virtual
Destructor.
hpp::core::InterpolatedPath::InterpolatedPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length) protected
Constructor.
hpp::core::InterpolatedPath::InterpolatedPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints) protected
Constructor with constraints.
hpp::core::InterpolatedPath::InterpolatedPath (const InterpolatedPath & path) protected
Copy constructor.
hpp::core::InterpolatedPath::InterpolatedPath (const InterpolatedPath & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
virtual PathPtr_t hpp::core::InterpolatedPath::copy () const inline virtual
Return a shared pointer to this.
As StaightPath are immutable, and refered to by shared pointers, they do not need to be copied.
Implements hpp::core::Path.
virtual PathPtr_t hpp::core::InterpolatedPath::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy *this should not have constraints.
Implements hpp::core::Path.
static InterpolatedPathPtr_t hpp::core::InterpolatedPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length) inline static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
length Distance between the configurations.
References init().
Referenced by hpp::core::steeringMethod::Interpolated::impl_compute().
static InterpolatedPathPtr_t hpp::core::InterpolatedPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints) inline static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
length Distance between the configurations.
constraints the path is subject to
References init().
static InterpolatedPathPtr_t hpp::core::InterpolatedPath::create (const PathPtr_t & path, const DevicePtr_t & device, const std::size_t & nbSamples) static
Create an interpolation of this path.
Parameters
path path to interpolate
nbSamples number of samples between the initial and end configuration
Note
it is assume that the constraints are constant along the path
static InterpolatedPathPtr_t hpp::core::InterpolatedPath::createCopy (const InterpolatedPathPtr_t & path) inline static
Create copy and return shared pointer.
Parameters
path path to copy
References initCopy().
static InterpolatedPathPtr_t hpp::core::InterpolatedPath::createCopy (const InterpolatedPathPtr_t & path, const ConstraintSetPtr_t & constraints) inline static
Create copy and return shared pointer.
Parameters
path path to copy
constraints the path is subject to
References initCopy().
DevicePtr_t hpp::core::InterpolatedPath::device () const
Return the internal robot.
Configuration_t hpp::core::InterpolatedPath::end () const inline virtual
Get the final configuration.
Implements hpp::core::Path.
virtual PathPtr_t hpp::core::InterpolatedPath::extract (const interval_t & subInterval) const throw (projection_error) virtual
Extraction/Reversion of a sub-path See Path::extract.
Reimplemented from hpp::core::Path.
virtual bool hpp::core::InterpolatedPath::impl_compute (ConfigurationOut_t configuration, value_type t) const protected virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implements hpp::core::Path.
void hpp::core::InterpolatedPath::init (InterpolatedPathPtr_t self) protected
Referenced by create().
void hpp::core::InterpolatedPath::initCopy (InterpolatedPathPtr_t self) protected
Referenced by createCopy().
Configuration_t hpp::core::InterpolatedPath::initial () const inline virtual
Get the initial configuration.
Implements hpp::core::Path.
void hpp::core::InterpolatedPath::insert (const value_type & time, ConfigurationIn_t config) inline
Insert interpolation point.
const InterpolationPoints_t& hpp::core::InterpolatedPath::interpolationPoints () const inline
virtual std::ostream& hpp::core::InterpolatedPath::print (std::ostream & os) const inline protected virtual
Print path in a stream.
Implements hpp::core::Path.
virtual PathPtr_t hpp::core::InterpolatedPath::reverse () const virtual
Reversion of a path.
Returns
a new path that is this one reversed.
Reimplemented from hpp::core::Path.