hpp::core::NumericalConstraint Class Reference
hpp::core::NumericalConstraint Class Reference
Constraints
With the same notation as in Equation, this class represents equation:
#include <hpp/core/numerical-constraint.hh>
Public Member Functions
virtual EquationPtr_t copy () const
Copy object and return shared pointer to copy.
void rightHandSideFromConfig (ConfigurationIn_t config)
DifferentiableFunction & function () const
Return a reference to the inner function.
const DifferentiableFunctionPtr_t & functionPtr () const
Return a reference to the inner function.
vector_t & value ()
Return a reference to the value.
matrix_t & jacobian ()
Return a reference to the jacobian.
Public Member Functions inherited from hpp::core::Equation
void rightHandSide (vectorIn_t rhs)
Set the right hand side of the equation.
vectorIn_t rightHandSide () const
Return the right hand side of the equation.
size_type rhsSize () const
Return the size of the right hand side constraint.
const ComparisonTypePtr_t & comparisonType () const
Return the ComparisonType.
void comparisonType (const ComparisonTypePtr_t &comp)
Set the comparison type.
vectorOut_t nonConstRightHandSide ()
Return the right hand side of the equation.
Static Public Member Functions
static NumericalConstraintPtr_t create (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp=ComparisonType::createDefault())
Create a shared pointer to a new instance.
static NumericalConstraintPtr_t create (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp, vectorIn_t rhs)
Create a shared pointer to a new instance.
static NumericalConstraintPtr_t createCopy (const NumericalConstraintPtr_t &other)
Create a copy and return shared pointer.
Protected Member Functions
NumericalConstraint (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp=ComparisonType::createDefault())
Constructor.
NumericalConstraint (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp, vectorIn_t rhs)
Constructor.
NumericalConstraint (const NumericalConstraint &other)
Copy constructor.
void init (const NumericalConstraintWkPtr_t &weak)
Protected Member Functions inherited from hpp::core::Equation
Equation (const ComparisonTypePtr_t &comp, vectorIn_t rhs)
Equation (const Equation &other)
void init (const EquationWkPtr_t &weak)
Detailed Description
With the same notation as in Equation, this class represents equation:
that cannot be explicitely defined;
in which is a differentiable function.
Constructor & Destructor Documentation
hpp::core::NumericalConstraint::NumericalConstraint (const DifferentiableFunctionPtr_t & function, ComparisonTypePtr_t comp = ComparisonType::createDefault()) protected
Constructor.
Parameters
function the differentiable function
hpp::core::NumericalConstraint::NumericalConstraint (const DifferentiableFunctionPtr_t & function, ComparisonTypePtr_t comp, vectorIn_t rhs) protected
Constructor.
Parameters
function the differentiable function
rhs the right hand side of this equation
hpp::core::NumericalConstraint::NumericalConstraint (const NumericalConstraint & other) protected
Copy constructor.
Member Function Documentation
virtual EquationPtr_t hpp::core::NumericalConstraint::copy () const virtual
Copy object and return shared pointer to copy.
Implements hpp::core::Equation.
Reimplemented in hpp::core::ExplicitNumericalConstraint, and hpp::core::ExplicitRelativeTransformation.
static NumericalConstraintPtr_t hpp::core::NumericalConstraint::create (const DifferentiableFunctionPtr_t & function, ComparisonTypePtr_t comp = ComparisonType::createDefault()) static
Create a shared pointer to a new instance.
See also
constructors
Referenced by hpp::core::ProblemSolver::addNumericalConstraint().
static NumericalConstraintPtr_t hpp::core::NumericalConstraint::create (const DifferentiableFunctionPtr_t & function, ComparisonTypePtr_t comp, vectorIn_t rhs) static
Create a shared pointer to a new instance.
See also
constructors
static NumericalConstraintPtr_t hpp::core::NumericalConstraint::createCopy (const NumericalConstraintPtr_t & other) static
Create a copy and return shared pointer.
DifferentiableFunction& hpp::core::NumericalConstraint::function () const inline
Return a reference to the inner function.
const DifferentiableFunctionPtr_t& hpp::core::NumericalConstraint::functionPtr () const inline
Return a reference to the inner function.
void hpp::core::NumericalConstraint::init (const NumericalConstraintWkPtr_t & weak) inline protected
References hpp::core::Equation::init().
Referenced by hpp::core::ExplicitNumericalConstraint::init().
matrix_t& hpp::core::NumericalConstraint::jacobian () inline
Return a reference to the jacobian.
This matrix can be used to store the derivative of the function, its size being initialized.
void hpp::core::NumericalConstraint::rightHandSideFromConfig (ConfigurationIn_t config) virtual
See also
Equation::rightHandSideFromConfig
Implements hpp::core::Equation.
vector_t& hpp::core::NumericalConstraint::value () inline
Return a reference to the value.
This vector can be used to store the output of the function, its size being initialized.