hpp::core::pathOptimization::PartialSplinePath Class Reference
hpp::core::pathOptimization::PartialSplinePath Class Reference
Path for a robot partially defined by a cubic B-spline.
#include <hpp/core/path-optimization/partial-spline-path.hh>
Public Types
typedef Path parent_t
Public Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
Public Member Functions inherited from hpp::core::Path
Configuration_t operator() (const value_type &t) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &t, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &t) const throw ()
bool at (const value_type &t, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
value_type length () const
Get length of definition interval.
virtual Configuration_t initial () const =0
Get the initial configuration.
virtual Configuration_t end () const =0
Get the final configuration.
virtual ~Path () throw ()
Destructor.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const =0
Return a shared pointer to a copy of this and set constraints.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
virtual PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
Extraction/Reversion of a sub-path.
virtual PathPtr_t reverse () const
Reversion of a path.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
Protected Member Functions
PartialSplinePath (const DevicePtr_t &robot, const PathPtr_t &path, const JointVector_t &joints, const std::vector< value_type > &knots)
Constructor.
PartialSplinePath (const PartialSplinePathPtr_t &path)
Copy constructor.
void init (PartialSplinePathPtr_t self)
virtual void impl_compute (ConfigurationOut_t result, value_type t) const
Function evaluation without applying constraints.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathPtr_t &self)
Store weak pointer to itself.
void initCopy (const PathPtr_t &self)
should be called at copy construction of derived class instances
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
void checkPath () const
Should be called by child classes after having init.
Construction, destruction, copy
static PartialSplinePathPtr_t create (const PathPtr_t &path, const JointVector_t &joints, const std::vector< value_type > &knots)
Create instance and return shared pointer.
static PartialSplinePathPtr_t create (const roboptim::trajectory::CubicBSpline &spline)
Create instance from a CubicBSpline and return a shared pointer.
virtual PathPtr_t copy () const
Return a shared pointer to a copy of this.
virtual ~PartialSplinePath () throw ()
Destructor.
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t timeRange_
Interval of definition.
Detailed Description
Path for a robot partially defined by a cubic B-spline.
Some configuration variables specified at construction are defined by an internal cubic B-spline while the other configuration variables are defined by a path given at construction.
This enables users to perform numerical optimization on some joints only, keeping the trajectory of other joints constant.
Member Typedef Documentation
typedef Path hpp::core::pathOptimization::PartialSplinePath::parent_t
Constructor & Destructor Documentation
virtual hpp::core::pathOptimization::PartialSplinePath::~PartialSplinePath () throw () inline virtual
Destructor.
hpp::core::pathOptimization::PartialSplinePath::PartialSplinePath (const DevicePtr_t & robot, const PathPtr_t & path, const JointVector_t & joints, const std::vector< value_type > & knots) protected
Constructor.
hpp::core::pathOptimization::PartialSplinePath::PartialSplinePath (const PartialSplinePathPtr_t & path) protected
Copy constructor.
Member Function Documentation
virtual PathPtr_t hpp::core::pathOptimization::PartialSplinePath::copy () const inline virtual
Return a shared pointer to a copy of this.
Implements hpp::core::Path.
static PartialSplinePathPtr_t hpp::core::pathOptimization::PartialSplinePath::create (const PathPtr_t & path, const JointVector_t & joints, const std::vector< value_type > & knots) inline static
Create instance and return shared pointer.
References init().
static PartialSplinePathPtr_t hpp::core::pathOptimization::PartialSplinePath::create (const roboptim::trajectory::CubicBSpline & spline) inline static
Create instance from a CubicBSpline and return a shared pointer.
References init().
virtual void hpp::core::pathOptimization::PartialSplinePath::impl_compute (ConfigurationOut_t configuration, value_type t) const protected virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implements hpp::core::Path.
void hpp::core::pathOptimization::PartialSplinePath::init (PartialSplinePathPtr_t self) inline protected
Referenced by create().
virtual std::ostream& hpp::core::pathOptimization::PartialSplinePath::print (std::ostream & os) const inline virtual
Print path in a stream.
Implements hpp::core::Path.