hpp::core::ExplicitRelativeTransformation Class Reference
hpp::core::ExplicitRelativeTransformation Class Reference
Constraints
Relative transformation as an explicit constraint.
#include <hpp/core/explicit-relative-transformation.hh>
Public Member Functions
virtual EquationPtr_t copy () const
Copy object and return shared pointer to copy.
virtual void solve (ConfigurationOut_t configuration)
Solve constraint.
Public Member Functions inherited from hpp::core::ExplicitNumericalConstraint
const SizeIntervals_t & outputConf () const
Get output configuration variables.
const SizeIntervals_t & outputVelocity () const
Get output degrees of freedom.
Public Member Functions inherited from hpp::core::NumericalConstraint
void rightHandSideFromConfig (ConfigurationIn_t config)
DifferentiableFunction & function () const
Return a reference to the inner function.
const DifferentiableFunctionPtr_t & functionPtr () const
Return a reference to the inner function.
vector_t & value ()
Return a reference to the value.
matrix_t & jacobian ()
Return a reference to the jacobian.
Public Member Functions inherited from hpp::core::Equation
void rightHandSide (vectorIn_t rhs)
Set the right hand side of the equation.
vectorIn_t rightHandSide () const
Return the right hand side of the equation.
size_type rhsSize () const
Return the size of the right hand side constraint.
const ComparisonTypePtr_t & comparisonType () const
Return the ComparisonType.
void comparisonType (const ComparisonTypePtr_t &comp)
Set the comparison type.
vectorOut_t nonConstRightHandSide ()
Return the right hand side of the equation.
Static Public Member Functions
static ExplicitRelativeTransformationPtr_t create (const std::string &name, const DevicePtr_t &robot, const JointPtr_t &joint1, const JointPtr_t &joint2, const Transform3f &frame1, const Transform3f &frame2)
Return a shared pointer to a new instance.
static ExplicitRelativeTransformationPtr_t createCopy (const ExplicitRelativeTransformationPtr_t &other)
Static Public Member Functions inherited from hpp::core::ExplicitNumericalConstraint
static ExplicitNumericalConstraintPtr_t create (const DevicePtr_t &robot, const DifferentiableFunctionPtr_t &function, const SizeIntervals_t &outputConf, const SizeIntervals_t &outputVelocity)
Create instance and return shared pointer.
static ExplicitNumericalConstraintPtr_t create (const DevicePtr_t &robot, const DifferentiableFunctionPtr_t &function, const SizeIntervals_t &outputConf, const SizeIntervals_t &outputVelocity, vectorIn_t rhs)
Create instance and return shared pointer.
static ExplicitNumericalConstraintPtr_t createCopy (const ExplicitNumericalConstraintPtr_t &other)
Create a copy and return shared pointer.
Static Public Member Functions inherited from hpp::core::NumericalConstraint
static NumericalConstraintPtr_t create (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp=ComparisonType::createDefault())
Create a shared pointer to a new instance.
static NumericalConstraintPtr_t create (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp, vectorIn_t rhs)
Create a shared pointer to a new instance.
static NumericalConstraintPtr_t createCopy (const NumericalConstraintPtr_t &other)
Create a copy and return shared pointer.
Protected Member Functions
ExplicitRelativeTransformation (const std::string &name, const DevicePtr_t &robot, const JointPtr_t &joint1, const JointPtr_t &joint2, const Transform3f &frame1, const Transform3f &frame2, std::vector< bool > mask=boost::assign::list_of(true)(true)(true)(true)(true)(true))
ExplicitRelativeTransformation (const ExplicitRelativeTransformation &other)
void init (const ExplicitRelativeTransformationWkPtr_t &weak)
Protected Member Functions inherited from hpp::core::ExplicitNumericalConstraint
ExplicitNumericalConstraint (const DevicePtr_t &robot, const DifferentiableFunctionPtr_t &function, const SizeIntervals_t &outputConf, const SizeIntervals_t &outputVelocity)
Constructor.
ExplicitNumericalConstraint (const DevicePtr_t &robot, const DifferentiableFunctionPtr_t &function, const SizeIntervals_t &outputConf, const SizeIntervals_t &outputVelocity, vectorIn_t rhs)
Constructor.
ExplicitNumericalConstraint (const DifferentiableFunctionPtr_t &implicitConstraint, const SizeIntervals_t &outputConf, const SizeIntervals_t &outputVelocity)
Constructor.
ExplicitNumericalConstraint (const ExplicitNumericalConstraint &other)
Constructor.
void init (const ExplicitNumericalConstraintWkPtr_t &weak)
Protected Member Functions inherited from hpp::core::NumericalConstraint
NumericalConstraint (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp=ComparisonType::createDefault())
Constructor.
NumericalConstraint (const DifferentiableFunctionPtr_t &function, ComparisonTypePtr_t comp, vectorIn_t rhs)
Constructor.
NumericalConstraint (const NumericalConstraint &other)
Copy constructor.
void init (const NumericalConstraintWkPtr_t &weak)
Protected Member Functions inherited from hpp::core::Equation
Equation (const ComparisonTypePtr_t &comp, vectorIn_t rhs)
Equation (const Equation &other)
void init (const EquationWkPtr_t &weak)
Detailed Description
Relative transformation as an explicit constraint.
When the positions of two joints are constrained by a full transformation constraint, if the second joint is hold by a freeflyer sequence (R3 x SO(3)), the position of this latter joint can be explicitely expressed with respect to the position of the first joint.
This class provides this expression through method solve.
When considered as an implicit constraint, for instance if this constraint is grouped with other constraints, the classical
Constructor & Destructor Documentation
hpp::core::ExplicitRelativeTransformation::ExplicitRelativeTransformation (const std::string & name, const DevicePtr_t & robot, const JointPtr_t & joint1, const JointPtr_t & joint2, const Transform3f & frame1, const Transform3f & frame2, std::vector< bool > mask = boost::assign::list_of (true)(true)(true) (true)(true)(true)) inline protected
hpp::core::ExplicitRelativeTransformation::ExplicitRelativeTransformation (const ExplicitRelativeTransformation & other) inline protected
Member Function Documentation
virtual EquationPtr_t hpp::core::ExplicitRelativeTransformation::copy () const inline virtual
Copy object and return shared pointer to copy.
Reimplemented from hpp::core::ExplicitNumericalConstraint.
static ExplicitRelativeTransformationPtr_t hpp::core::ExplicitRelativeTransformation::create (const std::string & name, const DevicePtr_t & robot, const JointPtr_t & joint1, const JointPtr_t & joint2, const Transform3f & frame1, const Transform3f & frame2) inline static
Return a shared pointer to a new instance.
Parameters
name the name of the constraints,
robot the robot the constraints is applied to,
joint1 input joint
joint2 output joint: position of this joint is computed with respect to joint1 position
frame1 position of a fixed frame in joint 1,
frame2 position of a fixed frame in joint 2,
References init().
static ExplicitRelativeTransformationPtr_t hpp::core::ExplicitRelativeTransformation::createCopy (const ExplicitRelativeTransformationPtr_t & other) inline static
References init().
void hpp::core::ExplicitRelativeTransformation::init (const ExplicitRelativeTransformationWkPtr_t & weak) inline protected
References hpp::core::ExplicitNumericalConstraint::init().
Referenced by create(), and createCopy().
virtual void hpp::core::ExplicitRelativeTransformation::solve (ConfigurationOut_t configuration) inline virtual
Solve constraint.
Compute output with respect to input.
Parameters
configuration input and output configuration
Reimplemented from hpp::core::ExplicitNumericalConstraint.