hpp::core::Path Class Reference
hpp::core::Path Class Reference abstract
Abstraction of paths: mapping from time to configuration space.
#include <hpp/core/path.hh>
Public Member Functions
Configuration_t operator() (const value_type &t) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &t, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &t) const throw ()
bool at (const value_type &t, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
virtual bool impl_compute (ConfigurationOut_t configuration, value_type t) const =0
Function evaluation without applying constraints.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
value_type length () const
Get length of definition interval.
virtual Configuration_t initial () const =0
Get the initial configuration.
virtual Configuration_t end () const =0
Get the final configuration.
Construction, destruction, copy
virtual ~Path () throw ()
Destructor.
virtual PathPtr_t copy () const =0
Return a shared pointer to a copy of this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const =0
Return a shared pointer to a copy of this and set constraints.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
virtual PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
Extraction/Reversion of a sub-path.
virtual PathPtr_t reverse () const
Reversion of a path.
Constraints
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const =0
Print path in a stream.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathPtr_t &self)
Store weak pointer to itself.
void initCopy (const PathPtr_t &self)
should be called at copy construction of derived class instances
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
void checkPath () const
Should be called by child classes after having init.
Protected Attributes
interval_t timeRange_
Interval of definition.
Friends
std::ostream & operator<< (std::ostream &os, const Path &path)
Detailed Description
Abstraction of paths: mapping from time to configuration space.
Constructor & Destructor Documentation
virtual hpp::core::Path::~Path () throw () inline virtual
Destructor.
hpp::core::Path::Path (const interval_t & interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t & constraints) protected
Constructor.
Parameters
interval interval of definition of the path,
outputSize size of the output configuration,
outputDerivativeSize number of degrees of freedom of the underlying robot
constraints constraints the set is subject to, constraints are solved at each evaluation of the output configuration.
Note
Constraints are copied.
hpp::core::Path::Path (const interval_t & interval, size_type outputSize, size_type outputDerivativeSize) protected
Constructor.
Parameters
interval interval of definition of the path,
outputSize size of the output configuration,
outputDerivativeSize number of degrees of freedom of the underlying robot
hpp::core::Path::Path (const Path & path) protected
Copy constructor.
hpp::core::Path::Path (const Path & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
template<class T > boost::shared_ptr<T> hpp::core::Path::as (void) inline
Static cast into a derived type.
template<class T > boost::shared_ptr<const T> hpp::core::Path::as (void) const inline
Static cast into a derived type.
bool hpp::core::Path::at (const value_type & t, ConfigurationOut_t result) const inline
Get the configuration at a parameter without applying the constraints.
void hpp::core::Path::checkPath () const protected
Should be called by child classes after having init.
Referenced by hpp::core::StraightPath::create(), and hpp::core::StraightPath::createCopy().
const ConstraintSetPtr_t& hpp::core::Path::constraints () const inline
Get constraints the path is subject to.
void hpp::core::Path::constraints (const ConstraintSetPtr_t & constraint) inline protected
Set the constraints.
Warning
this method is protected for child classes that need to initialize themselves before being sure that the initial and end configuration satisfy the constraints
virtual PathPtr_t hpp::core::Path::copy () const pure virtual
Return a shared pointer to a copy of this.
Implemented in hpp::core::InterpolatedPath, hpp::core::StraightPath, hpp::core::ReedsSheppPath, hpp::core::pathOptimization::PartialSplinePath, and hpp::core::PathVector.
virtual PathPtr_t hpp::core::Path::copy (const ConstraintSetPtr_t & constraints) const pure virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy *this should not have constraints.
Implemented in hpp::core::InterpolatedPath, hpp::core::StraightPath, hpp::core::ReedsSheppPath, and hpp::core::PathVector.
virtual Configuration_t hpp::core::Path::end () const pure virtual
Get the final configuration.
Implemented in hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::ReedsSheppPath, and hpp::core::PathVector.
virtual PathPtr_t hpp::core::Path::extract (const interval_t & subInterval) const throw (projection_error) virtual
Extraction/Reversion of a sub-path.
Parameters
subInterval interval of definition of the extract path If upper bound of subInterval is smaller than lower bound, result is reversed.
Exceptions
projection_error is thrown when an end configuration of the returned path could not be computed due to projection failure.
Reimplemented in hpp::core::InterpolatedPath, hpp::core::StraightPath, and hpp::core::PathVector.
virtual bool hpp::core::Path::impl_compute (ConfigurationOut_t configuration, value_type t) const pure virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implemented in hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::PathVector, hpp::core::ReedsSheppPath, and hpp::core::pathOptimization::PartialSplinePath.
void hpp::core::Path::init (const PathPtr_t & self) protected
Store weak pointer to itself.
should be called at construction of derived class instances
void hpp::core::Path::initCopy (const PathPtr_t & self) protected
should be called at copy construction of derived class instances
virtual Configuration_t hpp::core::Path::initial () const pure virtual
Get the initial configuration.
Implemented in hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::ReedsSheppPath, and hpp::core::PathVector.
value_type hpp::core::Path::length () const inline
Get length of definition interval.
Configuration_t hpp::core::Path::operator() (const value_type & t) const inline
Configuration_t hpp::core::Path::operator() (const value_type & t, bool & success) const inline
bool hpp::core::Path::operator() (ConfigurationOut_t result, const value_type & t) const throw () inline
size_type hpp::core::Path::outputDerivativeSize () const inline
Get size of velocity.
size_type hpp::core::Path::outputSize () const inline
Get size of configuration space.
virtual std::ostream& hpp::core::Path::print (std::ostream & os) const protected pure virtual
Print path in a stream.
Implemented in hpp::core::StraightPath, hpp::core::InterpolatedPath, hpp::core::ReedsSheppPath, hpp::core::PathVector, and hpp::core::pathOptimization::PartialSplinePath.
Referenced by hpp::core::operator<<().
virtual PathPtr_t hpp::core::Path::reverse () const virtual
Reversion of a path.
Returns
a new path that is this one reversed.
Reimplemented in hpp::core::InterpolatedPath.
const interval_t& hpp::core::Path::timeRange () const inline
Get interval of definition.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Path & path) friend
Member Data Documentation
interval_t hpp::core::Path::timeRange_ protected
Interval of definition.
Referenced by hpp::core::PathVector::PathVector().