hpp::core::continuousCollisionChecking::progressive::PathVelocity Struct Reference
hpp::core::continuousCollisionChecking::progressive::PathVelocity Struct Reference
#include <continuous-collision-checking/progressive/body-pair-collision.hh>
Public Types
typedef std::map< value_type, value_type > Velocities_t
Public Member Functions
PathVelocity (CoefficientVelocities_t const *coefs, PathPtr_t path)
PathVelocity (CoefficientVelocities_t const *coefs)
void init (StraightPathPtr_t path)
void init (InterpolatedPathPtr_t path)
value_type maximalVelocity (const value_type &t) const
value_type computeMaximalVelocity (const value_type &t0, ConfigurationIn_t q0, const value_type &t1, ConfigurationIn_t q1)
Compute maximal velocity of points of body1 in the frame of body 2.
Public Attributes
Velocities_t maximalVelocities_
value_type maximalVelocity_
CoefficientVelocities_t const * coefs_
Member Typedef Documentation
typedef std::map<value_type, value_type> hpp::core::continuousCollisionChecking::progressive::PathVelocity::Velocities_t
Constructor & Destructor Documentation
hpp::core::continuousCollisionChecking::progressive::PathVelocity::PathVelocity (CoefficientVelocities_t const * coefs, PathPtr_t path) inline
References init().
hpp::core::continuousCollisionChecking::progressive::PathVelocity::PathVelocity (CoefficientVelocities_t const * coefs) inline
Member Function Documentation
value_type hpp::core::continuousCollisionChecking::progressive::PathVelocity::computeMaximalVelocity (const value_type & t0, ConfigurationIn_t q0, const value_type & t1, ConfigurationIn_t q1) inline
Compute maximal velocity of points of body1 in the frame of body 2.
Parameters
path input path
References coefs_, hpp::model::Joint::configuration(), hpp::model::JointConfiguration::distance(), maximalVelocity(), and hpp::model::Joint::rankInConfiguration().
Referenced by init().
void hpp::core::continuousCollisionChecking::progressive::PathVelocity::init (StraightPathPtr_t path) inline
References computeMaximalVelocity(), maximalVelocities_, and maximalVelocity_.
Referenced by PathVelocity().
void hpp::core::continuousCollisionChecking::progressive::PathVelocity::init (InterpolatedPathPtr_t path) inline
References computeMaximalVelocity(), maximalVelocities_, and maximalVelocity_.
value_type hpp::core::continuousCollisionChecking::progressive::PathVelocity::maximalVelocity (const value_type & t) const inline
References maximalVelocities_.
Referenced by computeMaximalVelocity().
Member Data Documentation
CoefficientVelocities_t const* hpp::core::continuousCollisionChecking::progressive::PathVelocity::coefs_
Referenced by computeMaximalVelocity().
Velocities_t hpp::core::continuousCollisionChecking::progressive::PathVelocity::maximalVelocities_
Referenced by init(), and maximalVelocity().
value_type hpp::core::continuousCollisionChecking::progressive::PathVelocity::maximalVelocity_
Referenced by init(), hpp::core::continuousCollisionChecking::progressive::BodyPairCollision::maximalVelocity(), and hpp::core::continuousCollisionChecking::progressive::BodyPairCollision::validateConfiguration().