hpp::core::pathOptimization::ConfigOptimization::Parameters Struct Reference
hpp::core::pathOptimization::ConfigOptimization::Parameters Struct Reference
Path Optimization
#include <hpp/core/path-optimization/config-optimization.hh>
Public Member Functions
Parameters ()
Public Attributes
bool addConfigConstraintToPath
Defaults to false.
std::size_t numberOfPass
std::size_t numberOfIterations
value_type alphaInit
boost::function< Configuration_t(const PathVector &)> getGoal
boost::function< ConfigProjectorPtr_t(const PathPtr_t &, const PathPtr_t &, bool &) > getConfigProjector
boost::function< bool(const JointPtr_t, const size_type)> shouldFilter
Constructor & Destructor Documentation
hpp::core::pathOptimization::ConfigOptimization::Parameters::Parameters ()
Member Data Documentation
bool hpp::core::pathOptimization::ConfigOptimization::Parameters::addConfigConstraintToPath
Defaults to false.
Referenced by hpp::core::pathOptimization::ConfigOptimization::createWithTraits().
value_type hpp::core::pathOptimization::ConfigOptimization::Parameters::alphaInit
Referenced by hpp::core::pathOptimization::ConfigOptimization::createWithTraits().
boost::function< ConfigProjectorPtr_t (const PathPtr_t&, const PathPtr_t&, bool&) > hpp::core::pathOptimization::ConfigOptimization::Parameters::getConfigProjector
Referenced by hpp::core::pathOptimization::ConfigOptimization::createWithTraits().
boost::function<Configuration_t (const PathVector&)> hpp::core::pathOptimization::ConfigOptimization::Parameters::getGoal
Referenced by hpp::core::pathOptimization::ConfigOptimization::createWithTraits().
std::size_t hpp::core::pathOptimization::ConfigOptimization::Parameters::numberOfIterations
Referenced by hpp::core::pathOptimization::ConfigOptimization::createWithTraits().
std::size_t hpp::core::pathOptimization::ConfigOptimization::Parameters::numberOfPass
Referenced by hpp::core::pathOptimization::ConfigOptimization::createWithTraits().
boost::function<bool (const JointPtr_t, const size_type)> hpp::core::pathOptimization::ConfigOptimization::Parameters::shouldFilter
Referenced by hpp::core::pathOptimization::ConfigOptimization::createWithTraits().