hpp::core::StraightPath Class Reference
hpp::core::StraightPath Class Reference
Linear interpolation between two configurations.
#include <hpp/core/straight-path.hh>
Public Types
typedef Path parent_t
Public Member Functions
virtual ~StraightPath () throw ()
Destructor.
virtual PathPtr_t copy () const
Return a shared pointer to this.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
virtual PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
Extraction/Reversion of a sub-path.
void initialConfig (ConfigurationIn_t initial)
Modify initial configuration.
void endConfig (ConfigurationIn_t end)
Modify end configuration.
DevicePtr_t device () const
Return the internal robot.
Configuration_t initial () const
Get the initial configuration.
Configuration_t end () const
Get the final configuration.
Public Member Functions inherited from hpp::core::Path
Configuration_t operator() (const value_type &t) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &t, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &t) const throw ()
bool at (const value_type &t, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
value_type length () const
Get length of definition interval.
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
virtual PathPtr_t reverse () const
Reversion of a path.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
Static Public Member Functions
static StraightPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length)
Create instance and return shared pointer.
static StraightPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints)
Create instance and return shared pointer.
static StraightPathPtr_t createCopy (const StraightPathPtr_t &path)
Create copy and return shared pointer.
static StraightPathPtr_t createCopy (const StraightPathPtr_t &path, const ConstraintSetPtr_t &constraints)
Create copy and return shared pointer.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
StraightPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length)
Constructor.
StraightPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints)
Constructor with constraints.
StraightPath (const StraightPath &path)
Copy constructor.
StraightPath (const StraightPath &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (StraightPathPtr_t self)
void initCopy (StraightPathPtr_t self)
virtual bool impl_compute (ConfigurationOut_t result, value_type param) const
Function evaluation without applying constraints.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathPtr_t &self)
Store weak pointer to itself.
void initCopy (const PathPtr_t &self)
should be called at copy construction of derived class instances
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
void checkPath () const
Should be called by child classes after having init.
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t timeRange_
Interval of definition.
Detailed Description
Linear interpolation between two configurations.
Degrees of freedom are interpolated depending on the type of joint they parameterize:
linear interpolation for translation joints, bounded rotation joints, and translation part of freeflyer joints,
angular interpolation for unbounded rotation joints,
constant angular velocity for SO(3) part of freeflyer joints.
Member Typedef Documentation
typedef Path hpp::core::StraightPath::parent_t
Constructor & Destructor Documentation
virtual hpp::core::StraightPath::~StraightPath () throw () inline virtual
Destructor.
hpp::core::StraightPath::StraightPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length) protected
Constructor.
hpp::core::StraightPath::StraightPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints) protected
Constructor with constraints.
hpp::core::StraightPath::StraightPath (const StraightPath & path) protected
Copy constructor.
hpp::core::StraightPath::StraightPath (const StraightPath & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
virtual PathPtr_t hpp::core::StraightPath::copy () const inline virtual
Return a shared pointer to this.
As StaightPath are immutable, and refered to by shared pointers, they do not need to be copied.
Implements hpp::core::Path.
virtual PathPtr_t hpp::core::StraightPath::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy *this should not have constraints.
Implements hpp::core::Path.
static StraightPathPtr_t hpp::core::StraightPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length) inline static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
length Distance between the configurations.
References hpp::core::Path::checkPath(), and init().
Referenced by hpp::core::SteeringMethodStraight::impl_compute().
static StraightPathPtr_t hpp::core::StraightPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type length, ConstraintSetPtr_t constraints) inline static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
length Distance between the configurations.
constraints the path is subject to
References hpp::core::Path::checkPath(), and init().
static StraightPathPtr_t hpp::core::StraightPath::createCopy (const StraightPathPtr_t & path) inline static
Create copy and return shared pointer.
Parameters
path path to copy
References hpp::core::Path::checkPath(), and initCopy().
static StraightPathPtr_t hpp::core::StraightPath::createCopy (const StraightPathPtr_t & path, const ConstraintSetPtr_t & constraints) inline static
Create copy and return shared pointer.
Parameters
path path to copy
constraints the path is subject to
References hpp::core::Path::checkPath(), and initCopy().
DevicePtr_t hpp::core::StraightPath::device () const
Return the internal robot.
Configuration_t hpp::core::StraightPath::end () const inline virtual
Get the final configuration.
Implements hpp::core::Path.
void hpp::core::StraightPath::endConfig (ConfigurationIn_t end) inline
Modify end configuration.
Parameters
end new end configuration
Precondition
input configuration should be of the same size as current end configuration
virtual PathPtr_t hpp::core::StraightPath::extract (const interval_t & subInterval) const throw (projection_error) virtual
Extraction/Reversion of a sub-path.
Parameters
subInterval interval of definition of the extract path If upper bound of subInterval is smaller than lower bound, result is reversed.
Reimplemented from hpp::core::Path.
virtual bool hpp::core::StraightPath::impl_compute (ConfigurationOut_t configuration, value_type t) const protected virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implements hpp::core::Path.
void hpp::core::StraightPath::init (StraightPathPtr_t self) inline protected
Referenced by create().
void hpp::core::StraightPath::initCopy (StraightPathPtr_t self) inline protected
Referenced by createCopy().
Configuration_t hpp::core::StraightPath::initial () const inline virtual
Get the initial configuration.
Implements hpp::core::Path.
void hpp::core::StraightPath::initialConfig (ConfigurationIn_t initial) inline
Modify initial configuration.
Parameters
initial new initial configuration
Precondition
input configuration should be of the same size as current initial configuration
virtual std::ostream& hpp::core::StraightPath::print (std::ostream & os) const inline protected virtual
Print path in a stream.
Implements hpp::core::Path.