hpp::core::SteeringMethodStraight Class Reference
hpp::core::SteeringMethodStraight Class Reference
Steering method and distance functions
Steering method that creates StraightPath instances.
#include <hpp/core/steering-method-straight.hh>
Public Member Functions
virtual SteeringMethodPtr_t copy () const
Copy instance and return shared pointer.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Static Public Member Functions
static SteeringMethodStraightPtr_t create (const ProblemPtr_t &problem)
Create instance and return shared pointer.
static SteeringMethodStraightPtr_t create (const DevicePtr_t &device, const WeighedDistancePtr_t &distance) HPP_CORE_DEPRECATED
Create instance and return shared pointer.
static SteeringMethodStraightPtr_t createCopy (const SteeringMethodStraightPtr_t &other)
Copy instance and return shared pointer.
Protected Member Functions
SteeringMethodStraight (const ProblemPtr_t &problem)
Constructor with robot Weighed distance is created from robot.
SteeringMethodStraight (const DevicePtr_t &device, const WeighedDistancePtr_t &distance)
Constructor with weighed distance.
SteeringMethodStraight (const SteeringMethodStraight &other)
Copy constructor.
void init (SteeringMethodStraightWkPtr_t weak)
Store weak pointer to itself.
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (ProblemPtr_t problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Additional Inherited Members
Protected Attributes inherited from hpp::core::SteeringMethod
ProblemPtr_t problem_
Detailed Description
Steering method that creates StraightPath instances.
Constructor & Destructor Documentation
hpp::core::SteeringMethodStraight::SteeringMethodStraight (const ProblemPtr_t & problem) inline protected
Constructor with robot Weighed distance is created from robot.
hpp::core::SteeringMethodStraight::SteeringMethodStraight (const DevicePtr_t & device, const WeighedDistancePtr_t & distance) inline protected
Constructor with weighed distance.
hpp::core::SteeringMethodStraight::SteeringMethodStraight (const SteeringMethodStraight & other) inline protected
Copy constructor.
Member Function Documentation
virtual SteeringMethodPtr_t hpp::core::SteeringMethodStraight::copy () const inline virtual
Copy instance and return shared pointer.
Implements hpp::core::SteeringMethod.
static SteeringMethodStraightPtr_t hpp::core::SteeringMethodStraight::create (const ProblemPtr_t & problem) inline static
Create instance and return shared pointer.
References init().
static SteeringMethodStraightPtr_t hpp::core::SteeringMethodStraight::create (const DevicePtr_t & device, const WeighedDistancePtr_t & distance) inline static
Create instance and return shared pointer.
References init().
static SteeringMethodStraightPtr_t hpp::core::SteeringMethodStraight::createCopy (const SteeringMethodStraightPtr_t & other) inline static
Copy instance and return shared pointer.
References init().
virtual PathPtr_t hpp::core::SteeringMethodStraight::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const inline virtual
create a path between two configurations
Implements hpp::core::SteeringMethod.
References hpp::core::StraightPath::create().
void hpp::core::SteeringMethodStraight::init (SteeringMethodStraightWkPtr_t weak) inline protected
Store weak pointer to itself.
References hpp::core::SteeringMethod::init().
Referenced by create(), and createCopy().