hpp::core::ReedsSheppPath Class Reference
hpp::core::ReedsSheppPath Class Reference
Car like motion.
#include <hpp/core/reeds-shepp-path.hh>
Public Types
typedef core::Path parent_t
Public Member Functions
virtual ~ReedsSheppPath () throw ()
Destructor.
virtual PathPtr_t copy () const
Return a shared pointer to a copy of this object.
virtual PathPtr_t copy (const ConstraintSetPtr_t &constraints) const
Return a shared pointer to a copy of this and set constraints.
DevicePtr_t device () const
Return the internal robot.
Configuration_t initial () const
Get the initial configuration.
Configuration_t end () const
Get the final configuration.
void setSteeringJoint (const JointPtr_t sa)
Set the wheel joint for a motorcycle-like vehicle.
void setWheelJoints (const JointPtr_t left, const JointPtr_t right, const value_type &alphaPrime)
Set the wheel joints for a car-like vehicle.
Public Member Functions inherited from hpp::core::Path
Configuration_t operator() (const value_type &t) const HPP_CORE_DEPRECATED
Configuration_t operator() (const value_type &t, bool &success) const
bool operator() (ConfigurationOut_t result, const value_type &t) const throw ()
bool at (const value_type &t, ConfigurationOut_t result) const
Get the configuration at a parameter without applying the constraints.
size_type outputSize () const
Get size of configuration space.
size_type outputDerivativeSize () const
Get size of velocity.
const interval_t & timeRange () const
Get interval of definition.
value_type length () const
Get length of definition interval.
virtual ~Path () throw ()
Destructor.
template<class T >
boost::shared_ptr< T > as (void)
Static cast into a derived type.
template<class T >
boost::shared_ptr< const T > as (void) const
Static cast into a derived type.
virtual PathPtr_t extract (const interval_t &subInterval) const throw (projection_error)
Extraction/Reversion of a sub-path.
virtual PathPtr_t reverse () const
Reversion of a path.
const ConstraintSetPtr_t & constraints () const
Get constraints the path is subject to.
Static Public Member Functions
static ReedsSheppPathPtr_t create (const model::DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId)
Create instance and return shared pointer.
static ReedsSheppPathPtr_t create (const DevicePtr_t &device, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId, ConstraintSetPtr_t constraints)
Create instance and return shared pointer.
static ReedsSheppPathPtr_t createCopy (const ReedsSheppPathPtr_t &path)
Create copy and return shared pointer.
static ReedsSheppPathPtr_t createCopy (const ReedsSheppPathPtr_t &path, const ConstraintSetPtr_t &constraints)
Create copy and return shared pointer.
Protected Member Functions
virtual std::ostream & print (std::ostream &os) const
Print path in a stream.
ReedsSheppPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId)
Constructor.
ReedsSheppPath (const DevicePtr_t &robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId, ConstraintSetPtr_t constraints)
Constructor with constraints.
ReedsSheppPath (const ReedsSheppPath &path)
Copy constructor.
ReedsSheppPath (const ReedsSheppPath &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (ReedsSheppPathPtr_t self)
void initCopy (ReedsSheppPathPtr_t self)
virtual bool impl_compute (ConfigurationOut_t result, value_type param) const
Function evaluation without applying constraints.
Protected Member Functions inherited from hpp::core::Path
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize, const ConstraintSetPtr_t &constraints)
Constructor.
Path (const interval_t &interval, size_type outputSize, size_type outputDerivativeSize)
Constructor.
Path (const Path &path)
Copy constructor.
Path (const Path &path, const ConstraintSetPtr_t &constraints)
Copy constructor with constraints.
void init (const PathPtr_t &self)
Store weak pointer to itself.
void initCopy (const PathPtr_t &self)
should be called at copy construction of derived class instances
void constraints (const ConstraintSetPtr_t &constraint)
Set the constraints.
void checkPath () const
Should be called by child classes after having init.
Additional Inherited Members
Protected Attributes inherited from hpp::core::Path
interval_t timeRange_
Interval of definition.
Detailed Description
Car like motion.
Implement a Reeds and Shepp motion generation on the base joint. Degrees of freedom are interpolated depending on the type of joint they parameterize: The following interpolation is made:
Reeds and Shepp interpolation for the base_joint_xy and base_joint_rz
If the joint group "reedsshepp_wheels" is present with Device::jointGroup and has 2 joints, then these joints are understood as the left and right wheel (in this order)
If the joint group "reedsshepp_wheels" is present with Device::jointGroup and has 1 joint, then this joints is understood as the only wheel (as a motorcycle)
linear interpolation for the other joints
Member Typedef Documentation
typedef core::Path hpp::core::ReedsSheppPath::parent_t
Constructor & Destructor Documentation
virtual hpp::core::ReedsSheppPath::~ReedsSheppPath () throw () inline virtual
Destructor.
hpp::core::ReedsSheppPath::ReedsSheppPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId) protected
Constructor.
hpp::core::ReedsSheppPath::ReedsSheppPath (const DevicePtr_t & robot, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId, ConstraintSetPtr_t constraints) protected
Constructor with constraints.
hpp::core::ReedsSheppPath::ReedsSheppPath (const ReedsSheppPath & path) protected
Copy constructor.
hpp::core::ReedsSheppPath::ReedsSheppPath (const ReedsSheppPath & path, const ConstraintSetPtr_t & constraints) protected
Copy constructor with constraints.
Member Function Documentation
virtual PathPtr_t hpp::core::ReedsSheppPath::copy () const inline virtual
Return a shared pointer to a copy of this object.
Implements hpp::core::Path.
virtual PathPtr_t hpp::core::ReedsSheppPath::copy (const ConstraintSetPtr_t & constraints) const inline virtual
Return a shared pointer to a copy of this and set constraints.
Parameters
constraints constraints to apply to the copy *this should not have constraints.
Implements hpp::core::Path.
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::create (const model::DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId) static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
rho The radius of a turn.
Referenced by hpp::core::steeringMethod::ReedsShepp::impl_compute().
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::create (const DevicePtr_t & device, ConfigurationIn_t init, ConfigurationIn_t end, value_type rho, size_type xyId, size_type rzId, ConstraintSetPtr_t constraints) static
Create instance and return shared pointer.
Parameters
device Robot corresponding to configurations
init,end Start and end configurations of the path
rho The radius of a turn.
constraints the path is subject to
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::createCopy (const ReedsSheppPathPtr_t & path) inline static
Create copy and return shared pointer.
Parameters
path path to copy
References initCopy().
static ReedsSheppPathPtr_t hpp::core::ReedsSheppPath::createCopy (const ReedsSheppPathPtr_t & path, const ConstraintSetPtr_t & constraints) inline static
Create copy and return shared pointer.
Parameters
path path to copy
constraints the path is subject to
References initCopy().
DevicePtr_t hpp::core::ReedsSheppPath::device () const inline
Return the internal robot.
Configuration_t hpp::core::ReedsSheppPath::end () const inline virtual
Get the final configuration.
Implements hpp::core::Path.
virtual bool hpp::core::ReedsSheppPath::impl_compute (ConfigurationOut_t configuration, value_type t) const protected virtual
Function evaluation without applying constraints.
Returns
true if everything went good.
Implements hpp::core::Path.
void hpp::core::ReedsSheppPath::init (ReedsSheppPathPtr_t self) protected
void hpp::core::ReedsSheppPath::initCopy (ReedsSheppPathPtr_t self) inline protected
Referenced by createCopy().
Configuration_t hpp::core::ReedsSheppPath::initial () const inline virtual
Get the initial configuration.
Implements hpp::core::Path.
virtual std::ostream& hpp::core::ReedsSheppPath::print (std::ostream & os) const inline protected virtual
Print path in a stream.
Implements hpp::core::Path.
void hpp::core::ReedsSheppPath::setSteeringJoint (const JointPtr_t sa) inline
Set the wheel joint for a motorcycle-like vehicle.
void hpp::core::ReedsSheppPath::setWheelJoints (const JointPtr_t left, const JointPtr_t right, const value_type & alphaPrime)
Set the wheel joints for a car-like vehicle.