hpp::core::steeringMethod::Interpolated Class Reference
hpp::core::steeringMethod::Interpolated Class Reference
Steering method and distance functions
Steering method that creates StraightPath instances.
#include <hpp/core/steering-method/interpolated-steering-method.hh>
Public Member Functions
virtual SteeringMethodPtr_t copy () const
Copy instance and return shared pointer.
virtual PathPtr_t impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
Public Member Functions inherited from hpp::core::SteeringMethod
PathPtr_t operator() (ConfigurationIn_t q1, ConfigurationIn_t q2) const
create a path between two configurations
void constraints (const ConstraintSetPtr_t &constraints)
Set constraint set.
const ConstraintSetPtr_t & constraints () const
Get constraint set.
Static Public Member Functions
static InterpolatedPtr_t create (const DevicePtr_t &device)
Create instance and return shared pointer.
static InterpolatedPtr_t create (const DevicePtr_t &device, const WeighedDistancePtr_t &distance)
Create instance and return shared pointer.
static InterpolatedPtr_t createCopy (const InterpolatedPtr_t &other)
Copy instance and return shared pointer.
Protected Member Functions
Interpolated (const DevicePtr_t &device)
Constructor with robot Weighed distance is created from robot.
Interpolated (const DevicePtr_t &device, const WeighedDistancePtr_t &distance)
Constructor with weighed distance.
Interpolated (const Interpolated &other)
Copy constructor.
void init (InterpolatedWkPtr_t weak)
Store weak pointer to itself.
Protected Member Functions inherited from hpp::core::SteeringMethod
SteeringMethod (ProblemPtr_t problem)
Constructor.
SteeringMethod (const SteeringMethod &other)
Copy constructor.
void init (SteeringMethodWkPtr_t weak)
Store weak pointer to itself.
Additional Inherited Members
Protected Attributes inherited from hpp::core::SteeringMethod
ProblemPtr_t problem_
Detailed Description
Steering method that creates StraightPath instances.
Constructor & Destructor Documentation
hpp::core::steeringMethod::Interpolated::Interpolated (const DevicePtr_t & device) inline protected
Constructor with robot Weighed distance is created from robot.
hpp::core::steeringMethod::Interpolated::Interpolated (const DevicePtr_t & device, const WeighedDistancePtr_t & distance) inline protected
Constructor with weighed distance.
hpp::core::steeringMethod::Interpolated::Interpolated (const Interpolated & other) inline protected
Copy constructor.
Member Function Documentation
virtual SteeringMethodPtr_t hpp::core::steeringMethod::Interpolated::copy () const inline virtual
Copy instance and return shared pointer.
Implements hpp::core::SteeringMethod.
static InterpolatedPtr_t hpp::core::steeringMethod::Interpolated::create (const DevicePtr_t & device) inline static
Create instance and return shared pointer.
References init().
static InterpolatedPtr_t hpp::core::steeringMethod::Interpolated::create (const DevicePtr_t & device, const WeighedDistancePtr_t & distance) inline static
Create instance and return shared pointer.
References init().
static InterpolatedPtr_t hpp::core::steeringMethod::Interpolated::createCopy (const InterpolatedPtr_t & other) inline static
Copy instance and return shared pointer.
References init().
virtual PathPtr_t hpp::core::steeringMethod::Interpolated::impl_compute (ConfigurationIn_t q1, ConfigurationIn_t q2) const inline virtual
create a path between two configurations
Implements hpp::core::SteeringMethod.
References hpp::core::InterpolatedPath::create().
void hpp::core::steeringMethod::Interpolated::init (InterpolatedWkPtr_t weak) inline protected
Store weak pointer to itself.
References hpp::core::SteeringMethod::init().
Referenced by create(), and createCopy().