Validation of configurations and paths
Validation of configurations and paths
Paths and configurations need to be validated with respect to various criteria (collision, joint bounds,...) during path planning and path optimization.
Classes
struct hpp::core::CollisionPathValidationReport
Path validation report used for standard collision checking.
struct hpp::core::CollisionValidationReport
Validate a configuration with respect to collision.
class hpp::core::CollisionValidation
Validate a configuration with respect to collision.
class hpp::core::ConfigValidation
Abstraction of configuration validation.
class hpp::core::ConfigValidations
Validate a configuration with respect to collision.
class hpp::core::continuousCollisionChecking::Dichotomy
Continuous validation of a path for collision.
class hpp::core::continuousCollisionChecking::Progressive
Continuous validation of a path for collision.
class hpp::core::DiscretizedCollisionChecking
Validation of path by collision checking at discretized parameter values.
class hpp::core::DiscretizedPathValidation
Discretized validation of a path.
class hpp::core::JointBoundException
Exception thrown when a configuration is not within the bounds.
class hpp::core::JointBoundValidationReport
Exception thrown when a configuration is not within the bounds.
class hpp::core::JointBoundValidation
Validate a configuration with respect to joint bounds.
struct hpp::core::PathValidationReport
Abstraction of path validation report.
class hpp::core::PathValidation
Abstraction of path validation.
class hpp::core::ValidationReport
Abstraction of validation report for paths and configurations.
Typedefs
typedef boost::shared_ptr< BodyPairCollision > hpp::core::continuousCollisionChecking::dichotomy::BodyPairCollisionPtr_t
typedef std::list< BodyPairCollisionPtr_t > hpp::core::continuousCollisionChecking::dichotomy::BodyPairCollisions_t
typedef boost::shared_ptr< BodyPairCollision > hpp::core::continuousCollisionChecking::progressive::BodyPairCollisionPtr_t
typedef std::list< BodyPairCollisionPtr_t > hpp::core::continuousCollisionChecking::progressive::BodyPairCollisions_t
Functions
hpp::core::continuousCollisionChecking::dichotomy::HPP_PREDEF_CLASS (BodyPairCollision)
static DichotomyPtr_t hpp::core::continuousCollisionChecking::Dichotomy::create (const DevicePtr_t &robot, const value_type &tolerance)
Create instance and return shared pointer.
virtual bool hpp::core::continuousCollisionChecking::Dichotomy::validate (const PathPtr_t &path, bool reverse, PathPtr_t &validPart) HPP_CORE_DEPRECATED
Compute a valid interval starting from the path beginning.
virtual bool hpp::core::continuousCollisionChecking::Dichotomy::validate (const PathPtr_t &path, bool reverse, PathPtr_t &validPart, ValidationReport &report) HPP_CORE_DEPRECATED
Compute a valid interval starting from the path beginning.
virtual bool hpp::core::continuousCollisionChecking::Dichotomy::validate (const PathPtr_t &path, bool reverse, PathPtr_t &validPart, PathValidationReportPtr_t &report)
Compute the largest valid interval starting from the path beginning.
virtual void hpp::core::continuousCollisionChecking::Dichotomy::addObstacle (const CollisionObjectPtr_t &object)
Add an obstacle.
virtual void hpp::core::continuousCollisionChecking::Dichotomy::removeObstacleFromJoint (const JointPtr_t &joint, const CollisionObjectPtr_t &obstacle)
Remove a collision pair between a joint and an obstacle.
virtual hpp::core::continuousCollisionChecking::Dichotomy::~Dichotomy ()
hpp::core::continuousCollisionChecking::Dichotomy::Dichotomy (const DevicePtr_t &robot, const value_type &tolerance)
Constructor.
hpp::core::continuousCollisionChecking::progressive::HPP_PREDEF_CLASS (BodyPairCollision)
static ProgressivePtr_t hpp::core::continuousCollisionChecking::Progressive::create (const DevicePtr_t &robot, const value_type &tolerance)
Create instance and return shared pointer.
virtual bool hpp::core::continuousCollisionChecking::Progressive::validate (const PathPtr_t &path, bool reverse, PathPtr_t &validPart) HPP_CORE_DEPRECATED
Compute a valid interval starting from the path beginning.
virtual bool hpp::core::continuousCollisionChecking::Progressive::validate (const PathPtr_t &path, bool reverse, PathPtr_t &validPart, ValidationReport &validationReport) HPP_CORE_DEPRECATED
Compute a valid interval starting from the path beginning.
virtual bool hpp::core::continuousCollisionChecking::Progressive::validate (const PathPtr_t &path, bool reverse, PathPtr_t &validPart, PathValidationReportPtr_t &report)
Compute the largest valid interval starting from the path beginning.
virtual void hpp::core::continuousCollisionChecking::Progressive::addObstacle (const CollisionObjectPtr_t &object)
Add an obstacle.
virtual void hpp::core::continuousCollisionChecking::Progressive::removeObstacleFromJoint (const JointPtr_t &joint, const CollisionObjectPtr_t &obstacle)
Remove a collision pair between a joint and an obstacle.
virtual hpp::core::continuousCollisionChecking::Progressive::~Progressive ()
hpp::core::continuousCollisionChecking::Progressive::Progressive (const DevicePtr_t &robot, const value_type &tolerance)
Constructor.
std::ostream & hpp::core::operator<< (std::ostream &os, const ValidationReport &report)
Detailed Description
Paths and configurations need to be validated with respect to various criteria (collision, joint bounds,...) during path planning and path optimization.
Validation of a configuration or of a path gives rise to a validation report that provide information if validation failed.
Typedef Documentation
typedef boost::shared_ptr< BodyPairCollision > hpp::core::continuousCollisionChecking::dichotomy::BodyPairCollisionPtr_t
typedef boost::shared_ptr< BodyPairCollision > hpp::core::continuousCollisionChecking::progressive::BodyPairCollisionPtr_t
typedef std::list<BodyPairCollisionPtr_t> hpp::core::continuousCollisionChecking::progressive::BodyPairCollisions_t
typedef std::list<BodyPairCollisionPtr_t> hpp::core::continuousCollisionChecking::dichotomy::BodyPairCollisions_t
Function Documentation
void hpp::core::continuousCollisionChecking::Progressive::addObstacle (const CollisionObjectPtr_t & object) virtual
Add an obstacle.
Parameters
object obstacle added Add the object to each collision pair a body of which is the environment. care about obstacles.
Reimplemented from hpp::core::PathValidation.
void hpp::core::continuousCollisionChecking::Dichotomy::addObstacle (const CollisionObjectPtr_t & object) virtual
Add an obstacle.
Parameters
object obstacle added Add the object to each collision pair a body of which is the environment. care about obstacles.
Reimplemented from hpp::core::PathValidation.
ProgressivePtr_t hpp::core::continuousCollisionChecking::Progressive::create (const DevicePtr_t & robot, const value_type & tolerance) static
Create instance and return shared pointer.
Parameters
robot the robot for which collision checking is performed,
tolerance maximal penetration allowed.
References hpp::core::continuousCollisionChecking::Progressive::Progressive().
Referenced by hpp::core::ProblemSolver::ProblemSolver().
DichotomyPtr_t hpp::core::continuousCollisionChecking::Dichotomy::create (const DevicePtr_t & robot, const value_type & tolerance) static
Create instance and return shared pointer.
Parameters
robot the robot for which collision checking is performed,
tolerance maximal penetration allowed.
References hpp::core::continuousCollisionChecking::Dichotomy::Dichotomy().
Referenced by hpp::core::ProblemSolver::ProblemSolver().
hpp::core::continuousCollisionChecking::Dichotomy::Dichotomy (const DevicePtr_t & robot, const value_type & tolerance) protected
Constructor.
Parameters
robot the robot for which collision checking is performed,
tolerance maximal penetration allowed.
References hpp::model::COLLISION.
Referenced by hpp::core::continuousCollisionChecking::Dichotomy::create().
hpp::core::continuousCollisionChecking::dichotomy::HPP_PREDEF_CLASS (BodyPairCollision)
hpp::core::continuousCollisionChecking::progressive::HPP_PREDEF_CLASS (BodyPairCollision)
std::ostream& hpp::core::operator<< (std::ostream & os, const ValidationReport & report) inline
References hpp::core::ValidationReport::print().
hpp::core::continuousCollisionChecking::Progressive::Progressive (const DevicePtr_t & robot, const value_type & tolerance) protected
Constructor.
Parameters
robot the robot for which collision checking is performed,
tolerance maximal penetration allowed.
References hpp::model::COLLISION.
Referenced by hpp::core::continuousCollisionChecking::Progressive::create().
void hpp::core::continuousCollisionChecking::Progressive::removeObstacleFromJoint (const JointPtr_t & joint, const CollisionObjectPtr_t & obstacle) virtual
Remove a collision pair between a joint and an obstacle.
Parameters
the joint that holds the inner objects,
the obstacle to remove. collision configuration validation needs to know about obstacles. This virtual method does nothing for configuration validation methods that do not care about obstacles.
Reimplemented from hpp::core::PathValidation.
References hpp::model::Joint::name().
void hpp::core::continuousCollisionChecking::Dichotomy::removeObstacleFromJoint (const JointPtr_t & joint, const CollisionObjectPtr_t & obstacle) virtual
Remove a collision pair between a joint and an obstacle.
Parameters
the joint that holds the inner objects,
the obstacle to remove. collision configuration validation needs to know about obstacles. This virtual method does nothing for configuration validation methods that do not care about obstacles.
Reimplemented from hpp::core::PathValidation.
References hpp::model::Joint::name().
bool hpp::core::continuousCollisionChecking::Progressive::validate (const PathPtr_t & path, bool reverse, PathPtr_t & validPart) virtual
Compute a valid interval starting from the path beginning.
Parameters
path the path to check for validity,
reverse if true check from the end,
Return values
the extracted valid part of the path, pointer to path if path is valid.
report information about the validation process. The type can be derived for specific implementation
Returns
whether the whole path is valid. validationReport should be a of type CollisionPathValidationReport.
Implements hpp::core::PathValidation.
Referenced by hpp::core::continuousCollisionChecking::Progressive::validate().
bool hpp::core::continuousCollisionChecking::Dichotomy::validate (const PathPtr_t & path, bool reverse, PathPtr_t & validPart) virtual
Compute a valid interval starting from the path beginning.
Parameters
path the path to check for validity,
reverse if true check from the end,
Return values
the extracted valid part of the path, pointer to path if path is valid.
report information about the validation process. The type can be derived for specific implementation
Returns
whether the whole path is valid. validationReport should be a of type CollisionPathValidationReport.
Implements hpp::core::PathValidation.
Referenced by hpp::core::continuousCollisionChecking::Dichotomy::validate().
bool hpp::core::continuousCollisionChecking::Progressive::validate (const PathPtr_t & path, bool reverse, PathPtr_t & validPart, ValidationReport & validationReport) virtual
Compute a valid interval starting from the path beginning.
Parameters
path the path to check for validity,
reverse if true check from the end,
Return values
the extracted valid part of the path, pointer to path if path is valid.
Returns
whether the whole path is valid.
Return values
validationReport information about the validation process: which objects have been detected in collision and at which parameter along the path. validationReport should be a of type CollisionPathValidationReport.
Implements hpp::core::PathValidation.
References hpp::core::PathVector::create(), and hpp::core::PathValidationReport::parameter.
bool hpp::core::continuousCollisionChecking::Dichotomy::validate (const PathPtr_t & path, bool reverse, PathPtr_t & validPart, ValidationReport & report) virtual
Compute a valid interval starting from the path beginning.
Parameters
path the path to check for validity,
reverse if true check from the end,
Return values
the extracted valid part of the path, pointer to path if path is valid.
Returns
whether the whole path is valid.
Return values
report information about the validation process. validationReport should be a of type CollisionPathValidationReport.
Implements hpp::core::PathValidation.
References hpp::core::continuousCollisionChecking::compareBodyPairCol(), hpp::core::continuousCollisionChecking::compareReverseBodyPairCol(), hpp::core::PathValidationReport::configurationReport, hpp::core::PathVector::create(), hpp::core::PathValidationReport::parameter, and hpp::core::continuousCollisionChecking::partialSort().
bool hpp::core::continuousCollisionChecking::Dichotomy::validate (const PathPtr_t & path, bool reverse, PathPtr_t & validPart, PathValidationReportPtr_t & report) virtual
Compute the largest valid interval starting from the path beginning.
Parameters
path the path to check for validity,
reverse if true check from the end,
Return values
the extracted valid part of the path, pointer to path if path is valid.
report information about the validation process. A report is allocated if the path is not valid.
Returns
whether the whole path is valid.
Implements hpp::core::PathValidation.
References hpp::core::continuousCollisionChecking::compareBodyPairCol(), hpp::core::continuousCollisionChecking::compareReverseBodyPairCol(), hpp::core::PathVector::create(), hpp::core::continuousCollisionChecking::partialSort(), and hpp::core::continuousCollisionChecking::Dichotomy::validate().
bool hpp::core::continuousCollisionChecking::Progressive::validate (const PathPtr_t & path, bool reverse, PathPtr_t & validPart, PathValidationReportPtr_t & report) virtual
Compute the largest valid interval starting from the path beginning.
Parameters
path the path to check for validity,
reverse if true check from the end,
Return values
the extracted valid part of the path, pointer to path if path is valid.
report information about the validation process. A report is allocated if the path is not valid.
Returns
whether the whole path is valid.
Implements hpp::core::PathValidation.
References hpp::core::PathVector::create(), and hpp::core::continuousCollisionChecking::Progressive::validate().
hpp::core::continuousCollisionChecking::Dichotomy::~Dichotomy () virtual
hpp::core::continuousCollisionChecking::Progressive::~Progressive () virtual