Path Optimization
Path Optimization
Path optimization algorithms derive from class hpp::core::PathOptimizer.
Namespaces
hpp::core::pathOptimization
Classes
struct hpp::core::pathOptimization::ConfigOptimizationTraits
Optimize the waypoints of the path and optionally add the constraint::ConfigurationConstraint to the ConfigProjector of the path.
struct hpp::core::pathOptimization::ConfigOptimization::Parameters
struct hpp::core::pathOptimization::ConfigOptimization::Optimizer
class hpp::core::pathOptimization::ConfigOptimization
class hpp::core::pathOptimization::GradientBased
struct hpp::core::pathOptimization::PartialShortcutTraits
Partial shortcut.
struct hpp::core::pathOptimization::PartialShortcut::Parameters
class hpp::core::pathOptimization::PartialShortcut
class hpp::core::PathOptimizer
Abstraction of path optimizer.
class hpp::core::RandomShortcut
Random shortcut.
Typedefs
typedef std::vector< CollisionConstraintsResult > hpp::core::pathOptimization::CollisionConstraintsResults_t
Functions
static GradientBasedPtr_t hpp::core::pathOptimization::GradientBased::create (const Problem &problem)
Return shared pointer to new object.
virtual PathVectorPtr_t hpp::core::pathOptimization::GradientBased::optimize (const PathVectorPtr_t &path)
Optimize path.
hpp::core::pathOptimization::GradientBased::GradientBased (const Problem &problem)
const Problem & hpp::core::PathOptimizer::problem () const
Get problem.
virtual PathVectorPtr_t hpp::core::PathOptimizer::optimize (const PathVectorPtr_t &path)=0
Optimize path.
void hpp::core::PathOptimizer::interrupt ()
Interrupt path optimization.
hpp::core::PathOptimizer::PathOptimizer (const Problem &problem)
PathPtr_t hpp::core::PathOptimizer::steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const
Variables
bool hpp::core::PathOptimizer::interrupt_
Whether to interrupt computation Set to true at start of optimize method, set to false by method interrupt.
Detailed Description
Path optimization algorithms derive from class hpp::core::PathOptimizer.
Typedef Documentation
typedef std::vector< CollisionConstraintsResult > hpp::core::pathOptimization::CollisionConstraintsResults_t
Function Documentation
GradientBasedPtr_t hpp::core::pathOptimization::GradientBased::create (const Problem & problem) static
Return shared pointer to new object.
Default cost is path length.
Referenced by hpp::core::ProblemSolver::ProblemSolver().
hpp::core::pathOptimization::GradientBased::GradientBased (const Problem & problem) protected
References hpp::core::Problem::distance(), and hpp::core::Problem::steeringMethod().
void hpp::core::PathOptimizer::interrupt () inline
Interrupt path optimization.
virtual PathVectorPtr_t hpp::core::PathOptimizer::optimize (const PathVectorPtr_t & path) pure virtual
Optimize path.
Implemented in hpp::core::pathOptimization::ConfigOptimization, hpp::core::pathOptimization::PartialShortcut, hpp::core::RandomShortcut, and hpp::core::pathOptimization::GradientBased.
PathVectorPtr_t hpp::core::pathOptimization::GradientBased::optimize (const PathVectorPtr_t & path) virtual
Optimize path.
Implements hpp::core::PathOptimizer.
References hpp::core::PathVector::create(), hpp::core::PathOptimizer::interrupt_, and hpp::core::pathOptimization::validatePath().
hpp::core::PathOptimizer::PathOptimizer (const Problem & problem) inline protected
const Problem& hpp::core::PathOptimizer::problem () const inline
Get problem.
Referenced by hpp::core::pathOptimization::ConfigOptimization::buildOptimizers(), hpp::core::pathOptimization::PartialShortcut::create(), hpp::core::pathOptimization::ConfigOptimization::create(), hpp::core::RandomShortcut::optimize(), hpp::core::pathOptimization::ConfigOptimization::optimize(), and hpp::core::PathOptimizer::steer().
PathPtr_t hpp::core::PathOptimizer::steer (ConfigurationIn_t q1, ConfigurationIn_t q2) const protected
References hpp::core::Problem::pathProjector(), hpp::core::PathOptimizer::problem(), and hpp::core::Problem::steeringMethod().
Referenced by hpp::core::RandomShortcut::optimize(), and hpp::core::pathOptimization::ConfigOptimization::optimize().
Variable Documentation
bool hpp::core::PathOptimizer::interrupt_ protected
Whether to interrupt computation Set to true at start of optimize method, set to false by method interrupt.
Referenced by hpp::core::pathOptimization::GradientBased::optimize().