hpp::core::continuousCollisionChecking Namespace Reference
hpp::core::continuousCollisionChecking Namespace Reference
Namespaces
dichotomy
progressive
Classes
class Dichotomy
Continuous validation of a path for collision.
class Intervals
Union of intervals.
class Progressive
Continuous validation of a path for collision.
Typedefs
typedef boost::shared_ptr< Dichotomy > DichotomyPtr_t
typedef boost::shared_ptr< Progressive > ProgressivePtr_t
Functions
HPP_PREDEF_CLASS (Dichotomy)
HPP_PREDEF_CLASS (Progressive)
bool compareBodyPairCol (const BodyPairCollisionPtr_t &bodyPair1, const BodyPairCollisionPtr_t &bodyPair2)
bool compareReverseBodyPairCol (const BodyPairCollisionPtr_t &bodyPair1, const BodyPairCollisionPtr_t &bodyPair2)
template<typename Compare >
void partialSort (BodyPairCollisions_t &list, Compare comp)
bool lastElement (const std::list< interval_t > &list, const std::list< interval_t >::iterator &it)
Typedef Documentation
typedef boost::shared_ptr<Dichotomy> hpp::core::continuousCollisionChecking::DichotomyPtr_t
typedef boost::shared_ptr<Progressive> hpp::core::continuousCollisionChecking::ProgressivePtr_t
Function Documentation
bool hpp::core::continuousCollisionChecking::compareBodyPairCol (const BodyPairCollisionPtr_t & bodyPair1, const BodyPairCollisionPtr_t & bodyPair2)
Referenced by hpp::core::continuousCollisionChecking::Dichotomy::validate().
bool hpp::core::continuousCollisionChecking::compareReverseBodyPairCol (const BodyPairCollisionPtr_t & bodyPair1, const BodyPairCollisionPtr_t & bodyPair2)
Referenced by hpp::core::continuousCollisionChecking::Dichotomy::validate().
hpp::core::continuousCollisionChecking::HPP_PREDEF_CLASS (Dichotomy)
hpp::core::continuousCollisionChecking::HPP_PREDEF_CLASS (Progressive)
bool hpp::core::continuousCollisionChecking::lastElement (const std::list< interval_t > & list, const std::list< interval_t >::iterator & it) inline
Referenced by hpp::core::continuousCollisionChecking::Intervals::unionInterval().
template<typename Compare > void hpp::core::continuousCollisionChecking::partialSort (BodyPairCollisions_t & list, Compare comp)
Referenced by hpp::core::continuousCollisionChecking::Dichotomy::validate().