hpp::wholebodyStep::Steps Struct Reference
hpp::wholebodyStep::Steps Struct Reference
#include <small-steps/stepper.hh>
Public Types
typedef std::vector< Step * > Vector
typedef Vector::iterator iterator
typedef Vector::const_iterator const_iterator
typedef std::size_t index_t
Public Member Functions
void narrow (const value_type &invalid_time)
SmallSteps::PiecewiseAffine timing () const
void initPhase (const value_type &duration, const value_type &param, const bool toLeftSupport)
Builder.
void appendStep (const value_type &SStime, const value_type &DDtime, const value_type &param)
void endPhase (const value_type &SStime, const value_type &duration, const value_type &param)
Public Attributes
Vector steps_
InitBoundary * init_
EndBoundary * end_
value_type t0
Member Typedef Documentation
typedef Vector::const_iterator hpp::wholebodyStep::Steps::const_iterator
typedef std::size_t hpp::wholebodyStep::Steps::index_t
typedef Vector::iterator hpp::wholebodyStep::Steps::iterator
typedef std::vector<Step*> hpp::wholebodyStep::Steps::Vector
Member Function Documentation
void hpp::wholebodyStep::Steps::appendStep (const value_type & SStime, const value_type & DDtime, const value_type & param) inline
References hpp::wholebodyStep::Step::DStime, hpp::wholebodyStep::Step::leftSupport, hpp::wholebodyStep::Step::param, and hpp::wholebodyStep::Step::SStime.
void hpp::wholebodyStep::Steps::endPhase (const value_type & SStime, const value_type & duration, const value_type & param) inline
References hpp::wholebodyStep::Step::DStime, hpp::wholebodyStep::Step::leftSupport, hpp::wholebodyStep::Step::param, and hpp::wholebodyStep::Step::SStime.
void hpp::wholebodyStep::Steps::initPhase (const value_type & duration, const value_type & param, const bool toLeftSupport) inline
Builder.
References init().
void hpp::wholebodyStep::Steps::narrow (const value_type & invalid_time) inline
References hpp::wholebodyStep::Step::createAfter(), and hpp::wholebodyStep::Step::createBefore().
SmallSteps::PiecewiseAffine hpp::wholebodyStep::Steps::timing () const inline
References hpp::wholebodyStep::SmallSteps::PiecewiseAffine::addPair(), and t0.
Member Data Documentation
EndBoundary* hpp::wholebodyStep::Steps::end_
InitBoundary* hpp::wholebodyStep::Steps::init_
Vector hpp::wholebodyStep::Steps::steps_
value_type hpp::wholebodyStep::Steps::t0
Referenced by timing().