hpp::wholebodyStep Namespace Reference
hpp::wholebodyStep Namespace Reference
Classes
struct CubicBSplineToCom
struct EndBoundary
struct FootPathToFootPos
struct InitBoundary
struct ReproducePath
struct RightHandSideFunctor
class SmallSteps
Plan a sliding path for a humanoid robot and generate a walk motion along this path.
struct Step
struct Steps
struct Support
struct TimeDependant
class TimeDependantPath
Typedefs
typedef model::JointPtr_t JointPtr_t
typedef core::EquationPtr_t EquationPtr_t
typedef core::NumericalConstraint NumericalConstraint
typedef core::NumericalConstraintPtr_t NumericalConstraintPtr_t
typedef core::ConstraintSet ConstraintSet
typedef core::ConstraintSetPtr_t ConstraintSetPtr_t
typedef core::ConfigProjector ConfigProjector
typedef core::ConfigProjectorPtr_t ConfigProjectorPtr_t
typedef core::DifferentiableFunctionPtr_t DifferentiableFunctionPtr_t
typedef core::DifferentiableFunction DifferentiableFunction
typedef constraints::JointFrame JointFrame
typedef constraints::Traits< constraints::JointFrame >::Ptr_t JointFramePtr_t
typedef constraints::SymbolicFunction< JointFrame > JointFrameFunction
typedef constraints::SymbolicFunction< JointFrame >::Ptr_t JointFrameFunctionPtr_t
typedef constraints::PointInJoint PointInJoint
typedef constraints::SymbolicFunction< PointInJoint > PointInJointFunction
typedef constraints::PointCom PointCom
typedef constraints::SymbolicFunction< PointCom > PointComFunction
typedef constraints::SymbolicFunction< PointCom >::Ptr_t PointComFunctionPtr_t
typedef core::Problem Problem
typedef core::PathOptimizerPtr_t PathOptimizerPtr_t
typedef core::Path Path
typedef core::PathPtr_t PathPtr_t
typedef core::PathVector PathVector
typedef core::PathVectorPtr_t PathVectorPtr_t
typedef core::StraightPath StraightPath
typedef core::StraightPathPtr_t StraightPathPtr_t
typedef model::CenterOfMassComputationPtr_t CenterOfMassComputationPtr_t
typedef model::DevicePtr_t DevicePtr_t
typedef model::HumanoidRobotPtr_t HumanoidRobotPtr_t
typedef model::HumanoidRobot HumanoidRobot
typedef model::Configuration_t Configuration_t
typedef model::ConfigurationIn_t ConfigurationIn_t
typedef model::ConfigurationOut_t ConfigurationOut_t
typedef model::Transform3f Transform3f
typedef model::matrix3_t matrix3_t
typedef model::vector3_t vector3_t
typedef model::vector_t vector_t
typedef model::vectorOut_t vectorOut_t
typedef core::value_type value_type
typedef core::size_type size_type
typedef walkgen::FootPrint FootPrint
typedef walkgen::SplineBasedPtr_t SplineBasedPtr_t
typedef walkgen::SplineBased SplineBased
typedef walkgen::CubicBSplinePtr_t CubicBSplinePtr_t
typedef boost::shared_ptr< SmallSteps > SmallStepsPtr_t
typedef boost::shared_ptr< TimeDependantPath > TimeDependantPathPtr_t
typedef boost::shared_ptr< const RightHandSideFunctor > RightHandSideFunctorPtr_t
Functions
HPP_PREDEF_CLASS (SmallSteps)
HPP_PREDEF_CLASS (TimeDependantPath)
std::vector< NumericalConstraintPtr_t > createSlidingStabilityConstraint (const DevicePtr_t &robot, const CenterOfMassComputationPtr_t &comc, const JointPtr_t &leftAnkle, const JointPtr_t &rightAnkle, ConfigurationIn_t configuration)
Create quasi-static stability constraints.
std::vector< NumericalConstraintPtr_t > createSlidingStabilityConstraint (const DevicePtr_t &robot, const JointPtr_t &leftAnkle, const JointPtr_t &rightAnkle, ConfigurationIn_t configuration)
Create quasi-static stability constraints The center of mass takes into account all the joints of the robot.
std::vector< NumericalConstraintPtr_t > createSlidingStabilityConstraintComplement (const DevicePtr_t &robot, const JointPtr_t &leftAnkle, ConfigurationIn_t configuration)
Create quasi-static stability complementary constraints.
std::vector< NumericalConstraintPtr_t > createAlignedCOMStabilityConstraint (const DevicePtr_t &robot, const CenterOfMassComputationPtr_t &comc, const JointPtr_t &leftAnkle, const JointPtr_t &rightAnkle, ConfigurationIn_t configuration)
Constraints that ensure that the COM is between the two ankles.
Variables
const std::string STABILITY_CONTEXT = "stability"
Typedef Documentation
typedef model::CenterOfMassComputationPtr_t hpp::wholebodyStep::CenterOfMassComputationPtr_t
typedef core::ConfigProjector hpp::wholebodyStep::ConfigProjector
typedef core::ConfigProjectorPtr_t hpp::wholebodyStep::ConfigProjectorPtr_t
typedef model::Configuration_t hpp::wholebodyStep::Configuration_t
typedef model::ConfigurationIn_t hpp::wholebodyStep::ConfigurationIn_t
typedef model::ConfigurationOut_t hpp::wholebodyStep::ConfigurationOut_t
typedef core::ConstraintSet hpp::wholebodyStep::ConstraintSet
typedef core::ConstraintSetPtr_t hpp::wholebodyStep::ConstraintSetPtr_t
typedef walkgen::CubicBSplinePtr_t hpp::wholebodyStep::CubicBSplinePtr_t
typedef model::DevicePtr_t hpp::wholebodyStep::DevicePtr_t
typedef core::DifferentiableFunction hpp::wholebodyStep::DifferentiableFunction
typedef core::DifferentiableFunctionPtr_t hpp::wholebodyStep::DifferentiableFunctionPtr_t
typedef core::EquationPtr_t hpp::wholebodyStep::EquationPtr_t
typedef walkgen::FootPrint hpp::wholebodyStep::FootPrint
typedef model::HumanoidRobot hpp::wholebodyStep::HumanoidRobot
typedef model::HumanoidRobotPtr_t hpp::wholebodyStep::HumanoidRobotPtr_t
typedef constraints::JointFrame hpp::wholebodyStep::JointFrame
typedef constraints::SymbolicFunction<JointFrame> hpp::wholebodyStep::JointFrameFunction
typedef constraints::SymbolicFunction<JointFrame>::Ptr_t hpp::wholebodyStep::JointFrameFunctionPtr_t
typedef constraints::Traits<constraints::JointFrame>::Ptr_t hpp::wholebodyStep::JointFramePtr_t
typedef model::JointPtr_t hpp::wholebodyStep::JointPtr_t
typedef model::matrix3_t hpp::wholebodyStep::matrix3_t
typedef core::NumericalConstraint hpp::wholebodyStep::NumericalConstraint
typedef core::NumericalConstraintPtr_t hpp::wholebodyStep::NumericalConstraintPtr_t
typedef core::Path hpp::wholebodyStep::Path
typedef core::PathOptimizerPtr_t hpp::wholebodyStep::PathOptimizerPtr_t
typedef core::PathPtr_t hpp::wholebodyStep::PathPtr_t
typedef core::PathVector hpp::wholebodyStep::PathVector
typedef core::PathVectorPtr_t hpp::wholebodyStep::PathVectorPtr_t
typedef constraints::PointCom hpp::wholebodyStep::PointCom
typedef constraints::SymbolicFunction<PointCom> hpp::wholebodyStep::PointComFunction
typedef constraints::SymbolicFunction<PointCom>::Ptr_t hpp::wholebodyStep::PointComFunctionPtr_t
typedef constraints::PointInJoint hpp::wholebodyStep::PointInJoint
typedef constraints::SymbolicFunction<PointInJoint> hpp::wholebodyStep::PointInJointFunction
typedef core::Problem hpp::wholebodyStep::Problem
typedef boost::shared_ptr<const RightHandSideFunctor> hpp::wholebodyStep::RightHandSideFunctorPtr_t
typedef core::size_type hpp::wholebodyStep::size_type
typedef boost::shared_ptr<SmallSteps> hpp::wholebodyStep::SmallStepsPtr_t
typedef walkgen::SplineBased hpp::wholebodyStep::SplineBased
typedef walkgen::SplineBasedPtr_t hpp::wholebodyStep::SplineBasedPtr_t
typedef core::StraightPath hpp::wholebodyStep::StraightPath
typedef core::StraightPathPtr_t hpp::wholebodyStep::StraightPathPtr_t
typedef boost::shared_ptr<TimeDependantPath> hpp::wholebodyStep::TimeDependantPathPtr_t
typedef model::Transform3f hpp::wholebodyStep::Transform3f
typedef core::value_type hpp::wholebodyStep::value_type
typedef model::vector3_t hpp::wholebodyStep::vector3_t
typedef model::vector_t hpp::wholebodyStep::vector_t
typedef model::vectorOut_t hpp::wholebodyStep::vectorOut_t
Function Documentation
std::vector< NumericalConstraintPtr_t > hpp::wholebodyStep::createAlignedCOMStabilityConstraint (const DevicePtr_t & robot, const CenterOfMassComputationPtr_t & comc, const JointPtr_t & leftAnkle, const JointPtr_t & rightAnkle, ConfigurationIn_t configuration)
Constraints that ensure that the COM is between the two ankles.
Parameters
robot the robot,
comc a hpp::model::CenterOfMassComputation that handle COM computations.
leftAnkle left ankle joint,
rightAnkle right ankle joint,
configuration the configuration of the robot satisfying the constraint,
Create a the following set of constraints:
ComBetweenFeet constraints (dimension 3)
orientation of the right foot around x and y (dimension 2),
position of the right foot along z (dimension 1),
orientation of the left foot around x and y (dimension 2),
position of the left foot along z (dimension 1),
References hpp::core::NumericalConstraint::create(), create(), hpp::core::ComparisonTypes::create(), hpp::core::ComparisonType::EqualToZero, hpp::core::ComparisonType::Inferior, and hpp::core::ComparisonType::Superior.
std::vector< NumericalConstraintPtr_t > hpp::wholebodyStep::createSlidingStabilityConstraint (const DevicePtr_t & robot, const CenterOfMassComputationPtr_t & comc, const JointPtr_t & leftAnkle, const JointPtr_t & rightAnkle, ConfigurationIn_t configuration)
Create quasi-static stability constraints.
Parameters
robot the robot,
comc a hpp::model::CenterOfMassComputation that handle COM computations.
leftAnkle left ankle joint,
rightAnkle right ankle joint,
configuration the configuration of the robot satisfying the constraint,
The constraints make the feet of the robot slide on a horizontal ground and the center of mass project at a constant position with respect to the feet. Five constraints are returned:
relative position of the center of mass (as defined with comc) in the left ankle frame (dimension 3),
relative orientation of the feet (dimension 3),
relative position of the feet (dimension 3),
orientation of the left foot (dimension 2),
position of the left foot (dimension 1).
All constraints are returned along with the hpp::core::ComparisonType::createDefault()
References hpp::core::NumericalConstraint::create(), and create().
Referenced by createSlidingStabilityConstraint().
std::vector< NumericalConstraintPtr_t > hpp::wholebodyStep::createSlidingStabilityConstraint (const DevicePtr_t & robot, const JointPtr_t & leftAnkle, const JointPtr_t & rightAnkle, ConfigurationIn_t configuration)
Create quasi-static stability constraints The center of mass takes into account all the joints of the robot.
Parameters
robot,leftAnkle,rightAnkle,configuration see createSlidingStabilityConstraint(const DevicePtr_t&, const JointPtr_t&, const JointPtr_t&, ConfigurationIn_t)
References create(), and createSlidingStabilityConstraint().
std::vector< NumericalConstraintPtr_t > hpp::wholebodyStep::createSlidingStabilityConstraintComplement (const DevicePtr_t & robot, const JointPtr_t & leftAnkle, ConfigurationIn_t configuration)
Create quasi-static stability complementary constraints.
Parameters
robot the robot,
comc a hpp::model::CenterOfMassComputation that handle COM computations.
leftAnkle left ankle joint,
configuration the configuration of the robot satisfying the constraint,
Used with the quasi-static stability constraints, the constraints make the feet and the center of mass of the robot at a constant position. Two constraints are returned:
orientation of the left foot (dimension 1),
position of the left foot (dimension 2).
All constraints are returned along with the hpp::core::ComparisonType::createDefault()
References hpp::core::NumericalConstraint::create(), hpp::core::Equality::create(), and create().
hpp::wholebodyStep::HPP_PREDEF_CLASS (SmallSteps)
hpp::wholebodyStep::HPP_PREDEF_CLASS (TimeDependantPath)
Variable Documentation
const std::string hpp::wholebodyStep::STABILITY_CONTEXT = "stability"