hpp::manipulation::Handle Class Reference
hpp::manipulation::Handle Class Reference
Part of an object that is aimed at being grasped.
#include <hpp/manipulation/handle.hh>
Public Member Functions
virtual HandlePtr_t clone () const
Return a pointer to the copy of this.
const Transform3f & localPosition () const
Get local position in joint frame.
virtual NumericalConstraintPtr_t createGrasp (const GripperPtr_t &gripper) const
Create constraint corresponding to a gripper grasping this object.
virtual NumericalConstraintPtr_t createGraspComplement (const GripperPtr_t &gripper) const
Create constraint that acts on the non-constrained axis of the constraint generated by Handle::createGrasp.
virtual NumericalConstraintPtr_t createPreGrasp (const GripperPtr_t &gripper, const value_type &shift) const
Create constraint corresponding to a pregrasping task.
value_type clearance () const
Get the clearance.
void clearance (const value_type &clearance)
Set the clearance.
Name
const std::string & name () const
Get name.
void name (const std::string &n)
Set name.
Joint
const JointPtr_t & joint () const
Get joint to which the handle is linked.
void joint (const JointPtr_t &joint)
Set joint to which the handle is linked.
Static Public Member Functions
static HandlePtr_t create (const std::string &name, const Transform3f &localPosition, const JointPtr_t &joint)
Create constraint corresponding to a gripper grasping this object.
static NumericalConstraintPtr_t createGrasp (const GripperPtr_t &gripper, const HandlePtr_t &handle)
Protected Member Functions
Handle (const std::string &name, const Transform3f &localPosition, const JointPtr_t &joint)
Constructor.
void init (HandleWkPtr_t weakPtr)
virtual std::ostream & print (std::ostream &os) const
Friends
std::ostream & operator<< (std::ostream &, const Handle &)
Detailed Description
Part of an object that is aimed at being grasped.
Constructor & Destructor Documentation
hpp::manipulation::Handle::Handle (const std::string & name, const Transform3f & localPosition, const JointPtr_t & joint) inline protected
Constructor.
Parameters
robot the robot that grasps the handle,
grasp object containing the grasp information
Returns
the constraint of relative position between the handle and the gripper.
Referenced by create().
Member Function Documentation
value_type hpp::manipulation::Handle::clearance () const inline
Get the clearance.
The clearance is a distance, from the center of the gripper and along the x-aixs, that "ensures" an object being at that distance is not colliding with this gripper. It also gives an order of magnitude of the size of the gripper.
Referenced by clearance().
void hpp::manipulation::Handle::clearance (const value_type & clearance) inline
Set the clearance.
See also
clearance()
References clearance().
virtual HandlePtr_t hpp::manipulation::Handle::clone () const virtual
Return a pointer to the copy of this.
Reimplemented in hpp::manipulation::AxialHandle.
static HandlePtr_t hpp::manipulation::Handle::create (const std::string & name, const Transform3f & localPosition, const JointPtr_t & joint) inline static
Create constraint corresponding to a gripper grasping this object.
Parameters
robot the robot that grasps the handle,
grasp object containing the grasp information
Returns
the constraint of relative position between the handle and the gripper.
References Handle(), and init().
virtual NumericalConstraintPtr_t hpp::manipulation::Handle::createGrasp (const GripperPtr_t & gripper) const virtual
Create constraint corresponding to a gripper grasping this object.
Parameters
gripper object containing the gripper information
Returns
the constraint of relative transformation between the handle and the gripper.
Note
The 6 DOFs of the relative transformation are constrained.
Reimplemented in hpp::manipulation::AxialHandle.
static NumericalConstraintPtr_t hpp::manipulation::Handle::createGrasp (const GripperPtr_t & gripper, const HandlePtr_t & handle) inline static
virtual NumericalConstraintPtr_t hpp::manipulation::Handle::createGraspComplement (const GripperPtr_t & gripper) const virtual
Create constraint that acts on the non-constrained axis of the constraint generated by Handle::createGrasp.
Parameters
gripper object containing the gripper information
Returns
a constraints that is not doing anything.
Reimplemented in hpp::manipulation::AxialHandle.
virtual NumericalConstraintPtr_t hpp::manipulation::Handle::createPreGrasp (const GripperPtr_t & gripper, const value_type & shift) const virtual
Create constraint corresponding to a pregrasping task.
Parameters
gripper object containing the gripper information
Returns
the constraint of relative transformation between the handle and the gripper.
Note
6 DOFs of the relative transformation between the handle and the gripper are constrained. The transformation is shifted along x-axis of value shift.
void hpp::manipulation::Handle::init (HandleWkPtr_t weakPtr) inline protected
Referenced by create(), and hpp::manipulation::AxialHandle::init().
const JointPtr_t& hpp::manipulation::Handle::joint () const inline
Get joint to which the handle is linked.
Referenced by joint().
void hpp::manipulation::Handle::joint (const JointPtr_t & joint) inline
Set joint to which the handle is linked.
References joint().
const Transform3f& hpp::manipulation::Handle::localPosition () const inline
Get local position in joint frame.
const std::string& hpp::manipulation::Handle::name () const inline
Get name.
void hpp::manipulation::Handle::name (const std::string & n) inline
Set name.
virtual std::ostream& hpp::manipulation::Handle::print (std::ostream & os) const protected virtual
Reimplemented in hpp::manipulation::AxialHandle.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const Handle &) friend