fcl::Halfspace Class Reference
fcl::Halfspace Class Reference
Half Space: this is equivalent to the Plane in ODE.
#include <hpp/fcl/shape/geometric_shapes.h>
Public Member Functions
Halfspace (const Vec3f &n_, FCL_REAL d_)
Construct a half space with normal direction and offset.
Halfspace (FCL_REAL a, FCL_REAL b, FCL_REAL c, FCL_REAL d_)
Construct a plane with normal direction and offset.
Halfspace ()
FCL_REAL signedDistance (const Vec3f &p) const
FCL_REAL distance (const Vec3f &p) const
void computeLocalAABB ()
Compute AABB.
NODE_TYPE getNodeType () const
Get node type: a half space.
Public Member Functions inherited from fcl::ShapeBase
ShapeBase ()
OBJECT_TYPE getObjectType () const
Get object type: a geometric shape.
Public Member Functions inherited from fcl::CollisionGeometry
CollisionGeometry ()
virtual ~CollisionGeometry ()
void * getUserData () const
get user data in geometry
void setUserData (void *data)
set user data in geometry
bool isOccupied () const
whether the object is completely occupied
bool isFree () const
whether the object is completely free
bool isUncertain () const
whether the object has some uncertainty
virtual Vec3f computeCOM () const
compute center of mass
virtual Matrix3f computeMomentofInertia () const
compute the inertia matrix, related to the origin
virtual FCL_REAL computeVolume () const
compute the volume
virtual Matrix3f computeMomentofInertiaRelatedToCOM () const
compute the inertia matrix, related to the com
Public Attributes
Vec3f n
Plane normal.
FCL_REAL d
Plane offset.
Public Attributes inherited from fcl::CollisionGeometry
Vec3f aabb_center
AABB center in local coordinate.
FCL_REAL aabb_radius
AABB radius.
AABB aabb_local
AABB in local coordinate, used for tight AABB when only translation transform.
void * user_data
pointer to user defined data specific to this object
FCL_REAL cost_density
collision cost for unit volume
FCL_REAL threshold_occupied
threshold for occupied (>= is occupied)
FCL_REAL threshold_free
threshold for free (<= is free)
Protected Member Functions
void unitNormalTest ()
Turn non-unit normal into unit.
Detailed Description
Half Space: this is equivalent to the Plane in ODE.
The separation plane is defined as n * x = d; Points in the negative side of the separation plane (i.e. {x | n * x < d}) are inside the half space and points in the positive side of the separation plane (i.e. {x | n * x > d}) are outside the half space
Constructor & Destructor Documentation
fcl::Halfspace::Halfspace (const Vec3f & n_, FCL_REAL d_) inline
Construct a half space with normal direction and offset.
References unitNormalTest().
fcl::Halfspace::Halfspace (FCL_REAL a, FCL_REAL b, FCL_REAL c, FCL_REAL d_) inline
Construct a plane with normal direction and offset.
References unitNormalTest().
fcl::Halfspace::Halfspace () inline
Member Function Documentation
void fcl::Halfspace::computeLocalAABB () virtual
Compute AABB.
Implements fcl::CollisionGeometry.
FCL_REAL fcl::Halfspace::distance (const Vec3f & p) const inline
References fcl::details::abs(), d, and n.
NODE_TYPE fcl::Halfspace::getNodeType () const inline virtual
Get node type: a half space.
Reimplemented from fcl::CollisionGeometry.
References fcl::GEOM_HALFSPACE.
FCL_REAL fcl::Halfspace::signedDistance (const Vec3f & p) const inline
References d, and n.
void fcl::Halfspace::unitNormalTest () protected
Turn non-unit normal into unit.
Referenced by Halfspace().
Member Data Documentation
FCL_REAL fcl::Halfspace::d
Plane offset.
Referenced by distance(), and signedDistance().
Vec3f fcl::Halfspace::n
Plane normal.
Referenced by distance(), and signedDistance().