fcl::details::eigen_v3< T > Struct Template Reference
fcl::details::eigen_v3< T > Struct Template Reference
#include <hpp/fcl/eigen/math_details.h>
Public Types
typedef T meta_type
typedef Eigen::Matrix< T, 3, 1 > Base
Public Member Functions
eigen_v3 (void)
template<typename OtherDerived >
eigen_v3 (const Eigen::MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
eigen_v3 & operator= (const Eigen::MatrixBase< OtherDerived > &other)
eigen_v3 (T x)
eigen_v3 (T *x)
eigen_v3 (T x, T y, T z)
void setValue (T x, T y, T z)
void setValue (T x)
void negate ()
template<typename OtherDerived >
eigen_v3< T > & ubound (const Eigen::MatrixBase< OtherDerived > &u)
template<typename OtherDerived >
eigen_v3< T > & lbound (const Eigen::MatrixBase< OtherDerived > &l)
eigen_v3< T > & operator+= (const eigen_v3< T > &other)
eigen_v3< T > & operator-= (const eigen_v3< T > &other)
eigen_v3< T > & operator*= (const eigen_v3< T > &other)
eigen_v3< T > & operator/= (const eigen_v3< T > &other)
eigen_v3< T > & operator+= (T t)
eigen_v3< T > & operator-= (T t)
eigen_v3< T > & operator*= (T t)
eigen_v3< T > & operator/= (T t)
Member Typedef Documentation
template<typename T> typedef Eigen::Matrix<T, 3, 1> fcl::details::eigen_v3< T >::Base
template<typename T> typedef T fcl::details::eigen_v3< T >::meta_type
Constructor & Destructor Documentation
template<typename T> fcl::details::eigen_v3< T >::eigen_v3 (void) inline
template<typename T> template<typename OtherDerived > fcl::details::eigen_v3< T >::eigen_v3 (const Eigen::MatrixBase< OtherDerived > & other) inline
template<typename T> fcl::details::eigen_v3< T >::eigen_v3 (T x) inline
template<typename T> fcl::details::eigen_v3< T >::eigen_v3 (T * x) inline
template<typename T> fcl::details::eigen_v3< T >::eigen_v3 (T x, T y, T z) inline
Member Function Documentation
template<typename T> template<typename OtherDerived > eigen_v3<T>& fcl::details::eigen_v3< T >::lbound (const Eigen::MatrixBase< OtherDerived > & l) inline
template<typename T> void fcl::details::eigen_v3< T >::negate () inline
References fcl::details::eigen_v3< T >::operator*=().
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator*= (const eigen_v3< T > & other) inline
Referenced by fcl::details::eigen_v3< T >::negate().
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator*= (T t) inline
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator+= (const eigen_v3< T > & other) inline
References operator+=().
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator+= (T t) inline
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator-= (const eigen_v3< T > & other) inline
References operator-=().
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator-= (T t) inline
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator/= (const eigen_v3< T > & other) inline
template<typename T> eigen_v3<T>& fcl::details::eigen_v3< T >::operator/= (T t) inline
template<typename T> template<typename OtherDerived > eigen_v3& fcl::details::eigen_v3< T >::operator= (const Eigen::MatrixBase< OtherDerived > & other) inline
References operator=().
template<typename T> void fcl::details::eigen_v3< T >::setValue (T x, T y, T z) inline
References operator[]().
template<typename T> void fcl::details::eigen_v3< T >::setValue (T x) inline
template<typename T> template<typename OtherDerived > eigen_v3<T>& fcl::details::eigen_v3< T >::ubound (const Eigen::MatrixBase< OtherDerived > & u) inline