fcl::FclType< Derived > Class Template Reference
fcl::FclType< Derived > Class Template Reference
#include <hpp/fcl/eigen/vec_3fx.h>
Public Member Functions
Derived & fcl ()
const Derived & fcl () const
Member Function Documentation
template<typename Derived> Derived& fcl::FclType< Derived >::fcl () inline
Referenced by fcl::abs(), fcl::eigen(), fcl::generateCoordinateSystem(), fcl::max(), fcl::min(), fcl::operator*(), operator=(), fcl::transpose(), and fcl::triple().
template<typename Derived> const Derived& fcl::FclType< Derived >::fcl () const inline