fcl::details::eigen_m3< T > Struct Template Reference
fcl::details::eigen_m3< T > Struct Template Reference
#include <hpp/fcl/eigen/math_details.h>
Public Types
typedef T meta_type
typedef eigen_v3< T > vector_type
typedef Eigen::Matrix< T, 3, 3 > Base
typedef Base::ColXpr ColXpr
typedef Base::ConstColXpr ConstColXpr
typedef Base::RowXpr RowXpr
typedef Base::ConstRowXpr ConstRowXpr
Public Member Functions
eigen_m3 (void)
template<typename OtherDerived >
eigen_m3 (const Eigen::MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
eigen_m3 & operator= (const Eigen::MatrixBase< OtherDerived > &other)
eigen_m3 (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz)
eigen_m3 (const vector_type &v1, const vector_type &v2, const vector_type &v3)
ColXpr getColumn (size_t i)
RowXpr getRow (size_t i)
ConstColXpr getColumn (size_t i) const
ConstRowXpr getRow (size_t i) const
eigen_m3< T > & operator*= (const eigen_m3< T > &other)
eigen_m3< T > & operator+= (const eigen_m3< T > &other)
eigen_m3< T > & operator-= (const eigen_m3< T > &other)
eigen_m3< T > & operator+= (T c)
eigen_m3< T > & operator-= (T c)
eigen_m3< T > & operator*= (T c)
eigen_m3< T > & operator/= (T c)
eigen_m3< T > & transpose ()
eigen_m3< T > & inverse ()
template<typename OtherDerived >
const Eigen::ProductReturnType< eigen_m3< T >, OtherDerived >::Type transposeTimes (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Eigen::ProductReturnType< eigen_m3< T >, OtherDerived >::Type timesTranspose (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T transposeDotX (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T transposeDotY (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T transposeDotZ (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T transposeDot (size_t i, const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T dotX (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T dotY (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T dotZ (const Eigen::MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
T dot (size_t i, const Eigen::MatrixBase< OtherDerived > &other) const
void setValue (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz)
void setValue (T x)
Static Public Member Functions
static const eigen_m3< T > & getIdentity ()
Member Typedef Documentation
template<typename T> typedef Eigen::Matrix<T, 3, 3> fcl::details::eigen_m3< T >::Base
template<typename T> typedef Base::ColXpr fcl::details::eigen_m3< T >::ColXpr
template<typename T> typedef Base::ConstColXpr fcl::details::eigen_m3< T >::ConstColXpr
template<typename T> typedef Base::ConstRowXpr fcl::details::eigen_m3< T >::ConstRowXpr
template<typename T> typedef T fcl::details::eigen_m3< T >::meta_type
template<typename T> typedef Base::RowXpr fcl::details::eigen_m3< T >::RowXpr
template<typename T> typedef eigen_v3<T> fcl::details::eigen_m3< T >::vector_type
Constructor & Destructor Documentation
template<typename T> fcl::details::eigen_m3< T >::eigen_m3 (void) inline
template<typename T> template<typename OtherDerived > fcl::details::eigen_m3< T >::eigen_m3 (const Eigen::MatrixBase< OtherDerived > & other) inline
template<typename T> fcl::details::eigen_m3< T >::eigen_m3 (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz) inline
References fcl::details::eigen_m3< T >::setValue().
template<typename T> fcl::details::eigen_m3< T >::eigen_m3 (const vector_type & v1, const vector_type & v2, const vector_type & v3) inline
Member Function Documentation
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::dot (size_t i, const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::dotX (const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::dotY (const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::dotZ (const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> ColXpr fcl::details::eigen_m3< T >::getColumn (size_t i) inline
template<typename T> ConstColXpr fcl::details::eigen_m3< T >::getColumn (size_t i) const inline
template<typename T> static const eigen_m3<T>& fcl::details::eigen_m3< T >::getIdentity () inline static
template<typename T> RowXpr fcl::details::eigen_m3< T >::getRow (size_t i) inline
template<typename T> ConstRowXpr fcl::details::eigen_m3< T >::getRow (size_t i) const inline
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::inverse () inline
References operator=().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::operator*= (const eigen_m3< T > & other) inline
References fcl::details::eigen_m3< T >::operator*=().
Referenced by fcl::details::eigen_m3< T >::operator*=().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::operator*= (T c) inline
References fcl::details::eigen_m3< T >::operator*=().
Referenced by fcl::details::eigen_m3< T >::operator*=().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::operator+= (const eigen_m3< T > & other) inline
References fcl::details::eigen_m3< T >::operator+=().
Referenced by fcl::details::eigen_m3< T >::operator+=().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::operator+= (T c) inline
References fcl::details::eigen_m3< T >::operator+=().
Referenced by fcl::details::eigen_m3< T >::operator+=().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::operator-= (const eigen_m3< T > & other) inline
References fcl::details::eigen_m3< T >::operator-=().
Referenced by fcl::details::eigen_m3< T >::operator-=().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::operator-= (T c) inline
References fcl::details::eigen_m3< T >::operator-=().
Referenced by fcl::details::eigen_m3< T >::operator-=().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::operator/= (T c) inline
References fcl::details::eigen_m3< T >::operator/=().
Referenced by fcl::details::eigen_m3< T >::operator/=().
template<typename T> template<typename OtherDerived > eigen_m3& fcl::details::eigen_m3< T >::operator= (const Eigen::MatrixBase< OtherDerived > & other) inline
References operator=().
template<typename T> void fcl::details::eigen_m3< T >::setValue (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz) inline
Referenced by fcl::details::eigen_m3< T >::eigen_m3().
template<typename T> void fcl::details::eigen_m3< T >::setValue (T x) inline
template<typename T> template<typename OtherDerived > const Eigen::ProductReturnType<eigen_m3<T>, OtherDerived>::Type fcl::details::eigen_m3< T >::timesTranspose (const Eigen::MatrixBase< OtherDerived > & other) const inline
References fcl::operator*().
template<typename T> eigen_m3<T>& fcl::details::eigen_m3< T >::transpose () inline
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::transposeDot (size_t i, const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::transposeDotX (const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::transposeDotY (const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> template<typename OtherDerived > T fcl::details::eigen_m3< T >::transposeDotZ (const Eigen::MatrixBase< OtherDerived > & other) const inline
template<typename T> template<typename OtherDerived > const Eigen::ProductReturnType<eigen_m3<T>, OtherDerived>::Type fcl::details::eigen_m3< T >::transposeTimes (const Eigen::MatrixBase< OtherDerived > & other) const inline
References fcl::details::transpose().