fcl::BVNodeBase Struct Reference
fcl::BVNodeBase Struct Reference
BVNodeBase encodes the tree structure for BVH.
#include <hpp/fcl/BV/BV_node.h>
Public Member Functions
bool isLeaf () const
Whether current node is a leaf node (i.e. contains a primitive index.
int primitiveId () const
Return the primitive index. The index is referred to the original data (i.e. vertices or tri_indices) in BVHModel.
int leftChild () const
Return the index of the first child. The index is referred to the bounding volume array (i.e. bvs) in BVHModel.
int rightChild () const
Return the index of the second child. The index is referred to the bounding volume array (i.e. bvs) in BVHModel.
Public Attributes
int first_child
An index for first child node or primitive If the value is positive, it is the index of the first child bv node If the value is negative, it is -(primitive index + 1) Zero is not used.
int first_primitive
The start id the primitive belonging to the current node.
int num_primitives
The number of primitives belonging to the current node.
Detailed Description
BVNodeBase encodes the tree structure for BVH.
Member Function Documentation
bool fcl::BVNodeBase::isLeaf () const inline
Whether current node is a leaf node (i.e. contains a primitive index.
int fcl::BVNodeBase::leftChild () const inline
Return the index of the first child. The index is referred to the bounding volume array (i.e. bvs) in BVHModel.
References first_child.
int fcl::BVNodeBase::primitiveId () const inline
Return the primitive index. The index is referred to the original data (i.e. vertices or tri_indices) in BVHModel.
Referenced by fcl::MeshCollisionTraversalNode< OBBRSS >::leafTesting(), fcl::MeshShapeCollisionTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), fcl::MeshContinuousCollisionTraversalNode< BV >::leafTesting(), fcl::ShapeMeshCollisionTraversalNode< S, kIOS, NarrowPhaseSolver >::leafTesting(), fcl::MeshDistanceTraversalNode< OBBRSS >::leafTesting(), fcl::MeshConservativeAdvancementTraversalNode< OBBRSS >::leafTesting(), fcl::MeshShapeDistanceTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), fcl::ShapeMeshDistanceTraversalNode< S, kIOS, NarrowPhaseSolver >::leafTesting(), fcl::MeshShapeConservativeAdvancementTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), fcl::ShapeMeshConservativeAdvancementTraversalNode< S, OBBRSS, NarrowPhaseSolver >::leafTesting(), and fcl::details::meshShapeConservativeAdvancementOrientedNodeLeafTesting().
int fcl::BVNodeBase::rightChild () const inline
Return the index of the second child. The index is referred to the bounding volume array (i.e. bvs) in BVHModel.
Member Data Documentation
int fcl::BVNodeBase::first_child
An index for first child node or primitive If the value is positive, it is the index of the first child bv node If the value is negative, it is -(primitive index + 1) Zero is not used.
Referenced by leftChild().
int fcl::BVNodeBase::first_primitive
The start id the primitive belonging to the current node.
The index is referred to the primitive_indices in BVHModel and from that we can obtain the primitive's index in original data indirectly.
Referenced by fcl::BVHExpand().
int fcl::BVNodeBase::num_primitives
The number of primitives belonging to the current node.
Referenced by fcl::BVHExpand().