fcl::CollisionResult Struct Reference
fcl::CollisionResult Struct Reference
collision result
#include <hpp/fcl/collision_data.h>
Public Member Functions
CollisionResult ()
void addContact (const Contact &c)
add one contact into result structure
void addCostSource (const CostSource &c, std::size_t num_max_cost_sources)
add one cost source into result structure
bool operator== (const CollisionResult &other) const
whether two CollisionResult are the same or not
bool isCollision () const
return binary collision result
size_t numContacts () const
number of contacts found
size_t numCostSources () const
number of cost sources found
const Contact & getContact (size_t i) const
get the i-th contact calculated
void getContacts (std::vector< Contact > &contacts_)
get all the contacts
void getCostSources (std::vector< CostSource > &cost_sources_)
get all the cost sources
void clear ()
clear the results obtained
Public Attributes
Vec3f cached_gjk_guess
FCL_REAL distance_lower_bound
Lower bound on distance between objects if they are disjoint.
Friends
void invertResults (CollisionResult &result)
reposition Contact objects when fcl inverts them during their construction.
Detailed Description
collision result
Constructor & Destructor Documentation
fcl::CollisionResult::CollisionResult () inline
Member Function Documentation
void fcl::CollisionResult::addContact (const Contact & c) inline
add one contact into result structure
Referenced by fcl::ShapeCollisionTraversalNode< S1, S2, NarrowPhaseSolver >::leafTesting(), fcl::MeshCollisionTraversalNode< OBBRSS >::leafTesting(), fcl::MeshShapeCollisionTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), and fcl::ShapeMeshCollisionTraversalNode< S, kIOS, NarrowPhaseSolver >::leafTesting().
void fcl::CollisionResult::addCostSource (const CostSource & c, std::size_t num_max_cost_sources) inline
add one cost source into result structure
Referenced by fcl::ShapeCollisionTraversalNode< S1, S2, NarrowPhaseSolver >::leafTesting(), fcl::MeshCollisionTraversalNode< OBBRSS >::leafTesting(), fcl::MeshShapeCollisionTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), and fcl::ShapeMeshCollisionTraversalNode< S, kIOS, NarrowPhaseSolver >::leafTesting().
void fcl::CollisionResult::clear () inline
clear the results obtained
const Contact& fcl::CollisionResult::getContact (size_t i) const inline
get the i-th contact calculated
void fcl::CollisionResult::getContacts (std::vector< Contact > & contacts_) inline
get all the contacts
void fcl::CollisionResult::getCostSources (std::vector< CostSource > & cost_sources_) inline
get all the cost sources
bool fcl::CollisionResult::isCollision () const inline
return binary collision result
size_t fcl::CollisionResult::numContacts () const inline
number of contacts found
Referenced by fcl::ShapeCollisionTraversalNode< S1, S2, NarrowPhaseSolver >::leafTesting(), and fcl::MeshCollisionTraversalNode< OBBRSS >::leafTesting().
size_t fcl::CollisionResult::numCostSources () const inline
number of cost sources found
bool fcl::CollisionResult::operator== (const CollisionResult & other) const inline
whether two CollisionResult are the same or not
References distance_lower_bound.
Friends And Related Function Documentation
void invertResults (CollisionResult & result) friend
reposition Contact objects when fcl inverts them during their construction.
Member Data Documentation
Vec3f fcl::CollisionResult::cached_gjk_guess
FCL_REAL fcl::CollisionResult::distance_lower_bound
Lower bound on distance between objects if they are disjoint.
Note
computed only on request.
Referenced by operator==().