fcl::BroadPhaseContinuousCollisionManager Class Reference
fcl::BroadPhaseContinuousCollisionManager Class Reference abstract
Base class for broad phase continuous collision. It helps to accelerate the continuous collision/distance between N objects. Also support self collision, self distance and collision/distance with another M objects.
#include <hpp/fcl/broadphase/broadphase.h>
Public Member Functions
BroadPhaseContinuousCollisionManager ()
virtual ~BroadPhaseContinuousCollisionManager ()
virtual void registerObjects (const std::vector< ContinuousCollisionObject * > &other_objs)
add objects to the manager
virtual void registerObject (ContinuousCollisionObject *obj)=0
add one object to the manager
virtual void unregisterObject (ContinuousCollisionObject *obj)=0
remove one object from the manager
virtual void setup ()=0
initialize the manager, related with the specific type of manager
virtual void update ()=0
update the condition of manager
virtual void update (ContinuousCollisionObject *)
update the manager by explicitly given the object updated
virtual void update (const std::vector< ContinuousCollisionObject * > &)
update the manager by explicitly given the set of objects update
virtual void clear ()=0
clear the manager
virtual void getObjects (std::vector< ContinuousCollisionObject * > &objs) const =0
return the objects managed by the manager
virtual void collide (ContinuousCollisionObject *obj, void *cdata, CollisionCallBack callback) const =0
perform collision test between one object and all the objects belonging to the manager
virtual void distance (ContinuousCollisionObject *obj, void *cdata, DistanceCallBack callback) const =0
perform distance computation between one object and all the objects belonging to the manager
virtual void collide (void *cdata, CollisionCallBack callback) const =0
perform collision test for the objects belonging to the manager (i.e., N^2 self collision)
virtual void distance (void *cdata, DistanceCallBack callback) const =0
perform distance test for the objects belonging to the manager (i.e., N^2 self distance)
virtual void collide (BroadPhaseContinuousCollisionManager *other_manager, void *cdata, CollisionCallBack callback) const =0
perform collision test with objects belonging to another manager
virtual void distance (BroadPhaseContinuousCollisionManager *other_manager, void *cdata, DistanceCallBack callback) const =0
perform distance test with objects belonging to another manager
virtual bool empty () const =0
whether the manager is empty
virtual size_t size () const =0
the number of objects managed by the manager
Detailed Description
Base class for broad phase continuous collision. It helps to accelerate the continuous collision/distance between N objects. Also support self collision, self distance and collision/distance with another M objects.
Constructor & Destructor Documentation
fcl::BroadPhaseContinuousCollisionManager::BroadPhaseContinuousCollisionManager () inline
virtual fcl::BroadPhaseContinuousCollisionManager::~BroadPhaseContinuousCollisionManager () inline virtual
Member Function Documentation
virtual void fcl::BroadPhaseContinuousCollisionManager::clear () pure virtual
clear the manager
virtual void fcl::BroadPhaseContinuousCollisionManager::collide (ContinuousCollisionObject * obj, void * cdata, CollisionCallBack callback) const pure virtual
perform collision test between one object and all the objects belonging to the manager
virtual void fcl::BroadPhaseContinuousCollisionManager::collide (void * cdata, CollisionCallBack callback) const pure virtual
perform collision test for the objects belonging to the manager (i.e., N^2 self collision)
virtual void fcl::BroadPhaseContinuousCollisionManager::collide (BroadPhaseContinuousCollisionManager * other_manager, void * cdata, CollisionCallBack callback) const pure virtual
perform collision test with objects belonging to another manager
virtual void fcl::BroadPhaseContinuousCollisionManager::distance (ContinuousCollisionObject * obj, void * cdata, DistanceCallBack callback) const pure virtual
perform distance computation between one object and all the objects belonging to the manager
virtual void fcl::BroadPhaseContinuousCollisionManager::distance (void * cdata, DistanceCallBack callback) const pure virtual
perform distance test for the objects belonging to the manager (i.e., N^2 self distance)
virtual void fcl::BroadPhaseContinuousCollisionManager::distance (BroadPhaseContinuousCollisionManager * other_manager, void * cdata, DistanceCallBack callback) const pure virtual
perform distance test with objects belonging to another manager
virtual bool fcl::BroadPhaseContinuousCollisionManager::empty () const pure virtual
whether the manager is empty
virtual void fcl::BroadPhaseContinuousCollisionManager::getObjects (std::vector< ContinuousCollisionObject * > & objs) const pure virtual
return the objects managed by the manager
virtual void fcl::BroadPhaseContinuousCollisionManager::registerObject (ContinuousCollisionObject * obj) pure virtual
add one object to the manager
Referenced by registerObjects().
virtual void fcl::BroadPhaseContinuousCollisionManager::registerObjects (const std::vector< ContinuousCollisionObject * > & other_objs) inline virtual
add objects to the manager
References registerObject().
virtual void fcl::BroadPhaseContinuousCollisionManager::setup () pure virtual
initialize the manager, related with the specific type of manager
virtual size_t fcl::BroadPhaseContinuousCollisionManager::size () const pure virtual
the number of objects managed by the manager
virtual void fcl::BroadPhaseContinuousCollisionManager::unregisterObject (ContinuousCollisionObject * obj) pure virtual
remove one object from the manager
virtual void fcl::BroadPhaseContinuousCollisionManager::update () pure virtual
update the condition of manager
Referenced by update().
virtual void fcl::BroadPhaseContinuousCollisionManager::update (ContinuousCollisionObject *) inline virtual
update the manager by explicitly given the object updated
References update().
virtual void fcl::BroadPhaseContinuousCollisionManager::update (const std::vector< ContinuousCollisionObject * > &) inline virtual
update the manager by explicitly given the set of objects update
References update().