Eigen::FclMatrix< T, Cols, _Options > Class Template Reference
Eigen::FclMatrix< T, Cols, _Options > Class Template Reference
Vector3 class wrapper. The core data is in the template parameter class.
#include <hpp/fcl/eigen/vec_3fx.h>
Public Types
typedef Matrix< T, 3, Cols, _Options > Base
typedef T U
typedef T meta_type
Public Member Functions
FclMatrix (void)
template<typename OtherDerived >
FclMatrix (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
FclMatrix & operator= (const MatrixBase< OtherDerived > &other)
FclMatrix (T x, T y, T z)
create Vector (x, y, z)
FclMatrix (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz)
template<typename Vector >
FclMatrix (const ::fcl::FclType< Vector > &r0, const ::fcl::FclType< Vector > &r1, const ::fcl::FclType< Vector > &r2)
FclMatrix (T x)
create vector (x, x, x)
EIGEN_STRONG_INLINE const FclOp< const CwiseUnaryOp< internal::scalar_add_op< Scalar >, const Base > > operator- (const Scalar &scalar) const
create vector using the internal data type
const UnaryReturnType< Base >::Opposite operator- () const
FclMatrix & normalize ()
FclMatrix & normalize (bool *signal)
FclMatrix & abs ()
T length () const
T sqrLength () const
void setValue (T x, T y, T z)
void setValue (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz)
void setValue (T x)
bool equal (const FclMatrix &other, T epsilon=std::numeric_limits< T >::epsilon()*100) const
FclMatrix & negate ()
bool operator== (const FclMatrix &other) const
bool operator!= (const FclMatrix &other) const
FclMatrix & ubound (const FclMatrix &u)
FclMatrix & lbound (const FclMatrix &l)
bool isZero () const
FclMatrix & transpose ()
FclMatrix & inverse ()
template<typename OtherDerived >
EIGEN_STRONG_INLINE const FclProduct< const Base, const OtherDerived >::TransposeTimesType transposeTimes (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE const FclProduct< const Base, const OtherDerived >::TimesTransposeType timesTranspose (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE const FclProduct< const Base, const OtherDerived >::TensorTransformType tensorTransform (const MatrixBase< OtherDerived > &other) const
void setEulerZYX (Scalar eulerX, Scalar eulerY, Scalar eulerZ)
Set the matrix from euler angles YPR around ZYX axes.
void setEulerYPR (Scalar yaw, Scalar pitch, Scalar roll)
Set the matrix from euler angles using YPR around YXZ respectively.
Public Member Functions inherited from fcl::FclType< FclMatrix< T, Cols, _Options > >
FclMatrix< T, Cols, _Options > & fcl ()
const FclMatrix< T, Cols, _Options > & fcl () const
Static Public Member Functions
static const FclMatrix & getIdentity ()
Detailed Description
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options>
class Eigen::FclMatrix< T, Cols, _Options >
Vector3 class wrapper. The core data is in the template parameter class.
Member Typedef Documentation
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> typedef Matrix<T, 3, Cols, _Options> Eigen::FclMatrix< T, Cols, _Options >::Base
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> typedef T Eigen::FclMatrix< T, Cols, _Options >::meta_type
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> typedef T Eigen::FclMatrix< T, Cols, _Options >::U
Constructor & Destructor Documentation
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> Eigen::FclMatrix< T, Cols, _Options >::FclMatrix (void) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> template<typename OtherDerived > Eigen::FclMatrix< T, Cols, _Options >::FclMatrix (const MatrixBase< OtherDerived > & other) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> Eigen::FclMatrix< T, Cols, _Options >::FclMatrix (T x, T y, T z) inline
create Vector (x, y, z)
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> Eigen::FclMatrix< T, Cols, _Options >::FclMatrix (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> template<typename Vector > Eigen::FclMatrix< T, Cols, _Options >::FclMatrix (const ::fcl::FclType< Vector > & r0, const ::fcl::FclType< Vector > & r1, const ::fcl::FclType< Vector > & r2) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> Eigen::FclMatrix< T, Cols, _Options >::FclMatrix (T x) inline
create vector (x, x, x)
Member Function Documentation
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::abs () inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> bool Eigen::FclMatrix< T, Cols, _Options >::equal (const FclMatrix< T, Cols, _Options > & other, T epsilon = std::numeric_limits<T>::epsilon() * 100) const inline
Referenced by fcl::AABB::equal(), and Eigen::FclMatrix< FCL_REAL, 3 >::operator==().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> static const FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::getIdentity () inline static
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::inverse () inline
Referenced by fcl::inverse().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> bool Eigen::FclMatrix< T, Cols, _Options >::isZero () const inline
Referenced by fcl::Transform3f::isIdentity().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::lbound (const FclMatrix< T, Cols, _Options > & l) inline
Referenced by fcl::AABB::operator+=().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> T Eigen::FclMatrix< T, Cols, _Options >::length () const inline
Referenced by fcl::ScrewMotion::computeScrewParameter(), and fcl::SplineMotion::getTaylorModel().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::negate () inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::normalize () inline
Referenced by fcl::MeshConservativeAdvancementTraversalNode< OBBRSS >::canStop(), fcl::MeshShapeConservativeAdvancementTraversalNode< OBBRSS, S, NarrowPhaseSolver >::canStop(), fcl::ShapeMeshConservativeAdvancementTraversalNode< S, OBBRSS, NarrowPhaseSolver >::canStop(), fcl::ShapeConservativeAdvancementTraversalNode< S1, S2, NarrowPhaseSolver >::leafTesting(), fcl::MeshConservativeAdvancementTraversalNode< OBBRSS >::leafTesting(), fcl::MeshShapeConservativeAdvancementTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), fcl::ShapeMeshConservativeAdvancementTraversalNode< S, OBBRSS, NarrowPhaseSolver >::leafTesting(), fcl::details::meshConservativeAdvancementTraversalNodeCanStop(), fcl::details::meshShapeConservativeAdvancementOrientedNodeCanStop(), and fcl::details::meshShapeConservativeAdvancementOrientedNodeLeafTesting().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::normalize (bool * signal) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> bool Eigen::FclMatrix< T, Cols, _Options >::operator!= (const FclMatrix< T, Cols, _Options > & other) const inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> EIGEN_STRONG_INLINE const FclOp<const CwiseUnaryOp<internal::scalar_add_op<Scalar>, const Base> > Eigen::FclMatrix< T, Cols, _Options >::operator- (const Scalar & scalar) const inline
create vector using the internal data type
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> const UnaryReturnType<Base>::Opposite Eigen::FclMatrix< T, Cols, _Options >::operator- () const inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> template<typename OtherDerived > FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::operator= (const MatrixBase< OtherDerived > & other) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> bool Eigen::FclMatrix< T, Cols, _Options >::operator== (const FclMatrix< T, Cols, _Options > & other) const inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> void Eigen::FclMatrix< T, Cols, _Options >::setEulerYPR (Scalar yaw, Scalar pitch, Scalar roll) inline
Set the matrix from euler angles using YPR around YXZ respectively.
Parameters
yaw Yaw about Y axis
pitch Pitch about X axis
roll Roll about Z axis
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> void Eigen::FclMatrix< T, Cols, _Options >::setEulerZYX (Scalar eulerX, Scalar eulerY, Scalar eulerZ) inline
Set the matrix from euler angles YPR around ZYX axes.
Parameters
eulerX Roll about X axis
eulerY Pitch around Y axis
eulerZ Yaw aboud Z axis
These angles are used to produce a rotation matrix. The euler angles are applied in ZYX order. I.e a vector is first rotated about X then Y and then Z
Referenced by Eigen::FclMatrix< FCL_REAL, 3 >::setEulerYPR().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> void Eigen::FclMatrix< T, Cols, _Options >::setValue (T x, T y, T z) inline
Referenced by Eigen::FclMatrix< FCL_REAL, 3 >::FclMatrix(), fcl::ScrewMotion::ScrewMotion(), Eigen::FclMatrix< FCL_REAL, 3 >::setEulerZYX(), and fcl::Transform3f::setIdentity().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> void Eigen::FclMatrix< T, Cols, _Options >::setValue (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> void Eigen::FclMatrix< T, Cols, _Options >::setValue (T x) inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> T Eigen::FclMatrix< T, Cols, _Options >::sqrLength () const inline
Referenced by fcl::SplineMotion::getTaylorModel(), and fcl::OBB::size().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> template<typename OtherDerived > EIGEN_STRONG_INLINE const FclProduct<const Base,const OtherDerived>::TensorTransformType Eigen::FclMatrix< T, Cols, _Options >::tensorTransform (const MatrixBase< OtherDerived > & other) const inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> template<typename OtherDerived > EIGEN_STRONG_INLINE const FclProduct<const Base,const OtherDerived>::TimesTransposeType Eigen::FclMatrix< T, Cols, _Options >::timesTranspose (const MatrixBase< OtherDerived > & other) const inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::transpose () inline
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> template<typename OtherDerived > EIGEN_STRONG_INLINE const FclProduct<const Base,const OtherDerived>::TransposeTimesType Eigen::FclMatrix< T, Cols, _Options >::transposeTimes (const MatrixBase< OtherDerived > & other) const inline
Referenced by fcl::GJKSolver_indep::shapeDistance(), fcl::GJKSolver_indep::shapeIntersect(), fcl::GJKSolver_indep::shapeTriangleDistance(), and fcl::GJKSolver_indep::shapeTriangleIntersect().
template<typename T, int Cols, int _Options = internal::traits<Matrix <T, 3, Cols> >::Options> FclMatrix& Eigen::FclMatrix< T, Cols, _Options >::ubound (const FclMatrix< T, Cols, _Options > & u) inline
Referenced by fcl::AABB::operator+=().