fcl::MeshShapeCollisionTraversalNodeRSS< S, NarrowPhaseSolver > Class Template Reference
fcl::MeshShapeCollisionTraversalNodeRSS< S, NarrowPhaseSolver > Class Template Reference
#include <hpp/fcl/traversal/traversal_node_bvh_shape.h>
Public Member Functions
MeshShapeCollisionTraversalNodeRSS (bool enable_distance_lower_bound=false)
bool BVTesting (int b1, int b2) const
BV test between b1 and b2.
void leafTesting (int b1, int b2, FCL_REAL &sqrDistLowerBound) const
Leaf test between node b1 and b2, if they are both leafs.
Public Member Functions inherited from fcl::MeshShapeCollisionTraversalNode< RSS, S, NarrowPhaseSolver >
MeshShapeCollisionTraversalNode (bool enable_distance_lower_bound=false)
void leafTesting (int b1, int b2) const
Intersection testing between leaves (one triangle and one shape)
bool canStop () const
Whether the traversal process can stop early.
Public Member Functions inherited from fcl::BVHShapeCollisionTraversalNode< RSS, S >
BVHShapeCollisionTraversalNode (bool enable_distance_lower_bound)
bool isFirstNodeLeaf (int b) const
Whether the BV node in the first BVH tree is leaf.
int getFirstLeftChild (int b) const
Obtain the left child of BV node in the first BVH.
int getFirstRightChild (int b) const
Obtain the right child of BV node in the first BVH.
bool BVTesting (int b1, int b2) const
BV culling test in one BVTT node.
bool BVTesting (int b1, int b2, FCL_REAL &sqrDistLowerBound) const
BV test between b1 and b2.
Public Member Functions inherited from fcl::CollisionTraversalNodeBase
CollisionTraversalNodeBase (bool enable_distance_lower_bound_=false)
virtual ~CollisionTraversalNodeBase ()
void enableStatistics (bool enable)
Whether store some statistics information during traversal.
Public Member Functions inherited from fcl::TraversalNodeBase
virtual ~TraversalNodeBase ()
virtual void preprocess ()
virtual void postprocess ()
virtual bool isSecondNodeLeaf (int b) const
Whether b is a leaf node in the second BVH tree.
virtual bool firstOverSecond (int b1, int b2) const
Traverse the subtree of the node in the first tree first.
virtual int getSecondLeftChild (int b) const
Get the left child of the node b in the second tree.
virtual int getSecondRightChild (int b) const
Get the right child of the node b in the second tree.
Additional Inherited Members
Public Attributes inherited from fcl::MeshShapeCollisionTraversalNode< RSS, S, NarrowPhaseSolver >
Vec3f * vertices
Triangle * tri_indices
FCL_REAL cost_density
const NarrowPhaseSolver * nsolver
Public Attributes inherited from fcl::BVHShapeCollisionTraversalNode< RSS, S >
const BVHModel< RSS > * model1
const S * model2
RSS model2_bv
int num_bv_tests
int num_leaf_tests
FCL_REAL query_time_seconds
Public Attributes inherited from fcl::CollisionTraversalNodeBase
CollisionRequest request
request setting for collision
CollisionResult * result
collision result kept during the traversal iteration
bool enable_statistics
Whether stores statistics.
bool enable_distance_lower_bound
Whether to compute a lower bound on distance between bounding volumes.
Public Attributes inherited from fcl::TraversalNodeBase
Transform3f tf1
configuation of first object
Transform3f tf2
configuration of second object
Constructor & Destructor Documentation
template<typename S, typename NarrowPhaseSolver> fcl::MeshShapeCollisionTraversalNodeRSS< S, NarrowPhaseSolver >::MeshShapeCollisionTraversalNodeRSS (bool enable_distance_lower_bound = false) inline
Member Function Documentation
template<typename S, typename NarrowPhaseSolver> bool fcl::MeshShapeCollisionTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting (int b1, int b2) const inline virtual
BV test between b1 and b2.
Implements fcl::CollisionTraversalNodeBase.
References fcl::BVNode< BV >::bv, fcl::CollisionTraversalNodeBase::enable_statistics, fcl::BVHModel< BV >::getBV(), fcl::Transform3f::getRotation(), fcl::Transform3f::getTranslation(), fcl::BVHShapeCollisionTraversalNode< RSS, S >::model1, fcl::BVHShapeCollisionTraversalNode< RSS, S >::model2_bv, fcl::BVHShapeCollisionTraversalNode< RSS, S >::num_bv_tests, fcl::overlap(), and fcl::TraversalNodeBase::tf1.
template<typename S, typename NarrowPhaseSolver> void fcl::MeshShapeCollisionTraversalNodeRSS< S, NarrowPhaseSolver >::leafTesting (int , int , FCL_REAL &) const inline virtual
Leaf test between node b1 and b2, if they are both leafs.
Reimplemented from fcl::CollisionTraversalNodeBase.
References fcl::MeshShapeCollisionTraversalNode< RSS, S, NarrowPhaseSolver >::cost_density, fcl::CollisionTraversalNodeBase::enable_statistics, fcl::BVHShapeCollisionTraversalNode< RSS, S >::model1, fcl::BVHShapeCollisionTraversalNode< RSS, S >::model2, fcl::MeshShapeCollisionTraversalNode< RSS, S, NarrowPhaseSolver >::nsolver, fcl::BVHShapeCollisionTraversalNode< RSS, S >::num_leaf_tests, fcl::CollisionTraversalNodeBase::request, fcl::CollisionTraversalNodeBase::result, fcl::TraversalNodeBase::tf1, fcl::TraversalNodeBase::tf2, fcl::MeshShapeCollisionTraversalNode< RSS, S, NarrowPhaseSolver >::tri_indices, and fcl::MeshShapeCollisionTraversalNode< RSS, S, NarrowPhaseSolver >::vertices.