fcl::SamplerSE3Euler_ball Class Reference
fcl::SamplerSE3Euler_ball Class Reference
#include <hpp/fcl/math/sampling.h>
Public Member Functions
SamplerSE3Euler_ball ()
SamplerSE3Euler_ball (FCL_REAL r_)
void setBound (const FCL_REAL &r_)
void getBound (FCL_REAL &r_) const
Vecnf< 6 > sample () const
Protected Attributes
FCL_REAL r
Additional Inherited Members
Public Attributes inherited from fcl::SamplerBase
RNG rng
Constructor & Destructor Documentation
fcl::SamplerSE3Euler_ball::SamplerSE3Euler_ball () inline
fcl::SamplerSE3Euler_ball::SamplerSE3Euler_ball (FCL_REAL r_) inline
Member Function Documentation
void fcl::SamplerSE3Euler_ball::getBound (FCL_REAL & r_) const inline
References r.
Vecnf<6> fcl::SamplerSE3Euler_ball::sample () const inline
References fcl::RNG::ball(), fcl::RNG::quaternion(), r, fcl::SamplerBase::rng, and fcl::Quaternion3f::toEuler().
void fcl::SamplerSE3Euler_ball::setBound (const FCL_REAL & r_) inline
References r.
Member Data Documentation
FCL_REAL fcl::SamplerSE3Euler_ball::r protected
Referenced by getBound(), sample(), and setBound().