fcl::SamplerSE2_disk Class Reference
fcl::SamplerSE2_disk Class Reference
#include <hpp/fcl/math/sampling.h>
Public Member Functions
SamplerSE2_disk ()
SamplerSE2_disk (FCL_REAL cx, FCL_REAL cy, FCL_REAL r1, FCL_REAL r2, FCL_REAL crefx, FCL_REAL crefy)
void setBound (FCL_REAL cx, FCL_REAL cy, FCL_REAL r1, FCL_REAL r2, FCL_REAL crefx, FCL_REAL crefy)
Vecnf< 3 > sample () const
Protected Attributes
FCL_REAL c [2]
FCL_REAL cref [2]
FCL_REAL r_min
FCL_REAL r_max
Additional Inherited Members
Public Attributes inherited from fcl::SamplerBase
RNG rng
Constructor & Destructor Documentation
fcl::SamplerSE2_disk::SamplerSE2_disk () inline
fcl::SamplerSE2_disk::SamplerSE2_disk (FCL_REAL cx, FCL_REAL cy, FCL_REAL r1, FCL_REAL r2, FCL_REAL crefx, FCL_REAL crefy) inline
References setBound().
Member Function Documentation
Vecnf<3> fcl::SamplerSE2_disk::sample () const inline
References c, cref, fcl::RNG::disk(), r_max, r_min, fcl::SamplerBase::rng, and fcl::RNG::uniformReal().
void fcl::SamplerSE2_disk::setBound (FCL_REAL cx, FCL_REAL cy, FCL_REAL r1, FCL_REAL r2, FCL_REAL crefx, FCL_REAL crefy) inline
References c, cref, r_max, and r_min.
Referenced by SamplerSE2_disk().
Member Data Documentation
FCL_REAL fcl::SamplerSE2_disk::c[2] protected
Referenced by sample(), and setBound().
FCL_REAL fcl::SamplerSE2_disk::cref[2] protected
Referenced by sample(), and setBound().
FCL_REAL fcl::SamplerSE2_disk::r_max protected
Referenced by sample(), and setBound().
FCL_REAL fcl::SamplerSE2_disk::r_min protected
Referenced by sample(), and setBound().