fcl::Matrix3fX< T > Class Template Reference
fcl::Matrix3fX< T > Class Template Reference
Matrix2 class wrapper. the core data is in the template parameter class.
#include <hpp/fcl/math/matrix_3fx.h>
Public Types
typedef T::meta_type U
typedef T::vector_type S
Public Member Functions
Matrix3fX ()
Matrix3fX (U xx, U xy, U xz, U yx, U yy, U yz, U zx, U zy, U zz)
Matrix3fX (const Vec3fX< S > &v1, const Vec3fX< S > &v2, const Vec3fX< S > &v3)
Matrix3fX (const Matrix3fX< T > &other)
Matrix3fX (const T &data_)
Vec3fX< S > getColumn (size_t i) const
Vec3fX< S > getRow (size_t i) const
U operator() (size_t i, size_t j) const
U & operator() (size_t i, size_t j)
Vec3fX< S > operator* (const Vec3fX< S > &v) const
Matrix3fX< T > operator* (const Matrix3fX< T > &m) const
Matrix3fX< T > operator+ (const Matrix3fX< T > &other) const
Matrix3fX< T > operator- (const Matrix3fX< T > &other) const
Matrix3fX< T > operator+ (U c) const
Matrix3fX< T > operator- (U c) const
Matrix3fX< T > operator* (U c) const
Matrix3fX< T > operator/ (U c) const
Matrix3fX< T > & operator*= (const Matrix3fX< T > &other)
Matrix3fX< T > & operator+= (const Matrix3fX< T > &other)
Matrix3fX< T > & operator-= (const Matrix3fX< T > &other)
Matrix3fX< T > & operator+= (U c)
Matrix3fX< T > & operator-= (U c)
Matrix3fX< T > & operator*= (U c)
Matrix3fX< T > & operator/= (U c)
void setIdentity ()
bool isIdentity () const
void setZero ()
void setEulerZYX (FCL_REAL eulerX, FCL_REAL eulerY, FCL_REAL eulerZ)
Set the matrix from euler angles YPR around ZYX axes.
void setEulerYPR (FCL_REAL yaw, FCL_REAL pitch, FCL_REAL roll)
Set the matrix from euler angles using YPR around YXZ respectively.
U determinant () const
Matrix3fX< T > & transpose ()
Matrix3fX< T > & inverse ()
Matrix3fX< T > & abs ()
Matrix3fX< T > transposeTimes (const Matrix3fX< T > &other) const
Matrix3fX< T > timesTranspose (const Matrix3fX< T > &other) const
Vec3fX< S > transposeTimes (const Vec3fX< S > &v) const
Matrix3fX< T > tensorTransform (const Matrix3fX< T > &m) const
U transposeDotX (const Vec3fX< S > &v) const
U transposeDotY (const Vec3fX< S > &v) const
U transposeDotZ (const Vec3fX< S > &v) const
U transposeDot (size_t i, const Vec3fX< S > &v) const
U dotX (const Vec3fX< S > &v) const
U dotY (const Vec3fX< S > &v) const
U dotZ (const Vec3fX< S > &v) const
U dot (size_t i, const Vec3fX< S > &v) const
void setValue (U xx, U xy, U xz, U yx, U yy, U yz, U zx, U zy, U zz)
void setValue (U x)
Static Public Member Functions
static const Matrix3fX< T > & getIdentity ()
Public Attributes
T data
Detailed Description
template<typename T>
class fcl::Matrix3fX< T >
Matrix2 class wrapper. the core data is in the template parameter class.
Member Typedef Documentation
template<typename T> typedef T::vector_type fcl::Matrix3fX< T >::S
template<typename T> typedef T::meta_type fcl::Matrix3fX< T >::U
Constructor & Destructor Documentation
template<typename T> fcl::Matrix3fX< T >::Matrix3fX () inline
template<typename T> fcl::Matrix3fX< T >::Matrix3fX (U xx, U xy, U xz, U yx, U yy, U yz, U zx, U zy, U zz) inline
template<typename T> fcl::Matrix3fX< T >::Matrix3fX (const Vec3fX< S > & v1, const Vec3fX< S > & v2, const Vec3fX< S > & v3) inline
template<typename T> fcl::Matrix3fX< T >::Matrix3fX (const Matrix3fX< T > & other) inline
template<typename T> fcl::Matrix3fX< T >::Matrix3fX (const T & data_) inline
Member Function Documentation
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::abs () inline
template<typename T> U fcl::Matrix3fX< T >::determinant () const inline
template<typename T> U fcl::Matrix3fX< T >::dot (size_t i, const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> U fcl::Matrix3fX< T >::dotX (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> U fcl::Matrix3fX< T >::dotY (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> U fcl::Matrix3fX< T >::dotZ (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> Vec3fX<S> fcl::Matrix3fX< T >::getColumn (size_t i) const inline
template<typename T> static const Matrix3fX<T>& fcl::Matrix3fX< T >::getIdentity () inline static
template<typename T> Vec3fX<S> fcl::Matrix3fX< T >::getRow (size_t i) const inline
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::inverse () inline
template<typename T> bool fcl::Matrix3fX< T >::isIdentity () const inline
References fcl::Matrix3fX< T >::data.
template<typename T> U fcl::Matrix3fX< T >::operator() (size_t i, size_t j) const inline
References fcl::Matrix3fX< T >::data.
template<typename T> U& fcl::Matrix3fX< T >::operator() (size_t i, size_t j) inline
References fcl::Matrix3fX< T >::data.
template<typename T> Vec3fX<S> fcl::Matrix3fX< T >::operator* (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::operator* (const Matrix3fX< T > & m) const inline
References fcl::Matrix3fX< T >::data.
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::operator* (U c) const inline
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::operator*= (const Matrix3fX< T > & other) inline
References fcl::Matrix3fX< T >::data.
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::operator*= (U c) inline
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::operator+ (const Matrix3fX< T > & other) const inline
References fcl::Matrix3fX< T >::data.
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::operator+ (U c) const inline
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::operator+= (const Matrix3fX< T > & other) inline
References fcl::Matrix3fX< T >::data.
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::operator+= (U c) inline
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::operator- (const Matrix3fX< T > & other) const inline
References fcl::Matrix3fX< T >::data.
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::operator- (U c) const inline
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::operator-= (const Matrix3fX< T > & other) inline
References fcl::Matrix3fX< T >::data.
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::operator-= (U c) inline
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::operator/ (U c) const inline
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::operator/= (U c) inline
template<typename T> void fcl::Matrix3fX< T >::setEulerYPR (FCL_REAL yaw, FCL_REAL pitch, FCL_REAL roll) inline
Set the matrix from euler angles using YPR around YXZ respectively.
Parameters
yaw Yaw about Y axis
pitch Pitch about X axis
roll Roll about Z axis
References fcl::Matrix3fX< T >::setEulerZYX().
template<typename T> void fcl::Matrix3fX< T >::setEulerZYX (FCL_REAL eulerX, FCL_REAL eulerY, FCL_REAL eulerZ) inline
Set the matrix from euler angles YPR around ZYX axes.
Parameters
eulerX Roll about X axis
eulerY Pitch around Y axis
eulerZ Yaw aboud Z axis
These angles are used to produce a rotation matrix. The euler angles are applied in ZYX order. I.e a vector is first rotated about X then Y and then Z
References fcl::Matrix3fX< T >::setValue().
Referenced by fcl::Matrix3fX< T >::setEulerYPR().
template<typename T> void fcl::Matrix3fX< T >::setIdentity () inline
template<typename T> void fcl::Matrix3fX< T >::setValue (U xx, U xy, U xz, U yx, U yy, U yz, U zx, U zy, U zz) inline
Referenced by fcl::hat(), and fcl::Matrix3fX< T >::setEulerZYX().
template<typename T> void fcl::Matrix3fX< T >::setValue (U x) inline
template<typename T> void fcl::Matrix3fX< T >::setZero () inline
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::tensorTransform (const Matrix3fX< T > & m) const inline
References fcl::Matrix3fX< T >::timesTranspose().
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::timesTranspose (const Matrix3fX< T > & other) const inline
References fcl::Matrix3fX< T >::data.
Referenced by fcl::Matrix3fX< T >::tensorTransform().
template<typename T> Matrix3fX<T>& fcl::Matrix3fX< T >::transpose () inline
template<typename T> U fcl::Matrix3fX< T >::transposeDot (size_t i, const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> U fcl::Matrix3fX< T >::transposeDotX (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> U fcl::Matrix3fX< T >::transposeDotY (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> U fcl::Matrix3fX< T >::transposeDotZ (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
template<typename T> Matrix3fX<T> fcl::Matrix3fX< T >::transposeTimes (const Matrix3fX< T > & other) const inline
References fcl::Matrix3fX< T >::data.
Referenced by fcl::relativeTransform().
template<typename T> Vec3fX<S> fcl::Matrix3fX< T >::transposeTimes (const Vec3fX< S > & v) const inline
References fcl::Vec3fX< T >::data.
Member Data Documentation
template<typename T> T fcl::Matrix3fX< T >::data
Referenced by fcl::abs(), fcl::inverse(), fcl::Matrix3fX< T >::isIdentity(), fcl::Matrix3fX< T >::operator()(), fcl::Matrix3fX< T >::operator*(), fcl::Matrix3fX< T >::operator*=(), fcl::Matrix3fX< T >::operator+(), fcl::Matrix3fX< T >::operator+=(), fcl::Matrix3fX< T >::operator-(), fcl::Matrix3fX< T >::operator-=(), fcl::Matrix3fX< T >::timesTranspose(), fcl::transpose(), and fcl::Matrix3fX< T >::transposeTimes().