fcl::details::Matrix3Data< T > Struct Template Reference
fcl::details::Matrix3Data< T > Struct Template Reference
#include <hpp/fcl/math/math_details.h>
Public Types
typedef T meta_type
typedef Vec3Data< T > vector_type
Public Member Functions
Matrix3Data ()
Matrix3Data (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz)
Matrix3Data (const Vec3Data< T > &v1, const Vec3Data< T > &v2, const Vec3Data< T > &v3)
Matrix3Data (const Matrix3Data< T > &other)
Vec3Data< T > getColumn (size_t i) const
const Vec3Data< T > & getRow (size_t i) const
T operator() (size_t i, size_t j) const
T & operator() (size_t i, size_t j)
Vec3Data< T > operator* (const Vec3Data< T > &v) const
Matrix3Data< T > operator* (const Matrix3Data< T > &other) const
Matrix3Data< T > operator+ (const Matrix3Data< T > &other) const
Matrix3Data< T > operator- (const Matrix3Data< T > &other) const
Matrix3Data< T > operator+ (T c) const
Matrix3Data< T > operator- (T c) const
Matrix3Data< T > operator* (T c) const
Matrix3Data< T > operator/ (T c) const
Matrix3Data< T > & operator*= (const Matrix3Data< T > &other)
Matrix3Data< T > & operator+= (const Matrix3Data< T > &other)
Matrix3Data< T > & operator-= (const Matrix3Data< T > &other)
Matrix3Data< T > & operator+= (T c)
Matrix3Data< T > & operator- (T c)
Matrix3Data< T > & operator* (T c)
Matrix3Data< T > & operator/ (T c)
void setIdentity ()
void setZero ()
T determinant () const
Matrix3Data< T > & transpose ()
Matrix3Data< T > & inverse ()
Matrix3Data< T > transposeTimes (const Matrix3Data< T > &m) const
Matrix3Data< T > timesTranspose (const Matrix3Data< T > &m) const
Vec3Data< T > transposeTimes (const Vec3Data< T > &v) const
T transposeDotX (const Vec3Data< T > &v) const
T transposeDotY (const Vec3Data< T > &v) const
T transposeDotZ (const Vec3Data< T > &v) const
T transposeDot (size_t i, const Vec3Data< T > &v) const
T dotX (const Vec3Data< T > &v) const
T dotY (const Vec3Data< T > &v) const
T dotZ (const Vec3Data< T > &v) const
T dot (size_t i, const Vec3Data< T > &v) const
void setValue (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz)
void setValue (T x)
Static Public Member Functions
static const Matrix3Data< T > & getIdentity ()
Public Attributes
Vec3Data< T > rs [3]
Member Typedef Documentation
template<typename T> typedef T fcl::details::Matrix3Data< T >::meta_type
template<typename T> typedef Vec3Data<T> fcl::details::Matrix3Data< T >::vector_type
Constructor & Destructor Documentation
template<typename T> fcl::details::Matrix3Data< T >::Matrix3Data () inline
template<typename T> fcl::details::Matrix3Data< T >::Matrix3Data (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz) inline
References fcl::details::Matrix3Data< T >::setValue().
template<typename T> fcl::details::Matrix3Data< T >::Matrix3Data (const Vec3Data< T > & v1, const Vec3Data< T > & v2, const Vec3Data< T > & v3) inline
template<typename T> fcl::details::Matrix3Data< T >::Matrix3Data (const Matrix3Data< T > & other) inline
References fcl::details::Matrix3Data< T >::rs.
Member Function Documentation
template<typename T> T fcl::details::Matrix3Data< T >::determinant () const inline
References fcl::details::cross_prod(), and fcl::details::dot_prod3().
Referenced by fcl::details::Matrix3Data< T >::inverse(), and fcl::details::inverse().
template<typename T> T fcl::details::Matrix3Data< T >::dot (size_t i, const Vec3Data< T > & v) const inline
template<typename T> T fcl::details::Matrix3Data< T >::dotX (const Vec3Data< T > & v) const inline
template<typename T> T fcl::details::Matrix3Data< T >::dotY (const Vec3Data< T > & v) const inline
template<typename T> T fcl::details::Matrix3Data< T >::dotZ (const Vec3Data< T > & v) const inline
template<typename T> Vec3Data<T> fcl::details::Matrix3Data< T >::getColumn (size_t i) const inline
template<typename T> static const Matrix3Data<T>& fcl::details::Matrix3Data< T >::getIdentity () inline static
template<typename T> const Vec3Data<T>& fcl::details::Matrix3Data< T >::getRow (size_t i) const inline
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::inverse () inline
References fcl::details::Matrix3Data< T >::determinant(), and fcl::details::Matrix3Data< T >::setValue().
template<typename T> T fcl::details::Matrix3Data< T >::operator() (size_t i, size_t j) const inline
template<typename T> T& fcl::details::Matrix3Data< T >::operator() (size_t i, size_t j) inline
template<typename T> Vec3Data<T> fcl::details::Matrix3Data< T >::operator* (const Vec3Data< T > & v) const inline
References fcl::details::dot_prod3().
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::operator* (const Matrix3Data< T > & other) const inline
References fcl::details::Matrix3Data< T >::transposeDotX(), fcl::details::Matrix3Data< T >::transposeDotY(), and fcl::details::Matrix3Data< T >::transposeDotZ().
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::operator* (T c) const inline
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::operator* (T c) inline
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::operator*= (const Matrix3Data< T > & other) inline
References fcl::details::Vec3Data< T >::setValue(), fcl::details::Matrix3Data< T >::transposeDotX(), fcl::details::Matrix3Data< T >::transposeDotY(), and fcl::details::Matrix3Data< T >::transposeDotZ().
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::operator+ (const Matrix3Data< T > & other) const inline
References fcl::details::Matrix3Data< T >::rs.
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::operator+ (T c) const inline
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::operator+= (const Matrix3Data< T > & other) inline
References fcl::details::Matrix3Data< T >::rs.
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::operator+= (T c) inline
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::operator- (const Matrix3Data< T > & other) const inline
References fcl::details::Matrix3Data< T >::rs.
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::operator- (T c) const inline
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::operator- (T c) inline
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::operator-= (const Matrix3Data< T > & other) inline
References fcl::details::Matrix3Data< T >::rs.
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::operator/ (T c) const inline
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::operator/ (T c) inline
template<typename T> void fcl::details::Matrix3Data< T >::setIdentity () inline
References fcl::details::Matrix3Data< T >::setValue().
template<typename T> void fcl::details::Matrix3Data< T >::setValue (T xx, T xy, T xz, T yx, T yy, T yz, T zx, T zy, T zz) inline
References fcl::details::Vec3Data< T >::setValue().
Referenced by fcl::details::Matrix3Data< T >::inverse(), fcl::details::Matrix3Data< T >::Matrix3Data(), fcl::details::Matrix3Data< T >::setIdentity(), and fcl::details::Matrix3Data< T >::setZero().
template<typename T> void fcl::details::Matrix3Data< T >::setValue (T x) inline
References fcl::details::Vec3Data< T >::setValue().
template<typename T> void fcl::details::Matrix3Data< T >::setZero () inline
References fcl::details::Matrix3Data< T >::setValue().
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::timesTranspose (const Matrix3Data< T > & m) const inline
References fcl::details::dot_prod3().
template<typename T> Matrix3Data<T>& fcl::details::Matrix3Data< T >::transpose () inline
template<typename T> T fcl::details::Matrix3Data< T >::transposeDot (size_t i, const Vec3Data< T > & v) const inline
template<typename T> T fcl::details::Matrix3Data< T >::transposeDotX (const Vec3Data< T > & v) const inline
Referenced by fcl::details::Matrix3Data< T >::operator*(), fcl::details::Matrix3Data< T >::operator*=(), and fcl::details::Matrix3Data< T >::transposeTimes().
template<typename T> T fcl::details::Matrix3Data< T >::transposeDotY (const Vec3Data< T > & v) const inline
Referenced by fcl::details::Matrix3Data< T >::operator*(), fcl::details::Matrix3Data< T >::operator*=(), and fcl::details::Matrix3Data< T >::transposeTimes().
template<typename T> T fcl::details::Matrix3Data< T >::transposeDotZ (const Vec3Data< T > & v) const inline
Referenced by fcl::details::Matrix3Data< T >::operator*(), fcl::details::Matrix3Data< T >::operator*=(), and fcl::details::Matrix3Data< T >::transposeTimes().
template<typename T> Matrix3Data<T> fcl::details::Matrix3Data< T >::transposeTimes (const Matrix3Data< T > & m) const inline
References fcl::details::Matrix3Data< T >::rs.
template<typename T> Vec3Data<T> fcl::details::Matrix3Data< T >::transposeTimes (const Vec3Data< T > & v) const inline
References fcl::details::Matrix3Data< T >::transposeDotX(), fcl::details::Matrix3Data< T >::transposeDotY(), and fcl::details::Matrix3Data< T >::transposeDotZ().
Member Data Documentation
template<typename T> Vec3Data<T> fcl::details::Matrix3Data< T >::rs[3]
Referenced by fcl::details::abs(), fcl::details::inverse(), fcl::details::Matrix3Data< T >::Matrix3Data(), fcl::details::Matrix3Data< T >::operator+(), fcl::details::Matrix3Data< T >::operator+=(), fcl::details::Matrix3Data< T >::operator-(), fcl::details::Matrix3Data< T >::operator-=(), fcl::details::transpose(), and fcl::details::Matrix3Data< T >::transposeTimes().