fcl::IVector3 Struct Reference
fcl::IVector3 Struct Reference
#include <hpp/fcl/ccd/interval_vector.h>
Public Member Functions
IVector3 ()
IVector3 (FCL_REAL v)
IVector3 (FCL_REAL x, FCL_REAL y, FCL_REAL z)
IVector3 (FCL_REAL xl, FCL_REAL xu, FCL_REAL yl, FCL_REAL yu, FCL_REAL zl, FCL_REAL zu)
IVector3 (Interval v[3])
IVector3 (FCL_REAL v[3][2])
IVector3 (const Interval &v1, const Interval &v2, const Interval &v3)
IVector3 (const Vec3f &v)
void setValue (FCL_REAL v)
void setValue (FCL_REAL x, FCL_REAL y, FCL_REAL z)
void setValue (FCL_REAL xl, FCL_REAL xu, FCL_REAL yl, FCL_REAL yu, FCL_REAL zl, FCL_REAL zu)
void setValue (FCL_REAL v[3][2])
void setValue (Interval v[3])
void setValue (const Interval &v1, const Interval &v2, const Interval &v3)
void setValue (const Vec3f &v)
void setValue (FCL_REAL v[3])
IVector3 operator+ (const IVector3 &other) const
IVector3 & operator+= (const IVector3 &other)
IVector3 operator- (const IVector3 &other) const
IVector3 & operator-= (const IVector3 &other)
Interval dot (const IVector3 &other) const
IVector3 cross (const IVector3 &other) const
Interval dot (const Vec3f &other) const
IVector3 cross (const Vec3f &other) const
const Interval & operator[] (size_t i) const
Interval & operator[] (size_t i)
Vec3f getLow () const
Vec3f getHigh () const
void print () const
Vec3f center () const
FCL_REAL volumn () const
void setZero ()
void bound (const Vec3f &v)
void bound (const IVector3 &v)
bool overlap (const IVector3 &v) const
bool contain (const IVector3 &v) const
template<typename Derived >
IVector3 & operator= (const FclType< Derived > &other)
Public Attributes
Interval i_ [3]
Constructor & Destructor Documentation
fcl::IVector3::IVector3 ()
fcl::IVector3::IVector3 (FCL_REAL v)
fcl::IVector3::IVector3 (FCL_REAL x, FCL_REAL y, FCL_REAL z)
fcl::IVector3::IVector3 (FCL_REAL xl, FCL_REAL xu, FCL_REAL yl, FCL_REAL yu, FCL_REAL zl, FCL_REAL zu)
fcl::IVector3::IVector3 (Interval v[3])
fcl::IVector3::IVector3 (FCL_REAL v[3][2])
fcl::IVector3::IVector3 (const Interval & v1, const Interval & v2, const Interval & v3)
fcl::IVector3::IVector3 (const Vec3f & v)
Member Function Documentation
void fcl::IVector3::bound (const Vec3f & v)
void fcl::IVector3::bound (const IVector3 & v)
Vec3f fcl::IVector3::center () const
bool fcl::IVector3::contain (const IVector3 & v) const
IVector3 fcl::IVector3::cross (const IVector3 & other) const
IVector3 fcl::IVector3::cross (const Vec3f & other) const
Interval fcl::IVector3::dot (const IVector3 & other) const
Interval fcl::IVector3::dot (const Vec3f & other) const
Vec3f fcl::IVector3::getHigh () const inline
Referenced by fcl::ContinuousCollisionObject::computeAABB().
Vec3f fcl::IVector3::getLow () const inline
Referenced by fcl::ContinuousCollisionObject::computeAABB().
IVector3 fcl::IVector3::operator+ (const IVector3 & other) const
IVector3& fcl::IVector3::operator+= (const IVector3 & other)
IVector3 fcl::IVector3::operator- (const IVector3 & other) const
IVector3& fcl::IVector3::operator-= (const IVector3 & other)
template<typename Derived > IVector3& fcl::IVector3::operator= (const FclType< Derived > & other) inline
const Interval& fcl::IVector3::operator[] (size_t i) const inline
Interval& fcl::IVector3::operator[] (size_t i) inline
bool fcl::IVector3::overlap (const IVector3 & v) const
void fcl::IVector3::print () const
void fcl::IVector3::setValue (FCL_REAL v) inline
References fcl::Interval::setValue().
void fcl::IVector3::setValue (FCL_REAL x, FCL_REAL y, FCL_REAL z) inline
References fcl::Interval::setValue().
void fcl::IVector3::setValue (FCL_REAL xl, FCL_REAL xu, FCL_REAL yl, FCL_REAL yu, FCL_REAL zl, FCL_REAL zu) inline
References fcl::Interval::setValue().
void fcl::IVector3::setValue (FCL_REAL v[3][2]) inline
References fcl::Interval::setValue().
void fcl::IVector3::setValue (Interval v[3]) inline
void fcl::IVector3::setValue (const Interval & v1, const Interval & v2, const Interval & v3) inline
void fcl::IVector3::setValue (const Vec3f & v) inline
References fcl::Interval::setValue().
void fcl::IVector3::setValue (FCL_REAL v[3]) inline
References fcl::Interval::setValue().
void fcl::IVector3::setZero ()
FCL_REAL fcl::IVector3::volumn () const
Member Data Documentation
Interval fcl::IVector3::i_[3]