fcl::Quaternion3f Class Reference
fcl::Quaternion3f Class Reference
Quaternion used locally by InterpMotion.
#include <hpp/fcl/math/transform.h>
Public Member Functions
Quaternion3f ()
Default quaternion is identity rotation.
Quaternion3f (FCL_REAL a, FCL_REAL b, FCL_REAL c, FCL_REAL d)
bool isIdentity () const
Whether the rotation is identity.
void fromRotation (const Matrix3f &R)
Matrix to quaternion.
void toRotation (Matrix3f &R) const
Quaternion to matrix.
void fromEuler (FCL_REAL a, FCL_REAL b, FCL_REAL c)
Euler to quaternion.
void toEuler (FCL_REAL &a, FCL_REAL &b, FCL_REAL &c) const
Quaternion to Euler.
void fromAxes (const Vec3f axis[3])
Axes to quaternion.
void toAxes (Vec3f axis[3]) const
Axes to matrix.
void fromAxisAngle (const Vec3f &axis, FCL_REAL angle)
Axis and angle to quaternion.
void toAxisAngle (Vec3f &axis, FCL_REAL &angle) const
Quaternion to axis and angle.
FCL_REAL dot (const Quaternion3f &other) const
Dot product between quaternions.
Quaternion3f operator+ (const Quaternion3f &other) const
addition
const Quaternion3f & operator+= (const Quaternion3f &other)
Quaternion3f operator- (const Quaternion3f &other) const
minus
const Quaternion3f & operator-= (const Quaternion3f &other)
Quaternion3f operator* (const Quaternion3f &other) const
multiplication
const Quaternion3f & operator*= (const Quaternion3f &other)
Quaternion3f operator- () const
division
Quaternion3f operator* (FCL_REAL t) const
scalar multiplication
const Quaternion3f & operator*= (FCL_REAL t)
Quaternion3f & conj ()
conjugate
Quaternion3f & inverse ()
inverse
Vec3f transform (const Vec3f &v) const
rotate a vector
const FCL_REAL & getW () const
const FCL_REAL & getX () const
const FCL_REAL & getY () const
const FCL_REAL & getZ () const
FCL_REAL & getW ()
FCL_REAL & getX ()
FCL_REAL & getY ()
FCL_REAL & getZ ()
Vec3f getColumn (std::size_t i) const
Vec3f getRow (std::size_t i) const
bool operator== (const Quaternion3f &other) const
bool operator!= (const Quaternion3f &other) const
FCL_REAL operator[] (std::size_t i) const
Quaternion3f ()
Default quaternion is identity rotation.
Quaternion3f (FCL_REAL a, FCL_REAL b, FCL_REAL c, FCL_REAL d)
bool isIdentity () const
Whether the rotation is identity.
void fromRotation (const Matrix3f &R)
Matrix to quaternion.
void toRotation (Matrix3f &R) const
Quaternion to matrix.
void fromEuler (FCL_REAL a, FCL_REAL b, FCL_REAL c)
Euler to quaternion.
void toEuler (FCL_REAL &a, FCL_REAL &b, FCL_REAL &c) const
Quaternion to Euler.
void fromAxes (const Vec3f axis[3])
Axes to quaternion.
void toAxes (Vec3f axis[3]) const
Axes to matrix.
void fromAxisAngle (const Vec3f &axis, FCL_REAL angle)
Axis and angle to quaternion.
void toAxisAngle (Vec3f &axis, FCL_REAL &angle) const
Quaternion to axis and angle.
FCL_REAL dot (const Quaternion3f &other) const
Dot product between quaternions.
Quaternion3f operator+ (const Quaternion3f &other) const
addition
const Quaternion3f & operator+= (const Quaternion3f &other)
Quaternion3f operator- (const Quaternion3f &other) const
minus
const Quaternion3f & operator-= (const Quaternion3f &other)
Quaternion3f operator* (const Quaternion3f &other) const
multiplication
const Quaternion3f & operator*= (const Quaternion3f &other)
Quaternion3f operator- () const
division
Quaternion3f operator* (FCL_REAL t) const
scalar multiplication
const Quaternion3f & operator*= (FCL_REAL t)
Quaternion3f & conj ()
conjugate
Quaternion3f & inverse ()
inverse
Vec3f transform (const Vec3f &v) const
rotate a vector
const FCL_REAL & getW () const
const FCL_REAL & getX () const
const FCL_REAL & getY () const
const FCL_REAL & getZ () const
FCL_REAL & getW ()
FCL_REAL & getX ()
FCL_REAL & getY ()
FCL_REAL & getZ ()
Vec3f getColumn (std::size_t i) const
Vec3f getRow (std::size_t i) const
bool operator== (const Quaternion3f &other) const
bool operator!= (const Quaternion3f &other) const
FCL_REAL operator[] (std::size_t i) const
Detailed Description
Quaternion used locally by InterpMotion.
Constructor & Destructor Documentation
fcl::Quaternion3f::Quaternion3f () inline
Default quaternion is identity rotation.
fcl::Quaternion3f::Quaternion3f (FCL_REAL a, FCL_REAL b, FCL_REAL c, FCL_REAL d) inline
References d().
fcl::Quaternion3f::Quaternion3f () inline
Default quaternion is identity rotation.
fcl::Quaternion3f::Quaternion3f (FCL_REAL a, FCL_REAL b, FCL_REAL c, FCL_REAL d) inline
References d().
Member Function Documentation
Quaternion3f& fcl::Quaternion3f::conj ()
conjugate
Quaternion3f& fcl::Quaternion3f::conj ()
conjugate
FCL_REAL fcl::Quaternion3f::dot (const Quaternion3f & other) const
Dot product between quaternions.
FCL_REAL fcl::Quaternion3f::dot (const Quaternion3f & other) const
Dot product between quaternions.
void fcl::Quaternion3f::fromAxes (const Vec3f axis[3])
Axes to quaternion.
void fcl::Quaternion3f::fromAxes (const Vec3f axis[3])
Axes to quaternion.
void fcl::Quaternion3f::fromAxisAngle (const Vec3f & axis, FCL_REAL angle)
Axis and angle to quaternion.
void fcl::Quaternion3f::fromAxisAngle (const Vec3f & axis, FCL_REAL angle)
Axis and angle to quaternion.
Referenced by fcl::ScrewMotion::deltaRotation().
void fcl::Quaternion3f::fromEuler (FCL_REAL a, FCL_REAL b, FCL_REAL c)
Euler to quaternion.
void fcl::Quaternion3f::fromEuler (FCL_REAL a, FCL_REAL b, FCL_REAL c)
Euler to quaternion.
void fcl::Quaternion3f::fromRotation (const Matrix3f & R)
Matrix to quaternion.
void fcl::Quaternion3f::fromRotation (const Matrix3f & R)
Matrix to quaternion.
Referenced by fcl::TranslationMotion::TranslationMotion().
Vec3f fcl::Quaternion3f::getColumn (std::size_t i) const
Vec3f fcl::Quaternion3f::getColumn (std::size_t i) const
Vec3f fcl::Quaternion3f::getRow (std::size_t i) const
Vec3f fcl::Quaternion3f::getRow (std::size_t i) const
const FCL_REAL& fcl::Quaternion3f::getW () const inline
const FCL_REAL& fcl::Quaternion3f::getW () const inline
FCL_REAL& fcl::Quaternion3f::getW () inline
FCL_REAL& fcl::Quaternion3f::getW () inline
const FCL_REAL& fcl::Quaternion3f::getX () const inline
const FCL_REAL& fcl::Quaternion3f::getX () const inline
FCL_REAL& fcl::Quaternion3f::getX () inline
FCL_REAL& fcl::Quaternion3f::getX () inline
const FCL_REAL& fcl::Quaternion3f::getY () const inline
const FCL_REAL& fcl::Quaternion3f::getY () const inline
FCL_REAL& fcl::Quaternion3f::getY () inline
FCL_REAL& fcl::Quaternion3f::getY () inline
const FCL_REAL& fcl::Quaternion3f::getZ () const inline
const FCL_REAL& fcl::Quaternion3f::getZ () const inline
FCL_REAL& fcl::Quaternion3f::getZ () inline
FCL_REAL& fcl::Quaternion3f::getZ () inline
Quaternion3f& fcl::Quaternion3f::inverse ()
inverse
Quaternion3f& fcl::Quaternion3f::inverse ()
inverse
bool fcl::Quaternion3f::isIdentity () const inline
Whether the rotation is identity.
bool fcl::Quaternion3f::isIdentity () const inline
Whether the rotation is identity.
Referenced by fcl::CollisionObject::computeAABB().
bool fcl::Quaternion3f::operator!= (const Quaternion3f & other) const inline
bool fcl::Quaternion3f::operator!= (const Quaternion3f & other) const inline
Quaternion3f fcl::Quaternion3f::operator* (const Quaternion3f & other) const
multiplication
Quaternion3f fcl::Quaternion3f::operator* (const Quaternion3f & other) const
multiplication
Quaternion3f fcl::Quaternion3f::operator* (FCL_REAL t) const
scalar multiplication
Quaternion3f fcl::Quaternion3f::operator* (FCL_REAL t) const
scalar multiplication
const Quaternion3f& fcl::Quaternion3f::operator*= (const Quaternion3f & other)
const Quaternion3f& fcl::Quaternion3f::operator*= (const Quaternion3f & other)
const Quaternion3f& fcl::Quaternion3f::operator*= (FCL_REAL t)
const Quaternion3f& fcl::Quaternion3f::operator*= (FCL_REAL t)
Quaternion3f fcl::Quaternion3f::operator+ (const Quaternion3f & other) const
addition
Quaternion3f fcl::Quaternion3f::operator+ (const Quaternion3f & other) const
addition
const Quaternion3f& fcl::Quaternion3f::operator+= (const Quaternion3f & other)
const Quaternion3f& fcl::Quaternion3f::operator+= (const Quaternion3f & other)
Quaternion3f fcl::Quaternion3f::operator- (const Quaternion3f & other) const
minus
Quaternion3f fcl::Quaternion3f::operator- (const Quaternion3f & other) const
minus
Quaternion3f fcl::Quaternion3f::operator- () const
division
Quaternion3f fcl::Quaternion3f::operator- () const
division
const Quaternion3f& fcl::Quaternion3f::operator-= (const Quaternion3f & other)
const Quaternion3f& fcl::Quaternion3f::operator-= (const Quaternion3f & other)
bool fcl::Quaternion3f::operator== (const Quaternion3f & other) const inline
bool fcl::Quaternion3f::operator== (const Quaternion3f & other) const inline
FCL_REAL fcl::Quaternion3f::operator[] (std::size_t i) const inline
FCL_REAL fcl::Quaternion3f::operator[] (std::size_t i) const inline
void fcl::Quaternion3f::toAxes (Vec3f axis[3]) const
Axes to matrix.
void fcl::Quaternion3f::toAxes (Vec3f axis[3]) const
Axes to matrix.
void fcl::Quaternion3f::toAxisAngle (Vec3f & axis, FCL_REAL & angle) const
Quaternion to axis and angle.
void fcl::Quaternion3f::toAxisAngle (Vec3f & axis, FCL_REAL & angle) const
Quaternion to axis and angle.
Referenced by fcl::ScrewMotion::computeScrewParameter().
void fcl::Quaternion3f::toEuler (FCL_REAL & a, FCL_REAL & b, FCL_REAL & c) const
Quaternion to Euler.
void fcl::Quaternion3f::toEuler (FCL_REAL & a, FCL_REAL & b, FCL_REAL & c) const
Quaternion to Euler.
Referenced by fcl::SamplerSE3Euler::sample(), and fcl::SamplerSE3Euler_ball::sample().
void fcl::Quaternion3f::toRotation (Matrix3f & R) const
Quaternion to matrix.
void fcl::Quaternion3f::toRotation (Matrix3f & R) const
Quaternion to matrix.
Vec3f fcl::Quaternion3f::transform (const Vec3f & v) const
rotate a vector
Vec3f fcl::Quaternion3f::transform (const Vec3f & v) const
rotate a vector
Referenced by fcl::InterpMotion::getTaylorModel(), fcl::ScrewMotion::integrate(), fcl::Transform3f::inverseTimes(), fcl::Transform3f::operator*(), and fcl::GJKSolver_libccd::shapeTriangleDistance().