fcl::NodeBase< BV > Struct Template Reference
fcl::NodeBase< BV > Struct Template Reference
dynamic AABB tree node
#include <hpp/fcl/broadphase/hierarchy_tree.h>
Public Member Functions
bool isLeaf () const
whether is a leaf
bool isInternal () const
whether is internal node
NodeBase ()
Public Attributes
BV bv
the bounding volume for the node
NodeBase< BV > * parent
pointer to parent node
union {
NodeBase< BV > * children [2]
for leaf node, children nodes
void * data
};
FCL_UINT32 code
morton code for current BV
Detailed Description
template<typename BV>
struct fcl::NodeBase< BV >
dynamic AABB tree node
Constructor & Destructor Documentation
template<typename BV> fcl::NodeBase< BV >::NodeBase () inline
References fcl::NodeBase< BV >::children.
Member Function Documentation
template<typename BV> bool fcl::NodeBase< BV >::isInternal () const inline
whether is internal node
References fcl::NodeBase< BV >::isLeaf().
template<typename BV> bool fcl::NodeBase< BV >::isLeaf () const inline
whether is a leaf
References fcl::NodeBase< BV >::children.
Referenced by fcl::HierarchyTree< BV >::balanceIncremental(), fcl::HierarchyTree< BV >::extractLeaves(), fcl::NodeBase< BV >::isInternal(), and fcl::HierarchyTree< BV >::print().
Member Data Documentation
union { ... }
template<typename BV> BV fcl::NodeBase< BV >::bv
the bounding volume for the node
Referenced by fcl::nodeBaseLess(), fcl::HierarchyTree< BV >::print(), and fcl::HierarchyTree< BV >::update().
template<typename BV> NodeBase<BV>* fcl::NodeBase< BV >::children[2]
for leaf node, children nodes
Referenced by fcl::HierarchyTree< BV >::balanceIncremental(), fcl::HierarchyTree< BV >::extractLeaves(), fcl::NodeBase< BV >::isLeaf(), fcl::NodeBase< BV >::NodeBase(), and fcl::HierarchyTree< BV >::print().
template<typename BV> FCL_UINT32 fcl::NodeBase< BV >::code
morton code for current BV
template<typename BV> void* fcl::NodeBase< BV >::data
template<typename BV> NodeBase<BV>* fcl::NodeBase< BV >::parent
pointer to parent node
Referenced by fcl::HierarchyTree< BV >::update().