fcl::details::MinkowskiDiff Struct Reference
fcl::details::MinkowskiDiff Struct Reference
Minkowski difference class of two shapes.
#include <hpp/fcl/narrowphase/gjk.h>
Public Member Functions
MinkowskiDiff ()
Vec3f support0 (const Vec3f &d) const
support function for shape0
Vec3f support1 (const Vec3f &d) const
support function for shape1
Vec3f support (const Vec3f &d) const
support function for the pair of shapes
Vec3f support (const Vec3f &d, size_t index) const
support function for the d-th shape (d = 0 or 1)
Vec3f support0 (const Vec3f &d, const Vec3f &v) const
support function for translating shape0, which is translating at velocity v
Vec3f support (const Vec3f &d, const Vec3f &v) const
support function for the pair of shapes, where shape0 is translating at velocity v
Vec3f support (const Vec3f &d, const Vec3f &v, size_t index) const
support function for the d-th shape (d = 0 or 1), where shape0 is translating at velocity v
Public Attributes
const ShapeBase * shapes [2]
points to two shapes
Matrix3f toshape1
rotation from shape0 to shape1
Transform3f toshape0
transform from shape1 to shape0
Detailed Description
Minkowski difference class of two shapes.
Note
The Minkowski difference is expressed in the frame of the first shape.
Constructor & Destructor Documentation
fcl::details::MinkowskiDiff::MinkowskiDiff () inline
Member Function Documentation
Vec3f fcl::details::MinkowskiDiff::support (const Vec3f & d) const inline
support function for the pair of shapes
References support0(), and support1().
Referenced by fcl::GJKSolver_indep::shapeDistance(), fcl::GJKSolver_indep::shapeIntersect(), fcl::GJKSolver_indep::shapeTriangleDistance(), and fcl::GJKSolver_indep::shapeTriangleIntersect().
Vec3f fcl::details::MinkowskiDiff::support (const Vec3f & d, size_t index) const inline
support function for the d-th shape (d = 0 or 1)
References support0(), and support1().
Vec3f fcl::details::MinkowskiDiff::support (const Vec3f & d, const Vec3f & v) const inline
support function for the pair of shapes, where shape0 is translating at velocity v
References support0(), and support1().
Vec3f fcl::details::MinkowskiDiff::support (const Vec3f & d, const Vec3f & v, size_t index) const inline
support function for the d-th shape (d = 0 or 1), where shape0 is translating at velocity v
References support0(), and support1().
Vec3f fcl::details::MinkowskiDiff::support0 (const Vec3f & d) const inline
support function for shape0
References fcl::details::getSupport().
Referenced by support().
Vec3f fcl::details::MinkowskiDiff::support0 (const Vec3f & d, const Vec3f & v) const inline
support function for translating shape0, which is translating at velocity v
References fcl::details::getSupport(), and v.
Vec3f fcl::details::MinkowskiDiff::support1 (const Vec3f & d) const inline
support function for shape1
References fcl::details::getSupport(), and fcl::Transform3f::transform().
Referenced by support().
Member Data Documentation
const ShapeBase* fcl::details::MinkowskiDiff::shapes[2]
points to two shapes
Referenced by fcl::GJKSolver_indep::shapeDistance(), fcl::GJKSolver_indep::shapeIntersect(), fcl::GJKSolver_indep::shapeTriangleDistance(), and fcl::GJKSolver_indep::shapeTriangleIntersect().
Transform3f fcl::details::MinkowskiDiff::toshape0
transform from shape1 to shape0
Referenced by fcl::GJKSolver_indep::shapeDistance(), fcl::GJKSolver_indep::shapeIntersect(), fcl::GJKSolver_indep::shapeTriangleDistance(), and fcl::GJKSolver_indep::shapeTriangleIntersect().
Matrix3f fcl::details::MinkowskiDiff::toshape1
rotation from shape0 to shape1
Referenced by fcl::GJKSolver_indep::shapeDistance(), fcl::GJKSolver_indep::shapeIntersect(), fcl::GJKSolver_indep::shapeTriangleDistance(), and fcl::GJKSolver_indep::shapeTriangleIntersect().