fcl::SamplerSE3Euler Class Reference
fcl::SamplerSE3Euler Class Reference
#include <hpp/fcl/math/sampling.h>
Public Member Functions
SamplerSE3Euler ()
SamplerSE3Euler (const Vecnf< 3 > &lower_bound_, const Vecnf< 3 > &upper_bound_)
SamplerSE3Euler (const Vec3f &lower_bound_, const Vec3f &upper_bound_)
void setBound (const Vecnf< 3 > &lower_bound_, const Vecnf< 3 > &upper_bound_)
void setBound (const Vec3f &lower_bound_, const Vec3f &upper_bound_)
void getBound (Vecnf< 3 > &lower_bound_, Vecnf< 3 > &upper_bound_) const
void getBound (Vec3f &lower_bound_, Vec3f &upper_bound_) const
Vecnf< 6 > sample () const
Protected Attributes
Vecnf< 3 > lower_bound
Vecnf< 3 > upper_bound
Additional Inherited Members
Public Attributes inherited from fcl::SamplerBase
RNG rng
Constructor & Destructor Documentation
fcl::SamplerSE3Euler::SamplerSE3Euler () inline
fcl::SamplerSE3Euler::SamplerSE3Euler (const Vecnf< 3 > & lower_bound_, const Vecnf< 3 > & upper_bound_) inline
fcl::SamplerSE3Euler::SamplerSE3Euler (const Vec3f & lower_bound_, const Vec3f & upper_bound_) inline
Member Function Documentation
void fcl::SamplerSE3Euler::getBound (Vecnf< 3 > & lower_bound_, Vecnf< 3 > & upper_bound_) const inline
References lower_bound, and upper_bound.
void fcl::SamplerSE3Euler::getBound (Vec3f & lower_bound_, Vec3f & upper_bound_) const inline
References lower_bound, and upper_bound.
Vecnf<6> fcl::SamplerSE3Euler::sample () const inline
References lower_bound, fcl::RNG::quaternion(), fcl::SamplerBase::rng, fcl::Quaternion3f::toEuler(), fcl::RNG::uniformReal(), and upper_bound.
void fcl::SamplerSE3Euler::setBound (const Vecnf< 3 > & lower_bound_, const Vecnf< 3 > & upper_bound_) inline
References lower_bound, and upper_bound.
void fcl::SamplerSE3Euler::setBound (const Vec3f & lower_bound_, const Vec3f & upper_bound_) inline
References lower_bound, and upper_bound.
Member Data Documentation
Vecnf<3> fcl::SamplerSE3Euler::lower_bound protected
Referenced by getBound(), sample(), and setBound().
Vecnf<3> fcl::SamplerSE3Euler::upper_bound protected
Referenced by getBound(), sample(), and setBound().