fcl::TranslationMotion Class Reference
fcl::TranslationMotion Class Reference
#include <hpp/fcl/ccd/motion.h>
Public Member Functions
TranslationMotion (const Transform3f &tf1, const Transform3f &tf2)
Construct motion from intial and goal transform.
TranslationMotion (const Matrix3f &R, const Vec3f &T1, const Vec3f &T2)
bool integrate (FCL_REAL dt) const
Integrate the motion from 0 to dt.
FCL_REAL computeMotionBound (const BVMotionBoundVisitor &mb_visitor) const
Compute the motion bound for a bounding volume, given the closest direction n between two query objects.
FCL_REAL computeMotionBound (const TriangleMotionBoundVisitor &mb_visitor) const
Compute the motion bound for a triangle, given the closest direction n between two query objects.
void getCurrentTransform (Transform3f &tf_) const
void getTaylorModel (TMatrix3 &, TVector3 &) const
Vec3f getVelocity () const
Public Member Functions inherited from fcl::MotionBase
MotionBase ()
virtual ~MotionBase ()
void getCurrentTransform (Matrix3f &R, Vec3f &T) const
Get the rotation and translation in current step.
void getCurrentTransform (Quaternion3f &Q, Vec3f &T) const
void getCurrentRotation (Matrix3f &R) const
void getCurrentRotation (Quaternion3f &Q) const
void getCurrentTranslation (Vec3f &T) const
const boost::shared_ptr< TimeInterval > & getTimeInterval () const
Additional Inherited Members
Protected Attributes inherited from fcl::MotionBase
boost::shared_ptr< TimeInterval > time_interval_
Constructor & Destructor Documentation
fcl::TranslationMotion::TranslationMotion (const Transform3f & tf1, const Transform3f & tf2) inline
Construct motion from intial and goal transform.
fcl::TranslationMotion::TranslationMotion (const Matrix3f & R, const Vec3f & T1, const Vec3f & T2) inline
References fcl::Quaternion3f::fromRotation().
Member Function Documentation
FCL_REAL fcl::TranslationMotion::computeMotionBound (const BVMotionBoundVisitor & mb_visitor) const inline virtual
Compute the motion bound for a bounding volume, given the closest direction n between two query objects.
Implements fcl::MotionBase.
References fcl::BVMotionBoundVisitor::visit().
FCL_REAL fcl::TranslationMotion::computeMotionBound (const TriangleMotionBoundVisitor & mb_visitor) const inline virtual
Compute the motion bound for a triangle, given the closest direction n between two query objects.
Implements fcl::MotionBase.
References fcl::TriangleMotionBoundVisitor::visit().
void fcl::TranslationMotion::getCurrentTransform (Transform3f & tf_) const inline virtual
Implements fcl::MotionBase.
void fcl::TranslationMotion::getTaylorModel (TMatrix3 & , TVector3 &) const inline virtual
Implements fcl::MotionBase.
Vec3f fcl::TranslationMotion::getVelocity () const inline
bool fcl::TranslationMotion::integrate (FCL_REAL dt) const inline virtual
Integrate the motion from 0 to dt.
Implements fcl::MotionBase.