fcl::SpatialHashingCollisionManager< HashTable > Class Template Reference
fcl::SpatialHashingCollisionManager< HashTable > Class Template Reference
spatial hashing collision mananger
#include <hpp/fcl/broadphase/broadphase_spatialhash.h>
Public Member Functions
SpatialHashingCollisionManager (FCL_REAL cell_size, const Vec3f &scene_min, const Vec3f &scene_max, unsigned int default_table_size=1000)
~SpatialHashingCollisionManager ()
void registerObject (CollisionObject *obj)
add one object to the manager
void unregisterObject (CollisionObject *obj)
remove one object from the manager
void setup ()
initialize the manager, related with the specific type of manager
void update ()
update the condition of manager
void update (CollisionObject *updated_obj)
update the manager by explicitly given the object updated
void update (const std::vector< CollisionObject * > &updated_objs)
update the manager by explicitly given the set of objects update
void clear ()
clear the manager
void getObjects (std::vector< CollisionObject * > &objs) const
return the objects managed by the manager
void collide (CollisionObject *obj, void *cdata, CollisionCallBack callback) const
perform collision test between one object and all the objects belonging to the manager
void distance (CollisionObject *obj, void *cdata, DistanceCallBack callback) const
perform distance computation between one object and all the objects belonging ot the manager
void collide (void *cdata, CollisionCallBack callback) const
perform collision test for the objects belonging to the manager (i.e, N^2 self collision)
void distance (void *cdata, DistanceCallBack callback) const
perform distance test for the objects belonging to the manager (i.e., N^2 self distance)
void collide (BroadPhaseCollisionManager *other_manager, void *cdata, CollisionCallBack callback) const
perform collision test with objects belonging to another manager
void distance (BroadPhaseCollisionManager *other_manager, void *cdata, DistanceCallBack callback) const
perform distance test with objects belonging to another manager
bool empty () const
whether the manager is empty
size_t size () const
the number of objects managed by the manager
Public Member Functions inherited from fcl::BroadPhaseCollisionManager
BroadPhaseCollisionManager ()
virtual ~BroadPhaseCollisionManager ()
virtual void registerObjects (const std::vector< CollisionObject * > &other_objs)
add objects to the manager
Static Public Member Functions
static void computeBound (std::vector< CollisionObject * > &objs, Vec3f &l, Vec3f &u)
compute the bound for the environent
Protected Member Functions
bool collide_ (CollisionObject *obj, void *cdata, CollisionCallBack callback) const
perform collision test between one object and all the objects belonging to the manager
bool distance_ (CollisionObject *obj, void *cdata, DistanceCallBack callback, FCL_REAL &min_dist) const
perform distance computation between one object and all the objects belonging ot the manager
Protected Member Functions inherited from fcl::BroadPhaseCollisionManager
bool inTestedSet (CollisionObject *a, CollisionObject *b) const
void insertTestedSet (CollisionObject *a, CollisionObject *b) const
Protected Attributes
std::list< CollisionObject * > objs
all objects in the scene
std::list< CollisionObject * > objs_outside_scene_limit
objects outside the scene limit are in another list
AABB scene_limit
the size of the scene
std::map< CollisionObject *, AABB > obj_aabb_map
store the map between objects and their aabbs. will make update more convenient
HashTable * hash_table
objects in the scene limit (given by scene_min and scene_max) are in the spatial hash table
Protected Attributes inherited from fcl::BroadPhaseCollisionManager
std::set< std::pair< CollisionObject *, CollisionObject * > > tested_set
tools help to avoid repeating collision or distance callback for the pairs of objects tested before. It can be useful for some of the broadphase algorithms.
bool enable_tested_set_
Detailed Description
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>>
class fcl::SpatialHashingCollisionManager< HashTable >
spatial hashing collision mananger
Constructor & Destructor Documentation
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> fcl::SpatialHashingCollisionManager< HashTable >::SpatialHashingCollisionManager (FCL_REAL cell_size, const Vec3f & scene_min, const Vec3f & scene_max, unsigned int default_table_size = 1000) inline
References fcl::SpatialHashingCollisionManager< HashTable >::hash_table.
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> fcl::SpatialHashingCollisionManager< HashTable >::~SpatialHashingCollisionManager () inline
References fcl::SpatialHashingCollisionManager< HashTable >::hash_table.
Member Function Documentation
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::clear () virtual
clear the manager
Implements fcl::BroadPhaseCollisionManager.
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::collide (CollisionObject * obj, void * cdata, CollisionCallBack callback) const virtual
perform collision test between one object and all the objects belonging to the manager
Implements fcl::BroadPhaseCollisionManager.
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::collide (void * cdata, CollisionCallBack callback) const virtual
perform collision test for the objects belonging to the manager (i.e, N^2 self collision)
Implements fcl::BroadPhaseCollisionManager.
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::collide (BroadPhaseCollisionManager * other_manager, void * cdata, CollisionCallBack callback) const virtual
perform collision test with objects belonging to another manager
Implements fcl::BroadPhaseCollisionManager.
References fcl::collide(), fcl::SpatialHashingCollisionManager< HashTable >::collide_(), fcl::SpatialHashingCollisionManager< HashTable >::objs, and fcl::SpatialHashingCollisionManager< HashTable >::size().
template<typename HashTable > bool fcl::SpatialHashingCollisionManager< HashTable >::collide_ (CollisionObject * obj, void * cdata, CollisionCallBack callback) const protected
perform collision test between one object and all the objects belonging to the manager
References fcl::CollisionObject::getAABB().
Referenced by fcl::SpatialHashingCollisionManager< HashTable >::collide().
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> static void fcl::SpatialHashingCollisionManager< HashTable >::computeBound (std::vector< CollisionObject * > & objs, Vec3f & l, Vec3f & u) inline static
compute the bound for the environent
References fcl::bound(), fcl::AABB::max_, and fcl::AABB::min_.
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::distance (CollisionObject * obj, void * cdata, DistanceCallBack callback) const virtual
perform distance computation between one object and all the objects belonging ot the manager
Implements fcl::BroadPhaseCollisionManager.
References fcl::details::max().
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::distance (void * cdata, DistanceCallBack callback) const virtual
perform distance test for the objects belonging to the manager (i.e., N^2 self distance)
Implements fcl::BroadPhaseCollisionManager.
References fcl::details::max().
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::distance (BroadPhaseCollisionManager * other_manager, void * cdata, DistanceCallBack callback) const virtual
perform distance test with objects belonging to another manager
Implements fcl::BroadPhaseCollisionManager.
References fcl::distance(), fcl::SpatialHashingCollisionManager< HashTable >::distance_(), fcl::details::max(), fcl::SpatialHashingCollisionManager< HashTable >::objs, and fcl::SpatialHashingCollisionManager< HashTable >::size().
template<typename HashTable > bool fcl::SpatialHashingCollisionManager< HashTable >::distance_ (CollisionObject * obj, void * cdata, DistanceCallBack callback, FCL_REAL & min_dist) const protected
perform distance computation between one object and all the objects belonging ot the manager
References fcl::AABB::distance(), fcl::AABB::equal(), fcl::AABB::expand(), fcl::CollisionObject::getAABB(), fcl::details::max(), fcl::AABB::max_, and fcl::AABB::min_.
Referenced by fcl::SpatialHashingCollisionManager< HashTable >::distance().
template<typename HashTable > bool fcl::SpatialHashingCollisionManager< HashTable >::empty () const virtual
whether the manager is empty
Implements fcl::BroadPhaseCollisionManager.
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::getObjects (std::vector< CollisionObject * > & objs) const virtual
return the objects managed by the manager
Implements fcl::BroadPhaseCollisionManager.
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::registerObject (CollisionObject * obj) virtual
add one object to the manager
Implements fcl::BroadPhaseCollisionManager.
References fcl::CollisionObject::getAABB().
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::setup () virtual
initialize the manager, related with the specific type of manager
Implements fcl::BroadPhaseCollisionManager.
template<typename HashTable > size_t fcl::SpatialHashingCollisionManager< HashTable >::size () const virtual
the number of objects managed by the manager
Implements fcl::BroadPhaseCollisionManager.
Referenced by fcl::SpatialHashingCollisionManager< HashTable >::collide(), and fcl::SpatialHashingCollisionManager< HashTable >::distance().
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::unregisterObject (CollisionObject * obj) virtual
remove one object from the manager
Implements fcl::BroadPhaseCollisionManager.
References fcl::CollisionObject::getAABB().
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::update () virtual
update the condition of manager
Implements fcl::BroadPhaseCollisionManager.
References fcl::CollisionObject::getAABB().
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::update (CollisionObject * updated_obj) virtual
update the manager by explicitly given the object updated
Reimplemented from fcl::BroadPhaseCollisionManager.
References fcl::CollisionObject::getAABB().
template<typename HashTable > void fcl::SpatialHashingCollisionManager< HashTable >::update (const std::vector< CollisionObject * > & updated_objs) virtual
update the manager by explicitly given the set of objects update
Reimplemented from fcl::BroadPhaseCollisionManager.
Member Data Documentation
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> HashTable* fcl::SpatialHashingCollisionManager< HashTable >::hash_table protected
objects in the scene limit (given by scene_min and scene_max) are in the spatial hash table
Referenced by fcl::SpatialHashingCollisionManager< HashTable >::SpatialHashingCollisionManager(), and fcl::SpatialHashingCollisionManager< HashTable >::~SpatialHashingCollisionManager().
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> std::map<CollisionObject*, AABB> fcl::SpatialHashingCollisionManager< HashTable >::obj_aabb_map protected
store the map between objects and their aabbs. will make update more convenient
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> std::list<CollisionObject*> fcl::SpatialHashingCollisionManager< HashTable >::objs protected
all objects in the scene
Referenced by fcl::SpatialHashingCollisionManager< HashTable >::collide(), and fcl::SpatialHashingCollisionManager< HashTable >::distance().
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> std::list<CollisionObject*> fcl::SpatialHashingCollisionManager< HashTable >::objs_outside_scene_limit protected
objects outside the scene limit are in another list
template<typename HashTable = SimpleHashTable<AABB, CollisionObject*, SpatialHash>> AABB fcl::SpatialHashingCollisionManager< HashTable >::scene_limit protected
the size of the scene