fcl::details::sse_meta_f4 Struct Reference
fcl::details::sse_meta_f4 Struct Reference
#include <hpp/fcl/simd/math_simd_details.h>
Public Types
typedef float meta_type
Public Member Functions
sse_meta_f4 ()
sse_meta_f4 (float x)
sse_meta_f4 (float *px)
sse_meta_f4 (__m128 x)
sse_meta_f4 (float x, float y, float z, float w=1)
void setValue (float x, float y, float z, float w=1)
void setValue (float x)
void setValue (__m128 x)
void negate ()
sse_meta_f4 & ubound (const sse_meta_f4 &u)
sse_meta_f4 & lbound (const sse_meta_f4 &l)
void * operator new[] (size_t n)
void operator delete[] (void *x)
float operator[] (size_t i) const
float & operator[] (size_t i)
sse_meta_f4 operator+ (const sse_meta_f4 &other) const
sse_meta_f4 operator- (const sse_meta_f4 &other) const
sse_meta_f4 operator* (const sse_meta_f4 &other) const
sse_meta_f4 operator/ (const sse_meta_f4 &other) const
sse_meta_f4 & operator+= (const sse_meta_f4 &other)
sse_meta_f4 & operator-= (const sse_meta_f4 &other)
sse_meta_f4 & operator*= (const sse_meta_f4 &other)
sse_meta_f4 & operator/= (const sse_meta_f4 &other)
sse_meta_f4 operator+ (float t) const
sse_meta_f4 operator- (float t) const
sse_meta_f4 operator* (float t) const
sse_meta_f4 operator/ (float t) const
sse_meta_f4 & operator+= (float t)
sse_meta_f4 & operator-= (float t)
sse_meta_f4 & operator*= (float t)
sse_meta_f4 & operator/= (float t)
sse_meta_f4 operator- () const
Public Attributes
union {
float vs [4]
__m128 v
};
Member Typedef Documentation
typedef float fcl::details::sse_meta_f4::meta_type
Constructor & Destructor Documentation
fcl::details::sse_meta_f4::sse_meta_f4 () inline
Referenced by operator*(), operator*(), operator+(), operator-(), operator-=(), operator/(), operator/(), and setValue().
fcl::details::sse_meta_f4::sse_meta_f4 (float x) inline
fcl::details::sse_meta_f4::sse_meta_f4 (float * px) inline
fcl::details::sse_meta_f4::sse_meta_f4 (__m128 x) inline
fcl::details::sse_meta_f4::sse_meta_f4 (float x, float y, float z, float w = 1) inline
Member Function Documentation
sse_meta_f4& fcl::details::sse_meta_f4::lbound (const sse_meta_f4 & l) inline
void fcl::details::sse_meta_f4::negate () inline
void fcl::details::sse_meta_f4::operator delete[] (void * x) inline
void* fcl::details::sse_meta_f4::operator new[] (size_t n) inline
sse_meta_f4 fcl::details::sse_meta_f4::operator* (const sse_meta_f4 & other) const inline
sse_meta_f4 fcl::details::sse_meta_f4::operator* (float t) const inline
References sse_meta_f4().
sse_meta_f4& fcl::details::sse_meta_f4::operator*= (const sse_meta_f4 & other) inline
sse_meta_f4& fcl::details::sse_meta_f4::operator*= (float t) inline
sse_meta_f4 fcl::details::sse_meta_f4::operator+ (const sse_meta_f4 & other) const inline
sse_meta_f4 fcl::details::sse_meta_f4::operator+ (float t) const inline
References sse_meta_f4().
sse_meta_f4& fcl::details::sse_meta_f4::operator+= (const sse_meta_f4 & other) inline
sse_meta_f4& fcl::details::sse_meta_f4::operator+= (float t) inline
sse_meta_f4 fcl::details::sse_meta_f4::operator- (const sse_meta_f4 & other) const inline
sse_meta_f4 fcl::details::sse_meta_f4::operator- (float t) const inline
References sse_meta_f4().
sse_meta_f4 fcl::details::sse_meta_f4::operator- () const inline
References fcl::details::__attribute__, and sse_meta_f4().
sse_meta_f4& fcl::details::sse_meta_f4::operator-= (const sse_meta_f4 & other) inline
sse_meta_f4& fcl::details::sse_meta_f4::operator-= (float t) inline
sse_meta_f4 fcl::details::sse_meta_f4::operator/ (const sse_meta_f4 & other) const inline
sse_meta_f4 fcl::details::sse_meta_f4::operator/ (float t) const inline
References sse_meta_f4().
sse_meta_f4& fcl::details::sse_meta_f4::operator/= (const sse_meta_f4 & other) inline
sse_meta_f4& fcl::details::sse_meta_f4::operator/= (float t) inline
float fcl::details::sse_meta_f4::operator[] (size_t i) const inline
float& fcl::details::sse_meta_f4::operator[] (size_t i) inline
void fcl::details::sse_meta_f4::setValue (float x, float y, float z, float w = 1) inline
void fcl::details::sse_meta_f4::setValue (float x) inline
void fcl::details::sse_meta_f4::setValue (__m128 x) inline
sse_meta_f4& fcl::details::sse_meta_f4::ubound (const sse_meta_f4 & u) inline
Member Data Documentation
union { ... }
__m128 fcl::details::sse_meta_f4::v
Referenced by fcl::details::inverse(), and fcl::details::transpose().
float fcl::details::sse_meta_f4::vs[4]
Referenced by operator+(), and operator/=().