fcl::TriangleMotionBoundVisitor Class Reference
fcl::TriangleMotionBoundVisitor Class Reference
#include <hpp/fcl/ccd/motion_base.h>
Public Member Functions
TriangleMotionBoundVisitor (const Vec3f &a_, const Vec3f &b_, const Vec3f &c_, const Vec3f &n_)
virtual FCL_REAL visit (const MotionBase &) const
virtual FCL_REAL visit (const SplineMotion &motion) const
virtual FCL_REAL visit (const ScrewMotion &motion) const
virtual FCL_REAL visit (const InterpMotion &motion) const
virtual FCL_REAL visit (const TranslationMotion &motion) const
Protected Attributes
Vec3f a
Vec3f b
Vec3f c
Vec3f n
Constructor & Destructor Documentation
fcl::TriangleMotionBoundVisitor::TriangleMotionBoundVisitor (const Vec3f & a_, const Vec3f & b_, const Vec3f & c_, const Vec3f & n_) inline
Member Function Documentation
virtual FCL_REAL fcl::TriangleMotionBoundVisitor::visit (const MotionBase &) const inline virtual
Referenced by fcl::TranslationMotion::computeMotionBound(), fcl::SplineMotion::computeMotionBound(), fcl::ScrewMotion::computeMotionBound(), and fcl::InterpMotion::computeMotionBound().
virtual FCL_REAL fcl::TriangleMotionBoundVisitor::visit (const SplineMotion & motion) const virtual
virtual FCL_REAL fcl::TriangleMotionBoundVisitor::visit (const ScrewMotion & motion) const virtual
virtual FCL_REAL fcl::TriangleMotionBoundVisitor::visit (const InterpMotion & motion) const virtual
virtual FCL_REAL fcl::TriangleMotionBoundVisitor::visit (const TranslationMotion & motion) const virtual
Member Data Documentation
Vec3f fcl::TriangleMotionBoundVisitor::a protected
Vec3f fcl::TriangleMotionBoundVisitor::b protected
Vec3f fcl::TriangleMotionBoundVisitor::c protected
Vec3f fcl::TriangleMotionBoundVisitor::n protected