fcl::details::sse_meta_f12 Struct Reference
fcl::details::sse_meta_f12 Struct Reference
#include <hpp/fcl/simd/math_simd_details.h>
Public Types
typedef float meta_type
typedef sse_meta_f4 vector_type
Public Member Functions
sse_meta_f12 ()
sse_meta_f12 (float xx, float xy, float xz, float yx, float yy, float yz, float zx, float zy, float zz)
sse_meta_f12 (const sse_meta_f4 &x, const sse_meta_f4 &y, const sse_meta_f4 &z)
sse_meta_f12 (__m128 x, __m128 y, __m128 z)
void setValue (float xx, float xy, float xz, float yx, float yy, float yz, float zx, float zy, float zz)
void setIdentity ()
void setZero ()
void setColumn (const sse_meta_f4 &x, const sse_meta_f4 &y, const sse_meta_f4 &z)
void setColumn (__m128 x, __m128 y, __m128 z)
const sse_meta_f4 & getColumn (size_t i) const
sse_meta_f4 & getColumn (size_t i)
sse_meta_f4 getRow (size_t i) const
float operator() (size_t i, size_t j) const
float & operator() (size_t i, size_t j)
sse_meta_f4 operator* (const sse_meta_f4 &v) const
sse_meta_f12 operator* (const sse_meta_f12 &mat) const
sse_meta_f12 operator+ (const sse_meta_f12 &mat) const
sse_meta_f12 operator- (const sse_meta_f12 &mat) const
sse_meta_f12 operator+ (float t_) const
sse_meta_f12 operator- (float t_) const
sse_meta_f12 operator* (float t_) const
sse_meta_f12 operator/ (float t_) const
sse_meta_f12 & operator*= (const sse_meta_f12 &mat)
sse_meta_f12 & operator+= (const sse_meta_f12 &mat)
sse_meta_f12 & operator-= (const sse_meta_f12 &mat)
sse_meta_f12 & operator+= (float t_)
sse_meta_f12 & operator-= (float t_)
sse_meta_f12 & operator*= (float t_)
sse_meta_f12 & operator/= (float t_)
sse_meta_f12 & inverse ()
sse_meta_f12 & transpose ()
sse_meta_f12 & abs ()
float determinant () const
sse_meta_f12 transposeTimes (const sse_meta_f12 &other) const
sse_meta_f12 timesTranspose (const sse_meta_f12 &m) const
sse_meta_f4 transposeTimes (const sse_meta_f4 &v) const
float transposeDot (size_t i, const sse_meta_f4 &v) const
float dot (size_t i, const sse_meta_f4 &v) const
Public Attributes
sse_meta_f4 c [3]
Member Typedef Documentation
typedef float fcl::details::sse_meta_f12::meta_type
typedef sse_meta_f4 fcl::details::sse_meta_f12::vector_type
Constructor & Destructor Documentation
fcl::details::sse_meta_f12::sse_meta_f12 () inline
References setZero().
Referenced by operator*(), operator+(), operator-(), operator/(), and transposeTimes().
fcl::details::sse_meta_f12::sse_meta_f12 (float xx, float xy, float xz, float yx, float yy, float yz, float zx, float zy, float zz) inline
References setValue().
fcl::details::sse_meta_f12::sse_meta_f12 (const sse_meta_f4 & x, const sse_meta_f4 & y, const sse_meta_f4 & z) inline
References setColumn().
fcl::details::sse_meta_f12::sse_meta_f12 (__m128 x, __m128 y, __m128 z) inline
References setColumn().
Member Function Documentation
sse_meta_f12& fcl::details::sse_meta_f12::abs () inline
References fcl::details::abs().
float fcl::details::sse_meta_f12::determinant () const inline
References fcl::details::cross_prod(), and fcl::details::dot_prod3().
float fcl::details::sse_meta_f12::dot (size_t i, const sse_meta_f4 & v) const inline
const sse_meta_f4& fcl::details::sse_meta_f12::getColumn (size_t i) const inline
Referenced by fcl::details::abs(), fcl::details::inverse(), and fcl::details::transpose().
sse_meta_f4& fcl::details::sse_meta_f12::getColumn (size_t i) inline
sse_meta_f4 fcl::details::sse_meta_f12::getRow (size_t i) const inline
References sse_meta_f4().
sse_meta_f12& fcl::details::sse_meta_f12::inverse () inline
References fcl::details::inverse(), and setColumn().
float fcl::details::sse_meta_f12::operator() (size_t i, size_t j) const inline
float& fcl::details::sse_meta_f12::operator() (size_t i, size_t j) inline
sse_meta_f4 fcl::details::sse_meta_f12::operator* (const sse_meta_f4 & v) const inline
References sse_meta_f4(), and vec_splat.
sse_meta_f12 fcl::details::sse_meta_f12::operator* (const sse_meta_f12 & mat) const inline
References c, and sse_meta_f12().
sse_meta_f12 fcl::details::sse_meta_f12::operator* (float t_) const inline
References sse_meta_f12().
sse_meta_f12& fcl::details::sse_meta_f12::operator*= (const sse_meta_f12 & mat) inline
References c, and setColumn().
sse_meta_f12& fcl::details::sse_meta_f12::operator*= (float t_) inline
sse_meta_f12 fcl::details::sse_meta_f12::operator+ (const sse_meta_f12 & mat) const inline
References c, and sse_meta_f12().
sse_meta_f12 fcl::details::sse_meta_f12::operator+ (float t_) const inline
References sse_meta_f12().
sse_meta_f12& fcl::details::sse_meta_f12::operator+= (const sse_meta_f12 & mat) inline
References c.
sse_meta_f12& fcl::details::sse_meta_f12::operator+= (float t_) inline
sse_meta_f12 fcl::details::sse_meta_f12::operator- (const sse_meta_f12 & mat) const inline
References c, and sse_meta_f12().
sse_meta_f12 fcl::details::sse_meta_f12::operator- (float t_) const inline
References sse_meta_f12().
sse_meta_f12& fcl::details::sse_meta_f12::operator-= (const sse_meta_f12 & mat) inline
References c.
sse_meta_f12& fcl::details::sse_meta_f12::operator-= (float t_) inline
sse_meta_f12 fcl::details::sse_meta_f12::operator/ (float t_) const inline
References sse_meta_f12().
sse_meta_f12& fcl::details::sse_meta_f12::operator/= (float t_) inline
void fcl::details::sse_meta_f12::setColumn (const sse_meta_f4 & x, const sse_meta_f4 & y, const sse_meta_f4 & z) inline
Referenced by inverse(), operator*=(), sse_meta_f12(), and transpose().
void fcl::details::sse_meta_f12::setColumn (__m128 x, __m128 y, __m128 z) inline
void fcl::details::sse_meta_f12::setIdentity () inline
void fcl::details::sse_meta_f12::setValue (float xx, float xy, float xz, float yx, float yy, float yz, float zx, float zy, float zz) inline
Referenced by sse_meta_f12().
void fcl::details::sse_meta_f12::setZero () inline
Referenced by sse_meta_f12().
sse_meta_f12 fcl::details::sse_meta_f12::timesTranspose (const sse_meta_f12 & m) const inline
References transpose().
sse_meta_f12& fcl::details::sse_meta_f12::transpose () inline
References setColumn(), and fcl::details::transpose().
Referenced by timesTranspose().
float fcl::details::sse_meta_f12::transposeDot (size_t i, const sse_meta_f4 & v) const inline
References fcl::details::dot_prod3().
sse_meta_f12 fcl::details::sse_meta_f12::transposeTimes (const sse_meta_f12 & other) const inline
References c, fcl::details::dot_prod3(), and sse_meta_f12().
sse_meta_f4 fcl::details::sse_meta_f12::transposeTimes (const sse_meta_f4 & v) const inline
References fcl::details::dot_prod3(), and sse_meta_f4().
Member Data Documentation
sse_meta_f4 fcl::details::sse_meta_f12::c[3]
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), and transposeTimes().