fcl::ShapeMeshConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver > Class Template Reference
fcl::ShapeMeshConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver > Class Template Reference
#include <hpp/fcl/traversal/traversal_node_bvh_shape.h>
Public Member Functions
ShapeMeshConservativeAdvancementTraversalNodeRSS (FCL_REAL w_=1)
FCL_REAL BVTesting (int b1, int b2) const
BV test between b1 and b2.
void leafTesting (int b1, int b2) const
Leaf test between node b1 and b2, if they are both leafs.
bool canStop (FCL_REAL c) const
Check whether the traversal can stop.
Public Member Functions inherited from fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >
ShapeMeshConservativeAdvancementTraversalNode (FCL_REAL w_=1)
FCL_REAL BVTesting (int b1, int b2) const
BV culling test in one BVTT node.
void leafTesting (int b1, int b2) const
Conservative advancement testing between leaves (one triangle and one shape)
bool canStop (FCL_REAL c) const
Whether the traversal process can stop early.
Public Member Functions inherited from fcl::ShapeMeshDistanceTraversalNode< S, RSS, NarrowPhaseSolver >
ShapeMeshDistanceTraversalNode ()
Public Member Functions inherited from fcl::ShapeBVHDistanceTraversalNode< S, RSS >
ShapeBVHDistanceTraversalNode ()
bool isSecondNodeLeaf (int b) const
Whether the BV node in the second BVH tree is leaf.
int getSecondLeftChild (int b) const
Obtain the left child of BV node in the second BVH.
int getSecondRightChild (int b) const
Obtain the right child of BV node in the second BVH.
Public Member Functions inherited from fcl::DistanceTraversalNodeBase
DistanceTraversalNodeBase ()
virtual ~DistanceTraversalNodeBase ()
void enableStatistics (bool enable)
Whether store some statistics information during traversal.
Public Member Functions inherited from fcl::TraversalNodeBase
virtual ~TraversalNodeBase ()
virtual void preprocess ()
virtual void postprocess ()
virtual bool isFirstNodeLeaf (int b) const
Whether b is a leaf node in the first BVH tree.
virtual bool firstOverSecond (int b1, int b2) const
Traverse the subtree of the node in the first tree first.
virtual int getFirstLeftChild (int b) const
Get the left child of the node b in the first tree.
virtual int getFirstRightChild (int b) const
Get the right child of the node b in the first tree.
Additional Inherited Members
Public Attributes inherited from fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >
FCL_REAL min_distance
Vec3f closest_p1
Vec3f closest_p2
int last_tri_id
FCL_REAL w
CA controlling variable: early stop for the early iterations of CA.
FCL_REAL toc
The time from beginning point.
FCL_REAL t_err
FCL_REAL delta_t
The delta_t each step.
const MotionBase * motion1
Motions for the two objects in query.
const MotionBase * motion2
std::vector< ConservativeAdvancementStackData > stack
Public Attributes inherited from fcl::ShapeMeshDistanceTraversalNode< S, RSS, NarrowPhaseSolver >
Vec3f * vertices
Triangle * tri_indices
FCL_REAL rel_err
FCL_REAL abs_err
const NarrowPhaseSolver * nsolver
Public Attributes inherited from fcl::ShapeBVHDistanceTraversalNode< S, RSS >
const S * model1
const BVHModel< RSS > * model2
RSS model1_bv
int num_bv_tests
int num_leaf_tests
FCL_REAL query_time_seconds
Public Attributes inherited from fcl::DistanceTraversalNodeBase
DistanceRequest request
request setting for distance
DistanceResult * result
distance result kept during the traversal iteration
bool enable_statistics
Whether stores statistics.
Public Attributes inherited from fcl::TraversalNodeBase
Transform3f tf1
configuation of first object
Transform3f tf2
configuration of second object
Constructor & Destructor Documentation
template<typename S, typename NarrowPhaseSolver> fcl::ShapeMeshConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver >::ShapeMeshConservativeAdvancementTraversalNodeRSS (FCL_REAL w_ = 1) inline
Member Function Documentation
template<typename S, typename NarrowPhaseSolver> FCL_REAL fcl::ShapeMeshConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting (int b1, int b2) const inline virtual
BV test between b1 and b2.
Reimplemented from fcl::DistanceTraversalNodeBase.
References d(), fcl::distance(), fcl::ShapeBVHDistanceTraversalNode< S, RSS >::model1_bv, fcl::ShapeBVHDistanceTraversalNode< S, RSS >::num_bv_tests, and fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::stack.
template<typename S, typename NarrowPhaseSolver> bool fcl::ShapeMeshConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver >::canStop (FCL_REAL c) const inline virtual
Check whether the traversal can stop.
Reimplemented from fcl::DistanceTraversalNodeBase.
References fcl::ShapeMeshDistanceTraversalNode< S, RSS, NarrowPhaseSolver >::abs_err, fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::delta_t, fcl::details::meshShapeConservativeAdvancementOrientedNodeCanStop(), fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::min_distance, fcl::ShapeBVHDistanceTraversalNode< S, RSS >::model1_bv, fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::motion1, fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::motion2, fcl::ShapeMeshDistanceTraversalNode< S, RSS, NarrowPhaseSolver >::rel_err, fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::stack, and fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::w.
template<typename S, typename NarrowPhaseSolver> void fcl::ShapeMeshConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver >::leafTesting (int b1, int b2) const inline virtual
Leaf test between node b1 and b2, if they are both leafs.
Implements fcl::DistanceTraversalNodeBase.
References fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::delta_t, fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::last_tri_id, fcl::details::meshShapeConservativeAdvancementOrientedNodeLeafTesting(), fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::min_distance, fcl::ShapeBVHDistanceTraversalNode< S, RSS >::model1_bv, fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::motion1, and fcl::ShapeMeshConservativeAdvancementTraversalNode< S, RSS, NarrowPhaseSolver >::motion2.