fcl::Vec3fX< T > Class Template Reference
fcl::Vec3fX< T > Class Template Reference
Vector3 class wrapper. The core data is in the template parameter class.
#include <hpp/fcl/math/vec_3fx.h>
Public Types
typedef T::meta_type U
Public Member Functions
Vec3fX ()
Vec3fX (const Vec3fX &other)
Vec3fX (U x, U y, U z)
create Vector (x, y, z)
Vec3fX (U x)
create vector (x, x, x)
Vec3fX (const T &data_)
create vector using the internal data type
U operator[] (size_t i) const
U & operator[] (size_t i)
Vec3fX operator+ (const Vec3fX &other) const
Vec3fX operator- (const Vec3fX &other) const
Vec3fX operator* (const Vec3fX &other) const
Vec3fX operator/ (const Vec3fX &other) const
Vec3fX & operator+= (const Vec3fX &other)
Vec3fX & operator-= (const Vec3fX &other)
Vec3fX & operator*= (const Vec3fX &other)
Vec3fX & operator/= (const Vec3fX &other)
Vec3fX operator+ (U t) const
Vec3fX operator- (U t) const
Vec3fX operator* (U t) const
Vec3fX operator/ (U t) const
Vec3fX & operator+= (U t)
Vec3fX & operator-= (U t)
Vec3fX & operator*= (U t)
Vec3fX & operator/= (U t)
Vec3fX operator- () const
Vec3fX cross (const Vec3fX &other) const
U dot (const Vec3fX &other) const
Vec3fX & normalize ()
Vec3fX & normalize (bool *signal)
Vec3fX & abs ()
U length () const
U norm () const
U sqrLength () const
U squaredNorm () const
void setValue (U x, U y, U z)
void setValue (U x)
void setZero ()
bool equal (const Vec3fX &other, U epsilon=std::numeric_limits< U >::epsilon()*100) const
Vec3fX< T > & negate ()
bool operator== (const Vec3fX &other) const
bool operator!= (const Vec3fX &other) const
Vec3fX< T > & ubound (const Vec3fX< T > &u)
Vec3fX< T > & lbound (const Vec3fX< T > &l)
bool isZero () const
Public Attributes
T data
interval vector3 data
Detailed Description
template<typename T>
class fcl::Vec3fX< T >
Vector3 class wrapper. The core data is in the template parameter class.
Member Typedef Documentation
template<typename T> typedef T::meta_type fcl::Vec3fX< T >::U
Constructor & Destructor Documentation
template<typename T> fcl::Vec3fX< T >::Vec3fX () inline
Referenced by fcl::Vec3fX< T >::cross(), fcl::Vec3fX< T >::operator*(), fcl::Vec3fX< T >::operator+(), fcl::Vec3fX< T >::operator-(), and fcl::Vec3fX< T >::operator/().
template<typename T> fcl::Vec3fX< T >::Vec3fX (const Vec3fX< T > & other) inline
template<typename T> fcl::Vec3fX< T >::Vec3fX (U x, U y, U z) inline
create Vector (x, y, z)
template<typename T> fcl::Vec3fX< T >::Vec3fX (U x) inline
create vector (x, x, x)
template<typename T> fcl::Vec3fX< T >::Vec3fX (const T & data_) inline
create vector using the internal data type
Member Function Documentation
template<typename T> Vec3fX& fcl::Vec3fX< T >::abs () inline
template<typename T> Vec3fX fcl::Vec3fX< T >::cross (const Vec3fX< T > & other) const inline
References fcl::details::cross_prod(), fcl::Vec3fX< T >::data, and fcl::Vec3fX< T >::Vec3fX().
Referenced by fcl::triple().
template<typename T> U fcl::Vec3fX< T >::dot (const Vec3fX< T > & other) const inline
References fcl::Vec3fX< T >::data, and fcl::details::dot_prod3().
Referenced by fcl::quadraticForm(), and fcl::triple().
template<typename T> bool fcl::Vec3fX< T >::equal (const Vec3fX< T > & other, U epsilon = std::numeric_limits<U>::epsilon() * 100) const inline
References fcl::Vec3fX< T >::data, and fcl::details::equal().
Referenced by fcl::Vec3fX< T >::operator==().
template<typename T> bool fcl::Vec3fX< T >::isZero () const inline
template<typename T> Vec3fX<T>& fcl::Vec3fX< T >::lbound (const Vec3fX< T > & l) inline
References fcl::Vec3fX< T >::data.
template<typename T> U fcl::Vec3fX< T >::length () const inline
References fcl::details::dot_prod3().
template<typename T> Vec3fX<T>& fcl::Vec3fX< T >::negate () inline
template<typename T> U fcl::Vec3fX< T >::norm () const inline
References fcl::details::dot_prod3().
template<typename T> Vec3fX& fcl::Vec3fX< T >::normalize () inline
References fcl::details::dot_prod3().
template<typename T> Vec3fX& fcl::Vec3fX< T >::normalize (bool * signal) inline
References fcl::details::dot_prod3().
template<typename T> bool fcl::Vec3fX< T >::operator!= (const Vec3fX< T > & other) const inline
template<typename T> Vec3fX fcl::Vec3fX< T >::operator* (const Vec3fX< T > & other) const inline
References fcl::Vec3fX< T >::data, and fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX fcl::Vec3fX< T >::operator* (U t) const inline
References fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator*= (const Vec3fX< T > & other) inline
References fcl::Vec3fX< T >::data.
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator*= (U t) inline
template<typename T> Vec3fX fcl::Vec3fX< T >::operator+ (const Vec3fX< T > & other) const inline
References fcl::Vec3fX< T >::data, and fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX fcl::Vec3fX< T >::operator+ (U t) const inline
References fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator+= (const Vec3fX< T > & other) inline
References fcl::Vec3fX< T >::data.
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator+= (U t) inline
template<typename T> Vec3fX fcl::Vec3fX< T >::operator- (const Vec3fX< T > & other) const inline
References fcl::Vec3fX< T >::data, and fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX fcl::Vec3fX< T >::operator- (U t) const inline
References fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX fcl::Vec3fX< T >::operator- () const inline
References fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator-= (const Vec3fX< T > & other) inline
References fcl::Vec3fX< T >::data.
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator-= (U t) inline
template<typename T> Vec3fX fcl::Vec3fX< T >::operator/ (const Vec3fX< T > & other) const inline
References fcl::Vec3fX< T >::data, and fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX fcl::Vec3fX< T >::operator/ (U t) const inline
References fcl::Vec3fX< T >::Vec3fX().
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator/= (const Vec3fX< T > & other) inline
References fcl::Vec3fX< T >::data.
template<typename T> Vec3fX& fcl::Vec3fX< T >::operator/= (U t) inline
template<typename T> bool fcl::Vec3fX< T >::operator== (const Vec3fX< T > & other) const inline
References fcl::Vec3fX< T >::equal().
template<typename T> U fcl::Vec3fX< T >::operator[] (size_t i) const inline
template<typename T> U& fcl::Vec3fX< T >::operator[] (size_t i) inline
template<typename T> void fcl::Vec3fX< T >::setValue (U x, U y, U z) inline
Referenced by fcl::eigen().
template<typename T> void fcl::Vec3fX< T >::setValue (U x) inline
template<typename T> void fcl::Vec3fX< T >::setZero () inline
template<typename T> U fcl::Vec3fX< T >::sqrLength () const inline
References fcl::details::dot_prod3().
template<typename T> U fcl::Vec3fX< T >::squaredNorm () const inline
References fcl::details::dot_prod3().
template<typename T> Vec3fX<T>& fcl::Vec3fX< T >::ubound (const Vec3fX< T > & u) inline
References fcl::Vec3fX< T >::data.
Member Data Documentation
template<typename T> T fcl::Vec3fX< T >::data
interval vector3 data
Referenced by fcl::abs(), fcl::Vec3fX< T >::cross(), fcl::Vec3fX< T >::dot(), fcl::Matrix3fX< T >::dot(), fcl::Matrix3fX< T >::dotX(), fcl::Matrix3fX< T >::dotY(), fcl::Matrix3fX< T >::dotZ(), fcl::Vec3fX< T >::equal(), fcl::Vec3fX< T >::lbound(), fcl::max(), fcl::min(), fcl::normalize(), fcl::Vec3fX< T >::operator*(), fcl::Matrix3fX< T >::operator*(), fcl::operator*(), fcl::Vec3fX< T >::operator*=(), fcl::Vec3fX< T >::operator+(), fcl::Vec3fX< T >::operator+=(), fcl::Vec3fX< T >::operator-(), fcl::Vec3fX< T >::operator-=(), fcl::Vec3fX< T >::operator/(), fcl::Vec3fX< T >::operator/=(), fcl::Matrix3fX< T >::transposeDot(), fcl::Matrix3fX< T >::transposeDotX(), fcl::Matrix3fX< T >::transposeDotY(), fcl::Matrix3fX< T >::transposeDotZ(), fcl::Matrix3fX< T >::transposeTimes(), and fcl::Vec3fX< T >::ubound().