fcl::TimeInterval Struct Reference
fcl::TimeInterval Struct Reference
#include <hpp/fcl/ccd/taylor_model.h>
Public Member Functions
TimeInterval ()
TimeInterval (FCL_REAL l, FCL_REAL r)
void setValue (FCL_REAL l, FCL_REAL r)
Public Attributes
Interval t_
time interval and different powers
Interval t2_
Interval t3_
Interval t4_
Interval t5_
Interval t6_
Constructor & Destructor Documentation
fcl::TimeInterval::TimeInterval () inline
fcl::TimeInterval::TimeInterval (FCL_REAL l, FCL_REAL r) inline
References setValue().
Member Function Documentation
void fcl::TimeInterval::setValue (FCL_REAL l, FCL_REAL r) inline
References fcl::Interval::setValue().
Referenced by TimeInterval().
Member Data Documentation
Interval fcl::TimeInterval::t2_
Interval fcl::TimeInterval::t3_
Interval fcl::TimeInterval::t4_
Interval fcl::TimeInterval::t5_
Interval fcl::TimeInterval::t6_
Interval fcl::TimeInterval::t_
time interval and different powers