fcl::SpatialHash Struct Reference
fcl::SpatialHash Struct Reference
Spatial hash function: hash an AABB to a set of integer values.
#include <hpp/fcl/broadphase/broadphase_spatialhash.h>
Public Member Functions
SpatialHash (const AABB &scene_limit_, FCL_REAL cell_size_)
std::vector< unsigned int > operator() (const AABB &aabb) const
Detailed Description
Spatial hash function: hash an AABB to a set of integer values.
Constructor & Destructor Documentation
fcl::SpatialHash::SpatialHash (const AABB & scene_limit_, FCL_REAL cell_size_) inline
References fcl::AABB::depth(), fcl::AABB::height(), and fcl::AABB::width().
Member Function Documentation
std::vector<unsigned int> fcl::SpatialHash::operator() (const AABB & aabb) const inline
References fcl::AABB::max_, and fcl::AABB::min_.