fcl::details::sse_meta_d4 Struct Reference
fcl::details::sse_meta_d4 Struct Reference
#include <hpp/fcl/simd/math_simd_details.h>
Public Types
typedef double meta_type
Public Member Functions
sse_meta_d4 ()
sse_meta_d4 (double x)
sse_meta_d4 (double *px)
sse_meta_d4 (__m128d x, __m128d y)
sse_meta_d4 (double x, double y, double z, double w=0)
void setValue (double x, double y, double z, double w=0)
void setValue (double x)
void setValue (__m128d x, __m128d y)
void negate ()
sse_meta_d4 & ubound (const sse_meta_d4 &u)
sse_meta_d4 & lbound (const sse_meta_d4 &l)
void * operator new[] (size_t n)
void operator delete[] (void *x)
double operator[] (size_t i) const
double & operator[] (size_t i)
sse_meta_d4 operator+ (const sse_meta_d4 &other) const
sse_meta_d4 operator- (const sse_meta_d4 &other) const
sse_meta_d4 operator* (const sse_meta_d4 &other) const
sse_meta_d4 operator/ (const sse_meta_d4 &other) const
sse_meta_d4 & operator+= (const sse_meta_d4 &other)
sse_meta_d4 & operator-= (const sse_meta_d4 &other)
sse_meta_d4 & operator*= (const sse_meta_d4 &other)
sse_meta_d4 & operator/= (const sse_meta_d4 &other)
sse_meta_d4 operator+ (double t) const
sse_meta_d4 operator- (double t) const
sse_meta_d4 operator* (double t) const
sse_meta_d4 operator/ (double t) const
sse_meta_d4 & operator+= (double t)
sse_meta_d4 & operator-= (double t)
sse_meta_d4 & operator*= (double t)
sse_meta_d4 & operator/= (double t)
sse_meta_d4 operator- () const
Public Attributes
union {
double vs [4]
__m128d v [2]
};
Member Typedef Documentation
typedef double fcl::details::sse_meta_d4::meta_type
Constructor & Destructor Documentation
fcl::details::sse_meta_d4::sse_meta_d4 () inline
References setValue().
Referenced by operator*(), operator+(), operator-(), and operator/().
fcl::details::sse_meta_d4::sse_meta_d4 (double x) inline
References setValue().
fcl::details::sse_meta_d4::sse_meta_d4 (double * px) inline
fcl::details::sse_meta_d4::sse_meta_d4 (__m128d x, __m128d y) inline
fcl::details::sse_meta_d4::sse_meta_d4 (double x, double y, double z, double w = 0) inline
Member Function Documentation
sse_meta_d4& fcl::details::sse_meta_d4::lbound (const sse_meta_d4 & l) inline
References v.
void fcl::details::sse_meta_d4::negate () inline
void fcl::details::sse_meta_d4::operator delete[] (void * x) inline
void* fcl::details::sse_meta_d4::operator new[] (size_t n) inline
sse_meta_d4 fcl::details::sse_meta_d4::operator* (const sse_meta_d4 & other) const inline
References sse_meta_d4(), and v.
sse_meta_d4 fcl::details::sse_meta_d4::operator* (double t) const inline
References d(), and sse_meta_d4().
sse_meta_d4& fcl::details::sse_meta_d4::operator*= (const sse_meta_d4 & other) inline
References v.
sse_meta_d4& fcl::details::sse_meta_d4::operator*= (double t) inline
References d().
sse_meta_d4 fcl::details::sse_meta_d4::operator+ (const sse_meta_d4 & other) const inline
References sse_meta_d4(), and v.
sse_meta_d4 fcl::details::sse_meta_d4::operator+ (double t) const inline
References d(), and sse_meta_d4().
sse_meta_d4& fcl::details::sse_meta_d4::operator+= (const sse_meta_d4 & other) inline
References v.
sse_meta_d4& fcl::details::sse_meta_d4::operator+= (double t) inline
References d().
sse_meta_d4 fcl::details::sse_meta_d4::operator- (const sse_meta_d4 & other) const inline
References sse_meta_d4(), and v.
sse_meta_d4 fcl::details::sse_meta_d4::operator- (double t) const inline
References d(), and sse_meta_d4().
sse_meta_d4 fcl::details::sse_meta_d4::operator- () const inline
References fcl::details::__attribute__, and sse_meta_d4().
sse_meta_d4& fcl::details::sse_meta_d4::operator-= (const sse_meta_d4 & other) inline
References v.
sse_meta_d4& fcl::details::sse_meta_d4::operator-= (double t) inline
References d().
sse_meta_d4 fcl::details::sse_meta_d4::operator/ (const sse_meta_d4 & other) const inline
References sse_meta_d4(), and v.
sse_meta_d4 fcl::details::sse_meta_d4::operator/ (double t) const inline
References d(), and sse_meta_d4().
sse_meta_d4& fcl::details::sse_meta_d4::operator/= (const sse_meta_d4 & other) inline
References v.
sse_meta_d4& fcl::details::sse_meta_d4::operator/= (double t) inline
References d().
double fcl::details::sse_meta_d4::operator[] (size_t i) const inline
References vs.
double& fcl::details::sse_meta_d4::operator[] (size_t i) inline
References vs.
void fcl::details::sse_meta_d4::setValue (double x, double y, double z, double w = 0) inline
Referenced by sse_meta_d4().
void fcl::details::sse_meta_d4::setValue (double x) inline
void fcl::details::sse_meta_d4::setValue (__m128d x, __m128d y) inline
sse_meta_d4& fcl::details::sse_meta_d4::ubound (const sse_meta_d4 & u) inline
References v.
Member Data Documentation
union { ... }
__m128d fcl::details::sse_meta_d4::v[2]
Referenced by fcl::details::abs(), fcl::details::cross_prod(), fcl::details::dot_prod3(), fcl::details::dot_prod4(), fcl::details::equal(), lbound(), fcl::details::max(), fcl::details::min(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), and ubound().
double fcl::details::sse_meta_d4::vs[4]
Referenced by operator[]().