fcl::details::Vec3Data< T > Struct Template Reference
fcl::details::Vec3Data< T > Struct Template Reference
#include <hpp/fcl/math/math_details.h>
Public Types
typedef T meta_type
Public Member Functions
Vec3Data ()
Vec3Data (T x)
Vec3Data (T *x)
Vec3Data (T x, T y, T z)
void setValue (T x, T y, T z)
void setValue (T x)
void negate ()
Vec3Data< T > & ubound (const Vec3Data< T > &u)
Vec3Data< T > & lbound (const Vec3Data< T > &l)
T operator[] (size_t i) const
T & operator[] (size_t i)
Vec3Data< T > operator+ (const Vec3Data< T > &other) const
Vec3Data< T > operator- (const Vec3Data< T > &other) const
Vec3Data< T > operator* (const Vec3Data< T > &other) const
Vec3Data< T > operator/ (const Vec3Data< T > &other) const
Vec3Data< T > & operator+= (const Vec3Data< T > &other)
Vec3Data< T > & operator-= (const Vec3Data< T > &other)
Vec3Data< T > & operator*= (const Vec3Data< T > &other)
Vec3Data< T > & operator/= (const Vec3Data< T > &other)
Vec3Data< T > operator+ (T t) const
Vec3Data< T > operator- (T t) const
Vec3Data< T > operator* (T t) const
Vec3Data< T > operator/ (T t) const
Vec3Data< T > & operator+= (T t)
Vec3Data< T > & operator-= (T t)
Vec3Data< T > & operator*= (T t)
Vec3Data< T > & operator/= (T t)
Vec3Data< T > operator- () const
Public Attributes
T vs [3]
Member Typedef Documentation
template<typename T> typedef T fcl::details::Vec3Data< T >::meta_type
Constructor & Destructor Documentation
template<typename T> fcl::details::Vec3Data< T >::Vec3Data () inline
References fcl::details::Vec3Data< T >::setValue().
template<typename T> fcl::details::Vec3Data< T >::Vec3Data (T x) inline
References fcl::details::Vec3Data< T >::setValue().
template<typename T> fcl::details::Vec3Data< T >::Vec3Data (T * x) inline
template<typename T> fcl::details::Vec3Data< T >::Vec3Data (T x, T y, T z) inline
References fcl::details::Vec3Data< T >::setValue().
Member Function Documentation
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::lbound (const Vec3Data< T > & l) inline
References fcl::details::max(), and fcl::details::Vec3Data< T >::vs.
template<typename T> void fcl::details::Vec3Data< T >::negate () inline
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator* (const Vec3Data< T > & other) const inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator* (T t) const inline
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator*= (const Vec3Data< T > & other) inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator*= (T t) inline
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator+ (const Vec3Data< T > & other) const inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator+ (T t) const inline
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator+= (const Vec3Data< T > & other) inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator+= (T t) inline
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator- (const Vec3Data< T > & other) const inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator- (T t) const inline
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator- () const inline
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator-= (const Vec3Data< T > & other) inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator-= (T t) inline
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator/ (const Vec3Data< T > & other) const inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T> fcl::details::Vec3Data< T >::operator/ (T t) const inline
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator/= (const Vec3Data< T > & other) inline
References fcl::details::Vec3Data< T >::vs.
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::operator/= (T t) inline
template<typename T> T fcl::details::Vec3Data< T >::operator[] (size_t i) const inline
template<typename T> T& fcl::details::Vec3Data< T >::operator[] (size_t i) inline
template<typename T> void fcl::details::Vec3Data< T >::setValue (T x, T y, T z) inline
Referenced by fcl::details::Matrix3Data< T >::operator*=(), fcl::details::Matrix3Data< T >::setValue(), and fcl::details::Vec3Data< T >::Vec3Data().
template<typename T> void fcl::details::Vec3Data< T >::setValue (T x) inline
template<typename T> Vec3Data<T>& fcl::details::Vec3Data< T >::ubound (const Vec3Data< T > & u) inline
References fcl::details::min(), and fcl::details::Vec3Data< T >::vs.
Member Data Documentation
template<typename T> T fcl::details::Vec3Data< T >::vs[3]
Referenced by fcl::details::abs(), fcl::details::cross_prod(), fcl::details::dot_prod3(), fcl::details::equal(), fcl::details::Vec3Data< T >::lbound(), fcl::details::max(), fcl::details::min(), fcl::details::Vec3Data< T >::operator*(), fcl::details::Vec3Data< T >::operator*=(), fcl::details::Vec3Data< T >::operator+(), fcl::details::Vec3Data< T >::operator+=(), fcl::details::Vec3Data< T >::operator-(), fcl::details::Vec3Data< T >::operator-=(), fcl::details::Vec3Data< T >::operator/(), fcl::details::Vec3Data< T >::operator/=(), and fcl::details::Vec3Data< T >::ubound().