fcl::ShapeMeshCollisionTraversalNodeOBBRSS< S, NarrowPhaseSolver > Class Template Reference
fcl::ShapeMeshCollisionTraversalNodeOBBRSS< S, NarrowPhaseSolver > Class Template Reference
#include <hpp/fcl/traversal/traversal_node_bvh_shape.h>
Public Member Functions
ShapeMeshCollisionTraversalNodeOBBRSS ()
bool BVTesting (int b1, int b2) const
BV test between b1 and b2.
bool BVTesting (int b1, int b2, FCL_REAL &sqrDistLowerBound) const
BV test between b1 and b2.
void leafTesting (int b1, int b2, FCL_REAL &sqrDistLowerBound) const
Leaf test between node b1 and b2, if they are both leafs.
Public Member Functions inherited from fcl::ShapeMeshCollisionTraversalNode< S, OBBRSS, NarrowPhaseSolver >
ShapeMeshCollisionTraversalNode ()
void leafTesting (int b1, int b2) const
Intersection testing between leaves (one shape and one triangle)
bool canStop () const
Whether the traversal process can stop early.
Public Member Functions inherited from fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >
ShapeBVHCollisionTraversalNode ()
bool firstOverSecond (int, int) const
Alway extend the second model, which is a BVH model.
bool isSecondNodeLeaf (int b) const
Whether the BV node in the second BVH tree is leaf.
int getSecondLeftChild (int b) const
Obtain the left child of BV node in the second BVH.
int getSecondRightChild (int b) const
Obtain the right child of BV node in the second BVH.
bool BVTesting (int b1, int b2) const
BV test between b1 and b2.
bool BVTesting (int b1, int b2, FCL_REAL &sqrDistLowerBound) const
BV test between b1 and b2.
Public Member Functions inherited from fcl::CollisionTraversalNodeBase
CollisionTraversalNodeBase (bool enable_distance_lower_bound_=false)
virtual ~CollisionTraversalNodeBase ()
void enableStatistics (bool enable)
Whether store some statistics information during traversal.
Public Member Functions inherited from fcl::TraversalNodeBase
virtual ~TraversalNodeBase ()
virtual void preprocess ()
virtual void postprocess ()
virtual bool isFirstNodeLeaf (int b) const
Whether b is a leaf node in the first BVH tree.
virtual int getFirstLeftChild (int b) const
Get the left child of the node b in the first tree.
virtual int getFirstRightChild (int b) const
Get the right child of the node b in the first tree.
Additional Inherited Members
Public Attributes inherited from fcl::ShapeMeshCollisionTraversalNode< S, OBBRSS, NarrowPhaseSolver >
Vec3f * vertices
Triangle * tri_indices
FCL_REAL cost_density
const NarrowPhaseSolver * nsolver
Public Attributes inherited from fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >
const S * model1
const BVHModel< OBBRSS > * model2
OBBRSS model1_bv
int num_bv_tests
int num_leaf_tests
FCL_REAL query_time_seconds
Public Attributes inherited from fcl::CollisionTraversalNodeBase
CollisionRequest request
request setting for collision
CollisionResult * result
collision result kept during the traversal iteration
bool enable_statistics
Whether stores statistics.
bool enable_distance_lower_bound
Whether to compute a lower bound on distance between bounding volumes.
Public Attributes inherited from fcl::TraversalNodeBase
Transform3f tf1
configuation of first object
Transform3f tf2
configuration of second object
Constructor & Destructor Documentation
template<typename S, typename NarrowPhaseSolver> fcl::ShapeMeshCollisionTraversalNodeOBBRSS< S, NarrowPhaseSolver >::ShapeMeshCollisionTraversalNodeOBBRSS () inline
Member Function Documentation
template<typename S, typename NarrowPhaseSolver> bool fcl::ShapeMeshCollisionTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting (int b1, int b2) const inline virtual
BV test between b1 and b2.
Implements fcl::CollisionTraversalNodeBase.
References fcl::BVNode< BV >::bv, fcl::CollisionTraversalNodeBase::enable_statistics, fcl::BVHModel< BV >::getBV(), fcl::Transform3f::getRotation(), fcl::Transform3f::getTranslation(), fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::model1_bv, fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::model2, fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::num_bv_tests, fcl::overlap(), and fcl::TraversalNodeBase::tf2.
template<typename S, typename NarrowPhaseSolver> bool fcl::ShapeMeshCollisionTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting (int b1, int b2, FCL_REAL & sqrDistLowerBound) const inline virtual
BV test between b1 and b2.
Parameters
b1,b2 Bounding volumes to test,
Return values
sqrDistLowerBound square of a lower bound of the minimal distance between bounding volumes.
Implements fcl::CollisionTraversalNodeBase.
References fcl::BVNode< BV >::bv, fcl::CollisionTraversalNodeBase::enable_statistics, fcl::BVHModel< BV >::getBV(), fcl::Transform3f::getRotation(), fcl::Transform3f::getTranslation(), fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::model1_bv, fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::model2, fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::num_bv_tests, fcl::overlap(), and fcl::TraversalNodeBase::tf2.
template<typename S, typename NarrowPhaseSolver> void fcl::ShapeMeshCollisionTraversalNodeOBBRSS< S, NarrowPhaseSolver >::leafTesting (int , int , FCL_REAL &) const inline virtual
Leaf test between node b1 and b2, if they are both leafs.
Reimplemented from fcl::CollisionTraversalNodeBase.
References fcl::ShapeMeshCollisionTraversalNode< S, OBBRSS, NarrowPhaseSolver >::cost_density, fcl::CollisionTraversalNodeBase::enable_statistics, fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::model1, fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::model2, fcl::ShapeMeshCollisionTraversalNode< S, OBBRSS, NarrowPhaseSolver >::nsolver, fcl::ShapeBVHCollisionTraversalNode< S, OBBRSS >::num_leaf_tests, fcl::CollisionTraversalNodeBase::request, fcl::TraversalNodeBase::tf1, fcl::TraversalNodeBase::tf2, fcl::ShapeMeshCollisionTraversalNode< S, OBBRSS, NarrowPhaseSolver >::tri_indices, and fcl::ShapeMeshCollisionTraversalNode< S, OBBRSS, NarrowPhaseSolver >::vertices.