simplex.h File Reference
simplex.h File Reference
#include <ccd/compiler.h>
#include "support.h"
Classes
struct _ccd_simplex_t
Typedefs
typedef struct _ccd_simplex_t ccd_simplex_t
Functions
_ccd_inline void ccdSimplexInit (ccd_simplex_t *s)
_ccd_inline int ccdSimplexSize (const ccd_simplex_t *s)
_ccd_inline const ccd_support_t * ccdSimplexLast (const ccd_simplex_t *s)
_ccd_inline const ccd_support_t * ccdSimplexPoint (const ccd_simplex_t *s, int idx)
_ccd_inline ccd_support_t * ccdSimplexPointW (ccd_simplex_t *s, int idx)
_ccd_inline void ccdSimplexAdd (ccd_simplex_t *s, const ccd_support_t *v)
_ccd_inline void ccdSimplexSet (ccd_simplex_t *s, size_t pos, const ccd_support_t *a)
_ccd_inline void ccdSimplexSetSize (ccd_simplex_t *s, int size)
_ccd_inline void ccdSimplexSwap (ccd_simplex_t *s, size_t pos1, size_t pos2)
Typedef Documentation
typedef struct _ccd_simplex_t ccd_simplex_t
Function Documentation
_ccd_inline void ccdSimplexAdd (ccd_simplex_t * s, const ccd_support_t * v)
References ccdSupportCopy(), _ccd_simplex_t::last, and _ccd_simplex_t::ps.
_ccd_inline void ccdSimplexInit (ccd_simplex_t * s)
References _ccd_simplex_t::last.
_ccd_inline const ccd_support_t * ccdSimplexLast (const ccd_simplex_t * s)
References ccdSimplexPoint(), and _ccd_simplex_t::last.
_ccd_inline const ccd_support_t * ccdSimplexPoint (const ccd_simplex_t * s, int idx)
References _ccd_simplex_t::ps.
Referenced by ccdSimplexLast().
_ccd_inline ccd_support_t * ccdSimplexPointW (ccd_simplex_t * s, int idx)
References _ccd_simplex_t::ps.
_ccd_inline void ccdSimplexSet (ccd_simplex_t * s, size_t pos, const ccd_support_t * a)
References ccdSupportCopy(), and _ccd_simplex_t::ps.
_ccd_inline void ccdSimplexSetSize (ccd_simplex_t * s, int size)
References _ccd_simplex_t::last.
_ccd_inline int ccdSimplexSize (const ccd_simplex_t * s)
References _ccd_simplex_t::last.
_ccd_inline void ccdSimplexSwap (ccd_simplex_t * s, size_t pos1, size_t pos2)
References ccdSupportCopy(), and _ccd_simplex_t::ps.