support.h File Reference
support.h File Reference
#include <ccd/ccd.h>
Classes
struct _ccd_support_t
Typedefs
typedef struct _ccd_support_t ccd_support_t
Functions
_ccd_inline void ccdSupportCopy (ccd_support_t *, const ccd_support_t *s)
void __ccdSupport (const void *obj1, const void *obj2, const ccd_vec3_t *dir, const ccd_t *ccd, ccd_support_t *supp)
Computes support point of obj1 and obj2 in direction dir.
Typedef Documentation
typedef struct _ccd_support_t ccd_support_t
Function Documentation
void __ccdSupport (const void * obj1, const void * obj2, const ccd_vec3_t * dir, const ccd_t * ccd, ccd_support_t * supp)
Computes support point of obj1 and obj2 in direction dir.
Support point is returned via supp.
_ccd_inline void ccdSupportCopy (ccd_support_t * d, const ccd_support_t * s)
Referenced by ccdSimplexAdd(), ccdSimplexSet(), and ccdSimplexSwap().