math_details.h File Reference
eigen/math_details.h File Reference
#include <Eigen/Dense>
#include <Eigen/Geometry>
Classes
struct fcl::details::eigen_wrapper_v3< T >
struct fcl::details::internal::assign< Derived, Size >
struct fcl::details::internal::assign< Derived, 3 >
struct fcl::details::internal::assign< Derived, 4 >
struct fcl::details::eigen_wrapper_v4< T >
struct fcl::details::eigen_v3< T >
struct fcl::details::eigen_wrapper_m3< T >
struct fcl::details::eigen_m3< T >
Namespaces
fcl
Main namespace.
fcl::details
FCL internals.
fcl::details::internal
Typedefs
typedef T meta_type
typedef Eigen::Matrix< T, 4, 1 > vector_type
Functions
template<typename T >
static eigen_wrapper_v3< T > fcl::details::cross_prod (const eigen_wrapper_v3< T > &l, const eigen_wrapper_v3< T > &r)
template<typename T >
static T fcl::details::dot_prod3 (const eigen_wrapper_v3< T > &l, const eigen_wrapper_v3< T > &r)
template<typename T >
static eigen_wrapper_v3< T > fcl::details::min (const eigen_wrapper_v3< T > &x, const eigen_wrapper_v3< T > &y)
template<typename T >
static eigen_wrapper_v3< T > fcl::details::max (const eigen_wrapper_v3< T > &x, const eigen_wrapper_v3< T > &y)
template<typename T >
static eigen_wrapper_v3< T > fcl::details::abs (const eigen_wrapper_v3< T > &x)
template<typename T >
static bool fcl::details::equal (const eigen_wrapper_v3< T > &x, const eigen_wrapper_v3< T > &y, T epsilon)
template<typename T >
struct fcl::details::eigen_wrapper_v4 fcl::details::__attribute__ ((aligned))
eigen_wrapper_v4 ()
template<typename Derived >
eigen_wrapper_v4 (const Eigen::MatrixBase< Derived > &value)
eigen_wrapper_v4 (T x)
eigen_wrapper_v4 (T *x)
eigen_wrapper_v4 (T x, T y, T z)
vector_type::template FixedSegmentReturnType< 3 >::Type d ()
void setValue (T x, T y, T z, T w=0)
void setValue (T x)
void negate ()
eigen_wrapper_v4< T > & ubound (const eigen_wrapper_v4< T > &u)
eigen_wrapper_v4< T > & lbound (const eigen_wrapper_v4< T > &l)
T operator[] (size_t i) const
eigen_wrapper_v4< T > operator+ (const eigen_wrapper_v4< T > &other) const
eigen_wrapper_v4< T > operator- (const eigen_wrapper_v4< T > &other) const
eigen_wrapper_v4< T > operator* (const eigen_wrapper_v4< T > &other) const
eigen_wrapper_v4< T > operator/ (const eigen_wrapper_v4< T > &other) const
eigen_wrapper_v4< T > & operator+= (const eigen_wrapper_v4< T > &other)
eigen_wrapper_v4< T > & operator-= (const eigen_wrapper_v4< T > &other)
eigen_wrapper_v4< T > & operator*= (const eigen_wrapper_v4< T > &other)
eigen_wrapper_v4< T > & operator/= (const eigen_wrapper_v4< T > &other)
eigen_wrapper_v4< T > operator+ (T t) const
eigen_wrapper_v4< T > operator- (T t) const
eigen_wrapper_v4< T > operator* (T t) const
eigen_wrapper_v4< T > operator/ (T t) const
eigen_wrapper_v4< T > & operator+= (T t)
eigen_wrapper_v4< T > & operator-= (T t)
eigen_wrapper_v4< T > & operator*= (T t)
eigen_wrapper_v4< T > & operator/= (T t)
eigen_wrapper_v4< T > operator- () const
template<typename T >
static eigen_wrapper_v4< T > fcl::details::cross_prod (const eigen_wrapper_v4< T > &l, const eigen_wrapper_v4< T > &r)
template<typename T >
static T fcl::details::dot_prod3 (const eigen_wrapper_v4< T > &l, const eigen_wrapper_v4< T > &r)
template<typename T >
static eigen_wrapper_v4< T > fcl::details::min (const eigen_wrapper_v4< T > &x, const eigen_wrapper_v4< T > &y)
template<typename T >
static eigen_wrapper_v4< T > fcl::details::max (const eigen_wrapper_v4< T > &x, const eigen_wrapper_v4< T > &y)
template<typename T >
static eigen_wrapper_v4< T > fcl::details::abs (const eigen_wrapper_v4< T > &x)
template<typename T >
static bool fcl::details::equal (const eigen_wrapper_v4< T > &x, const eigen_wrapper_v4< T > &y, T epsilon)
template<typename T >
static eigen_v3< T > fcl::details::cross_prod (const eigen_v3< T > &l, const eigen_v3< T > &r)
template<typename T >
static T fcl::details::dot_prod3 (const eigen_v3< T > &l, const eigen_v3< T > &r)
template<typename T >
static eigen_v3< T > fcl::details::min (const eigen_v3< T > &x, const eigen_v3< T > &y)
template<typename T >
static eigen_v3< T > fcl::details::max (const eigen_v3< T > &x, const eigen_v3< T > &y)
template<typename T >
static eigen_v3< T > fcl::details::abs (const eigen_v3< T > &x)
template<typename T >
static bool fcl::details::equal (const eigen_v3< T > &x, const eigen_v3< T > &y, T epsilon)
template<typename T >
eigen_wrapper_m3< T > fcl::details::abs (const eigen_wrapper_m3< T > &m)
template<typename T >
eigen_wrapper_m3< T > fcl::details::transpose (const eigen_wrapper_m3< T > &m)
template<typename T >
eigen_wrapper_m3< T > fcl::details::inverse (const eigen_wrapper_m3< T > &m)
template<typename T >
eigen_m3< T > fcl::details::abs (const eigen_m3< T > &m)
template<typename T >
eigen_m3< T > fcl::details::transpose (const eigen_m3< T > &m)
template<typename T >
eigen_m3< T > fcl::details::inverse (const eigen_m3< T > &m)
Variables
vector_type v
fcl::details::eigen_v3 fcl::details::__attribute__
Typedef Documentation
typedef double meta_type
typedef Eigen::Matrix<T, 4, 1> vector_type
Function Documentation
vector_type::template ConstFixedSegmentReturnType< 3 >::Type d () inline
Referenced by fcl::MeshConservativeAdvancementTraversalNode< OBBRSS >::BVTesting(), fcl::MeshShapeConservativeAdvancementTraversalNode< OBBRSS, S, NarrowPhaseSolver >::BVTesting(), fcl::ShapeMeshConservativeAdvancementTraversalNode< S, OBBRSS, NarrowPhaseSolver >::BVTesting(), fcl::MeshShapeConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting(), fcl::MeshShapeConservativeAdvancementTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting(), fcl::ShapeMeshConservativeAdvancementTraversalNodeRSS< S, NarrowPhaseSolver >::BVTesting(), fcl::ShapeMeshConservativeAdvancementTraversalNodeOBBRSS< S, NarrowPhaseSolver >::BVTesting(), fcl::MeshConservativeAdvancementTraversalNode< OBBRSS >::canStop(), fcl::details::dot_prod3(), fcl::details::dot_prod4(), fcl::eigen(), fcl::details::equal(), fcl::generateBVHModel(), fcl::details::inverse(), fcl::MeshDistanceTraversalNode< OBBRSS >::leafTesting(), fcl::MeshConservativeAdvancementTraversalNode< OBBRSS >::leafTesting(), fcl::MeshShapeDistanceTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), fcl::MeshShapeConservativeAdvancementTraversalNode< OBBRSS, S, NarrowPhaseSolver >::leafTesting(), fcl::ShapeMeshConservativeAdvancementTraversalNode< S, OBBRSS, NarrowPhaseSolver >::leafTesting(), fcl::details::meshConservativeAdvancementTraversalNodeCanStop(), fcl::nodeBaseLess(), fcl::details::sse_meta_d4::operator*(), fcl::Interval::operator*=(), fcl::details::sse_meta_d4::operator*=(), fcl::details::sse_meta_d4::operator+(), fcl::details::sse_meta_d4::operator+=(), fcl::details::sse_meta_d4::operator-(), fcl::details::sse_meta_d4::operator-=(), fcl::details::sse_meta_d4::operator/(), fcl::details::sse_meta_d4::operator/=(), fcl::Quaternion3f::Quaternion3f(), fcl::OcTree::setCellDefaultOccupancy(), fcl::OcTree::setFreeThres(), and fcl::OcTree::setOccupancyThres().
__attribute__::eigen_wrapper_v4 ()
template<typename Derived > __attribute__::eigen_wrapper_v4 (const Eigen::MatrixBase< Derived > & value)
__attribute__::eigen_wrapper_v4 (T x)
__attribute__::eigen_wrapper_v4 (T * x)
__attribute__::eigen_wrapper_v4 (T x, T y, T z)
eigen_wrapper_v4<T>& __attribute__::lbound (const eigen_wrapper_v4< T > & l) inline
void negate () inline
eigen_wrapper_v4<T> __attribute__::operator* (const eigen_wrapper_v4< T > & other) const inline
eigen_wrapper_v4<T> __attribute__::operator* (T t) const inline
eigen_wrapper_v4<T>& __attribute__::operator*= (const eigen_wrapper_v4< T > & other) inline
eigen_wrapper_v4<T>& __attribute__::operator*= (T t) inline
eigen_wrapper_v4<T> __attribute__::operator+ (const eigen_wrapper_v4< T > & other) const inline
eigen_wrapper_v4<T> __attribute__::operator+ (T t) const inline
eigen_wrapper_v4<T>& __attribute__::operator+= (const eigen_wrapper_v4< T > & other) inline
Referenced by fcl::details::eigen_v3< T >::operator+=().
eigen_wrapper_v4<T>& __attribute__::operator+= (T t) inline
eigen_wrapper_v4<T> __attribute__::operator- (const eigen_wrapper_v4< T > & other) const inline
eigen_wrapper_v4<T> __attribute__::operator- (T t) const inline
sse_meta_d4 operator- () const inline
eigen_wrapper_v4<T>& __attribute__::operator-= (const eigen_wrapper_v4< T > & other) inline
Referenced by fcl::details::eigen_v3< T >::operator-=().
eigen_wrapper_v4<T>& __attribute__::operator-= (T t) inline
eigen_wrapper_v4<T> __attribute__::operator/ (const eigen_wrapper_v4< T > & other) const inline
eigen_wrapper_v4<T> __attribute__::operator/ (T t) const inline
eigen_wrapper_v4<T>& __attribute__::operator/= (const eigen_wrapper_v4< T > & other) inline
Referenced by Eigen::FclMatrix< FCL_REAL, 3 >::normalize().
eigen_wrapper_v4<T>& __attribute__::operator/= (T t) inline
double & operator[] (size_t i) const inline
Referenced by fcl::details::eigen_v3< T >::setValue().
void __attribute__::setValue (T x, T y, T z, T w = 0) inline
Referenced by operator=().
void __attribute__::setValue (T x) inline
eigen_wrapper_v4<T>& __attribute__::ubound (const eigen_wrapper_v4< T > & u) inline
Variable Documentation
vector_type v
Referenced by fcl::Interval::bound(), fcl::BVHExpand(), fcl::combine(), fcl::eigen(), fcl::generateCoordinateSystem(), fcl::Interval::Interval(), fcl::normalize(), fcl::operator<<(), and fcl::details::MinkowskiDiff::support0().