hpp::statistics Namespace Reference
hpp::statistics Namespace Reference
Classes
class Bin
Abstract class representing a bin.
class DiscreteDistribution
class Reason
class Statistics
Template class to do statistics.
class SuccessBin
This class count the number of success and failure.
class SuccessStatistics
class TimeCounter
Typedefs
typedef double Proba_t
typedef Statistics< Reason > Container
Functions
std::ostream & operator<< (std::ostream &os, const hpp::statistics::Bin &b)
template<typename T >
std::ostream & operator<< (std::ostream &os, const hpp::statistics::Statistics< T > &ss)
SuccessFailureCount ()
Constructor.
void addSuccess (const Reason &r=REASON_UNKNOWN)
Add a 'success'.
void addFailure (const Reason &r=REASON_UNKNOWN)
Add a 'failure'.
unsigned int nbSuccess () const
Count the number of success.
unsigned int nbSuccess (const SuccessBin::Reason &r) const
Count the number of a particular success.
unsigned int nbFailure () const
Count the number of failure, in total.
unsigned int nbFailure (const SuccessBin::Reason &r) const
Count the number of a particular failure.
std::ostream & operator<< (std::ostream &os, const TimeCounter &tc)
Variables
hpp::statistics::Reason REASON_UNKNOWN
Container success_
Container failure_
Typedef Documentation
typedef Statistics< Reason > hpp::statistics::Container
typedef double hpp::statistics::Proba_t
Function Documentation
void hpp::statistics::addFailure (const Reason & r = REASON_UNKNOWN)
Add a 'failure'.
Parameters
r the reason of the 'failure'
void hpp::statistics::addSuccess (const Reason & r = REASON_UNKNOWN)
Add a 'success'.
Parameters
r the reason of the 'failure'
unsigned int hpp::statistics::nbFailure () const
Count the number of failure, in total.
unsigned int hpp::statistics::nbFailure (const SuccessBin::Reason & r) const
Count the number of a particular failure.
unsigned int hpp::statistics::nbSuccess () const
Count the number of success.
Referenced by hpp::statistics::SuccessStatistics::isLowRatio(), and hpp::statistics::SuccessStatistics::nbFailure().
unsigned int hpp::statistics::nbSuccess (const SuccessBin::Reason & r) const
Count the number of a particular success.
std::ostream& hpp::statistics::operator<< (std::ostream & os, const TimeCounter & tc)
References hpp::statistics::TimeCounter::print().
std::ostream& hpp::statistics::operator<< (std::ostream & os, const hpp::statistics::Bin & b) inline
References hpp::statistics::Bin::print().
template<typename T > std::ostream & hpp::statistics::operator<< (std::ostream & os, const hpp::statistics::Statistics< T > & ss)
hpp::statistics::SuccessFailureCount ()
Constructor.
Variable Documentation
Container hpp::statistics::failure_
hpp::statistics::Reason hpp::statistics::REASON_UNKNOWN
Container hpp::statistics::success_
Referenced by hpp::statistics::SuccessBin::isSuccess(), and hpp::statistics::SuccessBin::SuccessBin().