hpp.corbaserver.problem_solver.ProblemSolver Class Reference
hpp.corbaserver.problem_solver.ProblemSolver Class Reference
Definition of a path planning problem.
Public Member Functions
def __init__ (self, robot)
Initial and goal configurations
def setInitialConfig (self, dofArray)
Set initial configuration of specified problem.
def getInitialConfig (self)
Get initial configuration of specified problem.
def addGoalConfig (self, dofArray)
Add goal configuration to specified problem.
def getGoalConfigs (self)
Get goal configurations of specified problem.
def resetGoalConfigs (self)
Reset goal configurations.
Obstacles
def loadObstacleFromUrdf (self, package, filename, prefix)
Load obstacle from urdf file.
def removeObstacleFromJoint (self, objectName, jointName, collision, distance)
Remove an obstacle from outer objects of a joint body.
def moveObstacle (self, objectName, cfg)
Move an obstacle to a given configuration.
def getObstaclePosition (self, objectName)
Get the position of an obstacle.
def getObstacleNames (self, collision, distance)
Get list of obstacles.
Constraints
def createOrientationConstraint (self, constraintName, joint1Name, joint2Name, p, mask)
Create orientation constraint between two joints.
def createRelativeComConstraint (self, constraintName, comName, jointLName, point, mask)
Create RelativeCom constraint between two joints.
def createComBeetweenFeet (self, constraintName, comName, jointLName, jointRName, pointL, pointR, jointRefName, mask)
Create ComBeetweenFeet constraint between two joints.
def addPartialCom (self, comName, jointNames)
Add an object to compute a partial COM of the robot.
def createPositionConstraint (self, constraintName, joint1Name, joint2Name, point1, point2, mask)
Create position constraint between two joints.
def createDistanceBetweenJointConstraint (self, constraintName, joint1Name, joint2Name, distance)
Create distance constraint between robot objects.
def createDistanceBetweenJointAndObjects (self, constraintName, joint1Name, objects, distance)
Create distance constraint between robot and environment objects.
def resetConstraints (self)
Reset Constraints.
def setNumericalConstraints
Set numerical constraints in ConfigProjector.
def applyConstraints (self, q)
Apply constraints.
def computeValueAndJacobian (self, q)
Compute value and Jacobian of numerical constraints.
def addPassiveDofs (self, name, dofNames)
Create a vector of passive dofs.
def generateValidConfig (self, maxIter)
Generate a configuration satisfying the constraints.
def lockJoint (self, jointName, value)
Lock joint with given joint configuration.
def setErrorThreshold (self, threshold)
error threshold in numerical constraint resolution
def setMaxIterations (self, iterations)
Set the maximal number of iterations.
Solve problem and get paths
def selectPathPlanner (self, pathPlannerType)
Select path planner type.
def addPathOptimizer (self, pathOptimizerType)
Add a path optimizer.
def clearPathOptimizers (self)
Clear sequence of path optimizers.
def selectPathValidation (self, pathValidationType, tolerance)
Select path validation method.
def selectPathProjector (self, pathProjectorType, tolerance)
Select path projector method.
def selectSteeringMethod (self, steeringMethodType)
Select steering method type.
def prepareSolveStepByStep (self)
def executeOneStep (self)
def finishSolveStepByStep (self)
def solve (self)
Solve the problem of corresponding ChppPlanner object.
def directPath (self, startConfig, endConfig)
Make direct connection between two configurations.
def numberPaths (self)
Get Number of paths.
def optimizePath (self, inPathId)
Optimize a given path.
def pathLength (self, inPathId)
Get length of path.
def configAtParam (self, inPathId, atDistance)
Get the robot's config at param on the a path.
def getWaypoints (self, pathId)
Get way points of a path.
Interruption of a path planning request
def interruptPathPlanning (self)
Interrupt path planning activity.
exploring the roadmap
def nodes (self)
Get nodes of the roadmap.
def node (self, nodeId)
def numberNodes (self)
def numberEdges (self)
Number of edges.
def edge (self, edgeId)
Edge at given rank.
def numberConnectedComponents (self)
Number of connected components.
def nodesConnectedComponent (self, ccId)
Nodes of a connected component.
def getNearestConfig
Return nearest neighbour of given input configuration.
def addConfigToRoadmap (self, config)
Add a configuration to the roadmap.
def addEdgeToRoadmap (self, config1, config2, pathId, bothEdges)
Add an edge to roadmap.
def clearRoadmap (self)
Clear the roadmap.
def saveRoadmap (self, filename)
Save the current roadmap in a file.
def readRoadmap (self, filename)
Read a roadmap from a file.
Public Attributes
client
robot
Detailed Description
Definition of a path planning problem.
This class wraps the Corba client to the server implemented by libhpp-corbaserver.so
Some method implemented by the server can be considered as private. The goal of this class is to hide them and to expose those that can be considered as public.
Constructor & Destructor Documentation
def hpp.corbaserver.problem_solver.ProblemSolver.__init__ (self, robot)
Member Function Documentation
def hpp.corbaserver.problem_solver.ProblemSolver.addConfigToRoadmap (self, config)
Add a configuration to the roadmap.
Parameters
config to be added to the roadmap.
def hpp.corbaserver.problem_solver.ProblemSolver.addEdgeToRoadmap (self, config1, config2, pathId, bothEdges)
Add an edge to roadmap.
If
Parameters
config1,config2 the ends of the path,
pathId the index if the path in the vector of path,
bothEdges if FALSE, only add config1 to config2, otherwise, If TRUE. add edges config1->config2 AND config2->config1.
def hpp.corbaserver.problem_solver.ProblemSolver.addGoalConfig (self, dofArray)
Add goal configuration to specified problem.
Parameters
dofArray Array of degrees of freedom
Exceptions
Error.
def hpp.corbaserver.problem_solver.ProblemSolver.addPartialCom (self, comName, jointNames)
Add an object to compute a partial COM of the robot.
Parameters
name of the partial com
jointNames list of joint name of each tree ROOT to consider.
Note
Joints are added recursively, it is not possible so far to add a joint without addind all its children.
References hpp.corbaserver.problem_solver.ProblemSolver.createPositionConstraint().
def hpp.corbaserver.problem_solver.ProblemSolver.addPassiveDofs (self, name, dofNames)
Create a vector of passive dofs.
Parameters
name name of the vector in the ProblemSolver map.
dofNames list of names of DOF that may
def hpp.corbaserver.problem_solver.ProblemSolver.addPathOptimizer (self, pathOptimizerType)
Add a path optimizer.
Parameters
Name of the path optimizer type, either "RandomShortcut" or any type added by core::ProblemSolver::addPathOptimizerType
def hpp.corbaserver.problem_solver.ProblemSolver.applyConstraints (self, q)
Apply constraints.
Parameters
q initial configuration
Returns
configuration projected in success,
Exceptions
Error if projection failed.
def hpp.corbaserver.problem_solver.ProblemSolver.clearPathOptimizers (self)
Clear sequence of path optimizers.
def hpp.corbaserver.problem_solver.ProblemSolver.clearRoadmap (self)
Clear the roadmap.
def hpp.corbaserver.problem_solver.ProblemSolver.computeValueAndJacobian (self, q)
Compute value and Jacobian of numerical constraints.
Parameters
q input configuration
Returns
value values of the numerical constraints stacked in a unique vector,
Jacobian of the numerical constraints stacked in a unique matrix.
Columns of the Jacobian corresponding to locked joints are omitted, columns corresponding to passive dofs are set to 0.
def hpp.corbaserver.problem_solver.ProblemSolver.configAtParam (self, inPathId, atDistance)
Get the robot's config at param on the a path.
Parameters
inPathId rank of the path in the problem
atDistance : the user parameter choice
Returns
dofseq : the config at param
def hpp.corbaserver.problem_solver.ProblemSolver.createComBeetweenFeet (self, constraintName, comName, jointLName, jointRName, pointL, pointR, jointRefName, mask)
Create ComBeetweenFeet constraint between two joints.
Parameters
constraintName name of the constraint created,
comName name of CenterOfMassComputation
jointLName name of first joint
jointRName name of second joint
pointL point in local frame of jointL.
pointR point in local frame of jointR.
jointRefName name of second joint
mask Select axis to be constrained. If jointRef is "", the robot root joint is used. Constraints are stored in ProblemSolver object
Referenced by hpp.corbaserver.problem_solver.ProblemSolver.createRelativeComConstraint().
def hpp.corbaserver.problem_solver.ProblemSolver.createDistanceBetweenJointAndObjects (self, constraintName, joint1Name, objects, distance)
Create distance constraint between robot and environment objects.
Parameters
constraintName name of the constraint created,
joint1Name name of first joint,
objects names of environment objects,
distance desired distance between joint bodies. Constraints are stored in ProblemSolver object
Referenced by hpp.corbaserver.problem_solver.ProblemSolver.createDistanceBetweenJointConstraint().
def hpp.corbaserver.problem_solver.ProblemSolver.createDistanceBetweenJointConstraint (self, constraintName, joint1Name, joint2Name, distance)
Create distance constraint between robot objects.
Parameters
constraintName name of the constraint created,
joint1Name name of first joint,
joint2Name name of second joint,
distance desired distance between joint bodies. Constraints are stored in ProblemSolver object
References hpp.corbaserver.problem_solver.ProblemSolver.createDistanceBetweenJointAndObjects().
Referenced by hpp.corbaserver.problem_solver.ProblemSolver.createPositionConstraint().
def hpp.corbaserver.problem_solver.ProblemSolver.createOrientationConstraint (self, constraintName, joint1Name, joint2Name, p, mask)
Create orientation constraint between two joints.
Parameters
constraintName name of the constraint created,
joint1Name name of first joint
joint2Name name of second joint
p quaternion representing the desired orientation of joint2 in the frame of joint1.
mask Select which axis to be constrained. If joint1 or joint2 is "", the corresponding joint is replaced by the global frame. constraints are stored in ProblemSolver object
Referenced by hpp.corbaserver.problem_solver.ProblemSolver.getObstacleNames().
def hpp.corbaserver.problem_solver.ProblemSolver.createPositionConstraint (self, constraintName, joint1Name, joint2Name, point1, point2, mask)
Create position constraint between two joints.
Parameters
constraintName name of the constraint created,
joint1Name name of first joint
joint2Name name of second joint
point1 point in local frame of joint1,
point2 point in local frame of joint2.
mask Select which axis to be constrained. If joint1 of joint2 is "", the corresponding joint is replaced by the global frame. constraints are stored in ProblemSolver object
References hpp.corbaserver.problem_solver.ProblemSolver.createDistanceBetweenJointConstraint().
Referenced by hpp.corbaserver.problem_solver.ProblemSolver.addPartialCom().
def hpp.corbaserver.problem_solver.ProblemSolver.createRelativeComConstraint (self, constraintName, comName, jointLName, point, mask)
Create RelativeCom constraint between two joints.
Parameters
constraintName name of the constraint created,
comName name of CenterOfMassComputation
jointName name of joint
point point in local frame of joint.
mask Select axis to be constrained. If jointName is "", the robot root joint is used. Constraints are stored in ProblemSolver object
References hpp.corbaserver.problem_solver.ProblemSolver.createComBeetweenFeet().
def hpp.corbaserver.problem_solver.ProblemSolver.directPath (self, startConfig, endConfig)
Make direct connection between two configurations.
Parameters
startConfig,endConfig the configurations to link.
Returns
True if the path is fully valid, false otherwise.
the path index of the collission-free part from startConfig
def hpp.corbaserver.problem_solver.ProblemSolver.edge (self, edgeId)
Edge at given rank.
def hpp.corbaserver.problem_solver.ProblemSolver.executeOneStep (self)
def hpp.corbaserver.problem_solver.ProblemSolver.finishSolveStepByStep (self)
def hpp.corbaserver.problem_solver.ProblemSolver.generateValidConfig (self, maxIter)
Generate a configuration satisfying the constraints.
Parameters
maxIter maximum number of tries,
Returns
configuration projected in success,
Exceptions
Error if projection failed.
def hpp.corbaserver.problem_solver.ProblemSolver.getGoalConfigs (self)
Get goal configurations of specified problem.
Returns
Array of degrees of freedom
def hpp.corbaserver.problem_solver.ProblemSolver.getInitialConfig (self)
Get initial configuration of specified problem.
Returns
Array of degrees of freedom
def hpp.corbaserver.problem_solver.ProblemSolver.getNearestConfig (self, randomConfig, connectedComponentId = -1)
Return nearest neighbour of given input configuration.
Parameters
connectedComponentId is the index of a connected component in the roadmap. If connectedComponentId is negative, function goes through all connected components looking for the nearest node (configuration).
distance returns the one-dimensional distance between
config and computed nearest node (configuration).
See also
numberConnectedComponents
def hpp.corbaserver.problem_solver.ProblemSolver.getObstacleNames (self, collision, distance)
Get list of obstacles.
Parameters
collision whether to return obstacle for collision,
distance whether to return obstacles for distance computation
Returns
list of obstacles
References hpp.corbaserver.problem_solver.ProblemSolver.createOrientationConstraint().
def hpp.corbaserver.problem_solver.ProblemSolver.getObstaclePosition (self, objectName)
Get the position of an obstacle.
Parameters
objectName name of the polyhedron.
Return values
cfg Position of the obstacle.
Exceptions
Error.
def hpp.corbaserver.problem_solver.ProblemSolver.getWaypoints (self, pathId)
Get way points of a path.
Parameters
pathId rank of the path in the problem
def hpp.corbaserver.problem_solver.ProblemSolver.interruptPathPlanning (self)
Interrupt path planning activity.
Note
this method is effective only when multi-thread policy is used by CORBA server. See constructor of class Server for details.
def hpp.corbaserver.problem_solver.ProblemSolver.loadObstacleFromUrdf (self, package, filename, prefix)
Load obstacle from urdf file.
Parameters
package Name of the package containing the model,
filename name of the urdf file in the package (without suffix .urdf)
prefix prefix added to object names in case the same file is loaded several times
The ros url is built as follows: "package://${package}/urdf/${filename}.urdf"
The kinematic structure of the urdf file is ignored. Only the geometric objects are loaded as obstacles.
References hpp.corbaserver.problem_solver.ProblemSolver.removeObstacleFromJoint().
def hpp.corbaserver.problem_solver.ProblemSolver.lockJoint (self, jointName, value)
Lock joint with given joint configuration.
Parameters
jointName name of the joint
value value of the joint configuration
def hpp.corbaserver.problem_solver.ProblemSolver.moveObstacle (self, objectName, cfg)
Move an obstacle to a given configuration.
Parameters
objectName name of the polyhedron.
cfg the configuration of the obstacle.
Exceptions
Error.
Note
The obstacle is not added to local map impl::Obstacle::collisionListMap.
Build the collision entity of polyhedron for KCD.
def hpp.corbaserver.problem_solver.ProblemSolver.node (self, nodeId)
def hpp.corbaserver.problem_solver.ProblemSolver.nodes (self)
Get nodes of the roadmap.
def hpp.corbaserver.problem_solver.ProblemSolver.nodesConnectedComponent (self, ccId)
Nodes of a connected component.
Parameters
connectedComponentId index of connected component in roadmap
Returns
list of nodes of the connected component.
def hpp.corbaserver.problem_solver.ProblemSolver.numberConnectedComponents (self)
Number of connected components.
def hpp.corbaserver.problem_solver.ProblemSolver.numberEdges (self)
Number of edges.
def hpp.corbaserver.problem_solver.ProblemSolver.numberNodes (self)
def hpp.corbaserver.problem_solver.ProblemSolver.numberPaths (self)
Get Number of paths.
def hpp.corbaserver.problem_solver.ProblemSolver.optimizePath (self, inPathId)
Optimize a given path.
Parameters
inPathId Id of the path in this problem.
Exceptions
Error.
def hpp.corbaserver.problem_solver.ProblemSolver.pathLength (self, inPathId)
Get length of path.
Parameters
inPathId rank of the path in the problem
Returns
length of path if path exists.
def hpp.corbaserver.problem_solver.ProblemSolver.prepareSolveStepByStep (self)
def hpp.corbaserver.problem_solver.ProblemSolver.readRoadmap (self, filename)
Read a roadmap from a file.
Parameters
filename name of the file from which the roadmap is read.
def hpp.corbaserver.problem_solver.ProblemSolver.removeObstacleFromJoint (self, objectName, jointName, collision, distance)
Remove an obstacle from outer objects of a joint body.
Parameters
objectName name of the object to remove,
jointName name of the joint owning the body,
collision whether collision with object should be computed,
distance whether distance to object should be computed.
Exceptions
Error.
Referenced by hpp.corbaserver.problem_solver.ProblemSolver.loadObstacleFromUrdf().
def hpp.corbaserver.problem_solver.ProblemSolver.resetConstraints (self)
Reset Constraints.
Reset all constraints, including numerical constraints and locked joints
def hpp.corbaserver.problem_solver.ProblemSolver.resetGoalConfigs (self)
Reset goal configurations.
def hpp.corbaserver.problem_solver.ProblemSolver.saveRoadmap (self, filename)
Save the current roadmap in a file.
Parameters
filename name of the file where the roadmap is saved
def hpp.corbaserver.problem_solver.ProblemSolver.selectPathPlanner (self, pathPlannerType)
Select path planner type.
Parameters
Name of the path planner type, either "DiffusingPlanner", "VisibilityPrmPlanner", or any type added by method core::ProblemSolver::addPathPlannerType
def hpp.corbaserver.problem_solver.ProblemSolver.selectPathProjector (self, pathProjectorType, tolerance)
Select path projector method.
Parameters
Name of the path projector method, either "Discretized" "Progressive", "Dichotomy", or any type added by core::ProblemSolver::addPathProjectorType,
tolerance maximal acceptable penetration.
def hpp.corbaserver.problem_solver.ProblemSolver.selectPathValidation (self, pathValidationType, tolerance)
Select path validation method.
Parameters
Name of the path validation method, either "Discretized" "Progressive", "Dichotomy", or any type added by core::ProblemSolver::addPathValidationType,
tolerance maximal acceptable penetration.
def hpp.corbaserver.problem_solver.ProblemSolver.selectSteeringMethod (self, steeringMethodType)
Select steering method type.
Parameters
Name of the steering method type, either "SteeringMethodStraight" or any type added by method core::ProblemSolver::addSteeringMethodType
def hpp.corbaserver.problem_solver.ProblemSolver.setErrorThreshold (self, threshold)
error threshold in numerical constraint resolution
def hpp.corbaserver.problem_solver.ProblemSolver.setInitialConfig (self, dofArray)
Set initial configuration of specified problem.
Parameters
dofArray Array of degrees of freedom
Exceptions
Error.
def hpp.corbaserver.problem_solver.ProblemSolver.setMaxIterations (self, iterations)
Set the maximal number of iterations.
def hpp.corbaserver.problem_solver.ProblemSolver.setNumericalConstraints (self, name, names, priorities = None)
Set numerical constraints in ConfigProjector.
Parameters
name name of the resulting numerical constraint obtained by stacking elementary numerical constraints,
names list of names of the numerical constraints as inserted by method hpp::core::ProblemSolver::addNumericalConstraint.
def hpp.corbaserver.problem_solver.ProblemSolver.solve (self)
Solve the problem of corresponding ChppPlanner object.
Member Data Documentation
hpp.corbaserver.problem_solver.ProblemSolver.client
hpp.corbaserver.problem_solver.ProblemSolver.robot