hpp::constraints::JointFrame Class Reference
hpp::constraints::JointFrame Class Reference
Symbolic calculus
#include <hpp/constraints/symbolic-calculus.hh>
Public Types
typedef CalculusBase< JointFrame, ValueType_t, JacobianType_t > Parent_t
Public Types inherited from hpp::constraints::CalculusBaseAbstract< Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
typedef Eigen::Matrix< value_type, 6, 1 > ValueType_t
typedef Eigen::Matrix< value_type, 6, Eigen::Dynamic > JacobianType_t
Public Member Functions
JointFrame ()
JointFrame (const Parent_t &other)
JointFrame (const JointFrame &jf)
JointFrame (const JointPtr_t &joint)
const JointPtr_t & joint () const
void impl_value ()
void impl_jacobian ()
Public Member Functions inherited from hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
CalculusBase ()
CalculusBase (const Eigen::Matrix< value_type, 6, 1 > &value, const Eigen::Matrix< value_type, 6, Eigen::Dynamic > &jacobian)
CalculusBase (const CalculusBase &o)
const Eigen::Matrix< value_type, 6, 1 > & value () const
const Eigen::Matrix< value_type, 6, Eigen::Dynamic > & jacobian () const
void computeValue ()
void computeJacobian ()
void invalidate ()
const CrossMatrix & cross () const
void computeCrossValue ()
Protected Attributes
JointPtr_t joint_
double theta_
Protected Attributes inherited from hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
Eigen::Matrix< value_type, 6, 1 > value_
Eigen::Matrix< value_type, 6, Eigen::Dynamic > jacobian_
CrossMatrix cross_
bool vValid_
bool jValid_
bool cValid_
Additional Inherited Members
Protected Member Functions inherited from hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >
void init (const typename Traits< JointFrame >::Ptr_t &ptr)
Member Typedef Documentation
typedef CalculusBase<JointFrame, ValueType_t, JacobianType_t > hpp::constraints::JointFrame::Parent_t
Constructor & Destructor Documentation
hpp::constraints::JointFrame::JointFrame () inline
hpp::constraints::JointFrame::JointFrame (const Parent_t & other) inline
hpp::constraints::JointFrame::JointFrame (const JointFrame & jf) inline
hpp::constraints::JointFrame::JointFrame (const JointPtr_t & joint) inline
References hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >::jacobian_, joint_, and hpp::model::Joint::robot().
Member Function Documentation
void hpp::constraints::JointFrame::impl_jacobian () inline
References hpp::constraints::computeJlog(), hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >::computeValue(), hpp::model::Joint::currentTransformation(), hpp::model::Joint::jacobian(), hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >::jacobian_, joint_, theta_, hpp::model::toEigen(), and hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >::value_.
void hpp::constraints::JointFrame::impl_value () inline
References hpp::constraints::computeLog(), hpp::model::Joint::currentTransformation(), joint_, theta_, and hpp::constraints::CalculusBase< JointFrame, Eigen::Matrix< value_type, 6, 1 >, Eigen::Matrix< value_type, 6, Eigen::Dynamic > >::value_.
const JointPtr_t& hpp::constraints::JointFrame::joint () const inline
References joint_.
Member Data Documentation
JointPtr_t hpp::constraints::JointFrame::joint_ protected
Referenced by impl_jacobian(), impl_value(), joint(), and JointFrame().
double hpp::constraints::JointFrame::theta_ protected
Referenced by impl_jacobian(), and impl_value().