hpp::constraints Namespace Reference
hpp::constraints Namespace Reference
Namespaces
eigen
Classes
class CalculusBase
Main abstract class.
class CalculusBaseAbstract
Abstract class defining a basic common interface.
class ComBetweenFeet
Constraint on the relative position of the center of mass.
class ConfigurationConstraint
class ConvexShape
class ConvexShapeContact
The function returns a relative transformation between the two "closest" convex shapes it contains.
class ConvexShapeContactComplement
Complement to full transformation constraint of ConvexShapeContact.
class CrossProduct
Cross product of two expressions.
class Difference
Difference of two expressions.
class DifferentiableFunction
Differentiable function.
class DistanceBetweenBodies
Distance between two sets of objects.
class DistanceBetweenPointsInBodies
Distance between two sets of objects.
class Expression
Base class for classes representing an operation.
class GenericTransformation
GenericTransformation class encapsulates 6 possible differentiable functions: Position2, Orientation2, Transformation2 and their relative versions RelativePosition2, RelativeOrientation2, RelativeTransformation2.
class JointFrame
struct JointTranspose
class MatrixOfExpressions
Matrix having Expression elements.
class Orientation
Constraint on the orientation of a robot joint.
class Point
Basic expression representing a static point.
class PointCom
Basic expression representing a COM.
class PointInJoint
Basic expression representing a point in a joint frame.
class Position
Constraint on the position of a robot point.
class QPStaticStability
class RelativeCom
Constraint on the relative position of the center of mass.
class RelativeOrientation
Constraint on the relative orientation of two robot joints.
class RelativePosition
Constraint on the relative position of two robot joints.
class RelativeTransformation
Relative transformation of two fixed frames in robot joints.
class RotationMultiply
Multiplication of an expression by a rotation matrix.
class ScalarMultiply
Multiplication of an expression by a scalar.
class ScalarProduct
Scalar product of two expressions.
class StaticStability
class Sum
Sum of two expressions.
class SymbolicFunction
struct Traits
struct Traits< JointTranspose >
struct Traits< model::Joint >
struct Traits< value_type >
class Transformation
Constraint on the transformation of one robot joint.
class VectorInJoint
Basic expression representing a vector in a joint frame.
Typedefs
typedef Eigen::Matrix< double, 5, 1 > vector5_t
typedef model::ObjectVector_t ObjectVector_t
typedef model::CollisionObjectPtr_t CollisionObjectPtr_t
typedef model::Configuration_t Configuration_t
typedef model::ConfigurationIn_t ConfigurationIn_t
typedef model::ConfigurationOut_t ConfigurationOut_t
typedef model::Device Device
typedef model::DevicePtr_t DevicePtr_t
typedef model::CenterOfMassComputation CenterOfMassComputation
typedef model::CenterOfMassComputationPtr_t CenterOfMassComputationPtr_t
typedef boost::shared_ptr< DifferentiableFunction > DifferentiableFunctionPtr_t
typedef model::size_type size_type
typedef model::value_type value_type
typedef model::JointPtr_t JointPtr_t
typedef model::vector3_t vector3_t
typedef model::matrix3_t matrix3_t
typedef model::matrix_t matrix_t
typedef Eigen::Ref< const matrix_t > matrixIn_t
typedef Eigen::Ref< matrix_t > matrixOut_t
typedef model::vector_t vector_t
typedef model::vectorIn_t vectorIn_t
typedef model::vectorOut_t vectorOut_t
typedef model::ComJacobian_t ComJacobian_t
typedef model::JointJacobian_t JointJacobian_t
typedef model::Transform3f Transform3f
typedef boost::shared_ptr< DistanceBetweenBodies > DistanceBetweenBodiesPtr_t
typedef boost::shared_ptr< DistanceBetweenPointsInBodies > DistanceBetweenPointsInBodiesPtr_t
typedef boost::shared_ptr< Orientation > OrientationPtr_t
typedef boost::shared_ptr< Position > PositionPtr_t
typedef boost::shared_ptr< Transformation > TransformationPtr_t
typedef boost::shared_ptr< RelativeOrientation > RelativeOrientationPtr_t
typedef boost::shared_ptr< RelativeCom > RelativeComPtr_t
typedef boost::shared_ptr< ComBetweenFeet > ComBetweenFeetPtr_t
typedef boost::shared_ptr< RelativePosition > RelativePositionPtr_t
typedef boost::shared_ptr< RelativeTransformation > RelativeTransformationPtr_t
typedef boost::shared_ptr< ConvexShapeContact > ConvexShapeContactPtr_t
typedef boost::shared_ptr< ConvexShapeContactComplement > ConvexShapeContactComplementPtr_t
typedef boost::shared_ptr< StaticStability > StaticStabilityPtr_t
typedef boost::shared_ptr< QPStaticStability > QPStaticStabilityPtr_t
typedef boost::shared_ptr< ConfigurationConstraint > ConfigurationConstraintPtr_t
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContact StaticStabilityGravity
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContactComplement StaticStabilityGravityComplement
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContactPtr_t StaticStabilityGravityPtr_t
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContactComplementPtr_t StaticStabilityGravityComplementPtr_t
typedef GenericTransformation< PositionBit|OrientationBit > Transformation2
typedef GenericTransformation< PositionBit > Position2
typedef GenericTransformation< OrientationBit > Orientation2
typedef GenericTransformation< RelativeBit|PositionBit|OrientationBit > RelativeTransformation2
typedef GenericTransformation< RelativeBit|PositionBit > RelativePosition2
typedef GenericTransformation< RelativeBit|OrientationBit > RelativeOrientation2
typedef eigen::matrix3_t CrossMatrix
typedef Eigen::Matrix< value_type, 1, Eigen::Dynamic, Eigen::RowMajor > RowJacobianMatrix
typedef Eigen::Matrix< value_type, 3, Eigen::Dynamic, Eigen::RowMajor > JacobianMatrix
Functions
void closestPointToSegment (const fcl::Vec3f &P, const fcl::Vec3f &A, const fcl::Vec3f &v, fcl::Vec3f &B)
Return the closest point to point P, on a segment line .
std::ostream & operator<< (std::ostream &os, const DifferentiableFunction &f)
HPP_PREDEF_CLASS (DifferentiableFunction)
HPP_PREDEF_CLASS (DistanceBetweenBodies)
HPP_PREDEF_CLASS (DistanceBetweenPointsInBodies)
HPP_PREDEF_CLASS (Orientation)
HPP_PREDEF_CLASS (Position)
HPP_PREDEF_CLASS (Transformation)
HPP_PREDEF_CLASS (RelativeCom)
HPP_PREDEF_CLASS (ComBetweenFeet)
HPP_PREDEF_CLASS (RelativeOrientation)
HPP_PREDEF_CLASS (RelativePosition)
HPP_PREDEF_CLASS (RelativeTransformation)
HPP_PREDEF_CLASS (StaticStability)
HPP_PREDEF_CLASS (QPStaticStability)
HPP_PREDEF_CLASS (ConvexShapeContact)
HPP_PREDEF_CLASS (ConvexShapeContactComplement)
HPP_PREDEF_CLASS (ConfigurationConstraint)
template<typename SVD >
static Eigen::Ref< const typename SVD::MatrixUType > getU1 (const SVD &svd)
template<typename SVD >
static Eigen::Ref< const typename SVD::MatrixUType > getU2 (const SVD &svd)
template<typename SVD >
static Eigen::Ref< const typename SVD::MatrixUType > getV1 (const SVD &svd)
template<typename SVD >
static Eigen::Ref< const typename SVD::MatrixUType > getV2 (const SVD &svd)
template<typename SVD >
static void pseudoInverse (const SVD &svd, Eigen::Ref< typename SVD::MatrixType > pinvmat)
template<typename SVD >
void projectorOnSpan (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector)
template<typename SVD >
void projectorOnSpanOfInv (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector)
template<typename SVD >
void projectorOnKernel (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector, const bool &computeFullV=false)
template<typename SVD >
void projectorOnKernelOfInv (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector, const bool &computeFullU=false)
void computeLog (vectorOut_t result, double &theta, const fcl::Matrix3f &Rerror)
void computeJlog (const double &theta, vectorIn_t r, eigen::matrix3_t &Jlog)
template<typename VectorType , typename MatrixType >
static void computeCrossMatrix (const VectorType &v, MatrixType &m)
template<typename InType , typename OutType >
static OutType convert (const InType &in, const std::size_t s)
Variables
const int RelativeBit = 0x1
const int PositionBit = 0x2
const int OrientationBit = 0x4
Typedef Documentation
typedef model::CenterOfMassComputation hpp::constraints::CenterOfMassComputation
typedef model::CenterOfMassComputationPtr_t hpp::constraints::CenterOfMassComputationPtr_t
typedef model::CollisionObjectPtr_t hpp::constraints::CollisionObjectPtr_t
typedef boost::shared_ptr<ComBetweenFeet> hpp::constraints::ComBetweenFeetPtr_t
typedef model::ComJacobian_t hpp::constraints::ComJacobian_t
typedef model::Configuration_t hpp::constraints::Configuration_t
typedef boost::shared_ptr<ConfigurationConstraint> hpp::constraints::ConfigurationConstraintPtr_t
typedef model::ConfigurationIn_t hpp::constraints::ConfigurationIn_t
typedef model::ConfigurationOut_t hpp::constraints::ConfigurationOut_t
typedef boost::shared_ptr<ConvexShapeContactComplement> hpp::constraints::ConvexShapeContactComplementPtr_t
typedef boost::shared_ptr<ConvexShapeContact> hpp::constraints::ConvexShapeContactPtr_t
typedef model::Device hpp::constraints::Device
typedef model::DevicePtr_t hpp::constraints::DevicePtr_t
typedef boost::shared_ptr<DifferentiableFunction> hpp::constraints::DifferentiableFunctionPtr_t
typedef boost::shared_ptr<DistanceBetweenBodies> hpp::constraints::DistanceBetweenBodiesPtr_t
typedef boost::shared_ptr<DistanceBetweenPointsInBodies> hpp::constraints::DistanceBetweenPointsInBodiesPtr_t
typedef model::JointJacobian_t hpp::constraints::JointJacobian_t
typedef model::JointPtr_t hpp::constraints::JointPtr_t
typedef model::matrix3_t hpp::constraints::matrix3_t
typedef model::matrix_t hpp::constraints::matrix_t
typedef Eigen::Ref<const matrix_t> hpp::constraints::matrixIn_t
typedef Eigen::Ref<matrix_t> hpp::constraints::matrixOut_t
typedef model::ObjectVector_t hpp::constraints::ObjectVector_t
typedef boost::shared_ptr<Orientation> hpp::constraints::OrientationPtr_t
typedef boost::shared_ptr<Position> hpp::constraints::PositionPtr_t
typedef boost::shared_ptr<QPStaticStability> hpp::constraints::QPStaticStabilityPtr_t
typedef boost::shared_ptr<RelativeCom> hpp::constraints::RelativeComPtr_t
typedef boost::shared_ptr<RelativeOrientation> hpp::constraints::RelativeOrientationPtr_t
typedef boost::shared_ptr<RelativePosition> hpp::constraints::RelativePositionPtr_t
typedef boost::shared_ptr<RelativeTransformation> hpp::constraints::RelativeTransformationPtr_t
typedef model::size_type hpp::constraints::size_type
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContact hpp::constraints::StaticStabilityGravity
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContactComplement hpp::constraints::StaticStabilityGravityComplement
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContactComplementPtr_t hpp::constraints::StaticStabilityGravityComplementPtr_t
typedef HPP_CONSTRAINTS_DEPRECATED ConvexShapeContactPtr_t hpp::constraints::StaticStabilityGravityPtr_t
typedef boost::shared_ptr<StaticStability> hpp::constraints::StaticStabilityPtr_t
typedef model::Transform3f hpp::constraints::Transform3f
typedef boost::shared_ptr<Transformation> hpp::constraints::TransformationPtr_t
typedef model::value_type hpp::constraints::value_type
typedef model::vector3_t hpp::constraints::vector3_t
typedef Eigen::Matrix<double, 5, 1> hpp::constraints::vector5_t
typedef model::vector_t hpp::constraints::vector_t
typedef model::vectorIn_t hpp::constraints::vectorIn_t
typedef model::vectorOut_t hpp::constraints::vectorOut_t
Function Documentation
void hpp::constraints::closestPointToSegment (const fcl::Vec3f & P, const fcl::Vec3f & A, const fcl::Vec3f & v, fcl::Vec3f & B) inline
Return the closest point to point P, on a segment line .
Parameters
P PA where P is the point to
A the origin the segment line
v vector presenting the segment line
[out] B the closest point
template<typename VectorType , typename MatrixType > static void hpp::constraints::computeCrossMatrix (const VectorType & v, MatrixType & m) static
Referenced by hpp::constraints::PointInJoint::computeCrossRXl(), hpp::constraints::VectorInJoint::computeCrossRXl(), and hpp::constraints::CalculusBase< CrossProduct< LhsValue, RhsValue > >::computeCrossValue().
void hpp::constraints::computeJlog (const double & theta, vectorIn_t r, eigen::matrix3_t & Jlog)
Referenced by hpp::constraints::JointFrame::impl_jacobian().
void hpp::constraints::computeLog (vectorOut_t result, double & theta, const fcl::Matrix3f & Rerror)
Referenced by hpp::constraints::JointFrame::impl_value().
template<typename InType , typename OutType > static OutType hpp::constraints::convert (const InType & in, const std::size_t s) static
template<typename SVD > static Eigen::Ref<const typename SVD::MatrixUType> hpp::constraints::getU1 (const SVD & svd) static
template<typename SVD > static Eigen::Ref<const typename SVD::MatrixUType> hpp::constraints::getU2 (const SVD & svd) static
template<typename SVD > static Eigen::Ref<const typename SVD::MatrixUType> hpp::constraints::getV1 (const SVD & svd) static
template<typename SVD > static Eigen::Ref<const typename SVD::MatrixUType> hpp::constraints::getV2 (const SVD & svd) static
hpp::constraints::HPP_PREDEF_CLASS (DifferentiableFunction)
hpp::constraints::HPP_PREDEF_CLASS (DistanceBetweenBodies)
hpp::constraints::HPP_PREDEF_CLASS (DistanceBetweenPointsInBodies)
hpp::constraints::HPP_PREDEF_CLASS (Orientation)
hpp::constraints::HPP_PREDEF_CLASS (Position)
hpp::constraints::HPP_PREDEF_CLASS (Transformation)
hpp::constraints::HPP_PREDEF_CLASS (RelativeCom)
hpp::constraints::HPP_PREDEF_CLASS (ComBetweenFeet)
hpp::constraints::HPP_PREDEF_CLASS (RelativeOrientation)
hpp::constraints::HPP_PREDEF_CLASS (RelativePosition)
hpp::constraints::HPP_PREDEF_CLASS (RelativeTransformation)
hpp::constraints::HPP_PREDEF_CLASS (StaticStability)
hpp::constraints::HPP_PREDEF_CLASS (QPStaticStability)
hpp::constraints::HPP_PREDEF_CLASS (ConvexShapeContact)
hpp::constraints::HPP_PREDEF_CLASS (ConvexShapeContactComplement)
hpp::constraints::HPP_PREDEF_CLASS (ConfigurationConstraint)
template<typename SVD > void hpp::constraints::projectorOnKernel (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector, const bool & computeFullV = false)
template<typename SVD > void hpp::constraints::projectorOnKernelOfInv (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector, const bool & computeFullU = false)
template<typename SVD > void hpp::constraints::projectorOnSpan (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector)
template<typename SVD > void hpp::constraints::projectorOnSpanOfInv (const SVD svd, Eigen::Ref< typename SVD::MatrixType > projector)
template<typename SVD > static void hpp::constraints::pseudoInverse (const SVD & svd, Eigen::Ref< typename SVD::MatrixType > pinvmat) static
Variable Documentation
const int hpp::constraints::OrientationBit = 0x4
const int hpp::constraints::PositionBit = 0x2
const int hpp::constraints::RelativeBit = 0x1