hpp::gui::ColorMap Class Reference
hpp::gui::ColorMap Class Reference
#include <hpp/gui/color-map.hh>
Public Member Functions
ColorMap (std::size_t nbColors)
QColor getColor (std::size_t index) const
void getColor (std::size_t index, float color[4]) const
QColor nextColor ()
void currentIndex (std::size_t index)
std::size_t remap (const std::size_t &index) const
Reverse the order of the bits in index.
Static Public Member Functions
static QColor interpolate (std::size_t nbColors, std::size_t index)
Constructor & Destructor Documentation
hpp::gui::ColorMap::ColorMap (std::size_t nbColors) inline
Member Function Documentation
void hpp::gui::ColorMap::currentIndex (std::size_t index) inline
Referenced by nextColor().
QColor hpp::gui::ColorMap::getColor (std::size_t index) const inline
References interpolate(), and remap().
Referenced by getColor(), and nextColor().
void hpp::gui::ColorMap::getColor (std::size_t index, float color[4]) const inline
References getColor().
static QColor hpp::gui::ColorMap::interpolate (std::size_t nbColors, std::size_t index) inline static
Referenced by getColor().
QColor hpp::gui::ColorMap::nextColor () inline
References currentIndex(), and getColor().
std::size_t hpp::gui::ColorMap::remap (const std::size_t & index) const inline
Reverse the order of the bits in index.
This increases the contrast between colors with close indexes.
Referenced by getColor().