hpp::gui::PluginManagerDialog Class Reference
hpp::gui::PluginManagerDialog Class Reference
#include <hpp/gui/dialog/pluginmanagerdialog.hh>
Public Slots
void onItemChanged (QTableWidgetItem *current, QTableWidgetItem *previous)
void contextMenu (const QPoint &pos)
void load (const QString &name)
void unload (const QString &name)
Public Member Functions
PluginManagerDialog (PluginManager *pm, QWidget *parent=0)
~PluginManagerDialog ()
Constructor & Destructor Documentation
hpp::gui::PluginManagerDialog::PluginManagerDialog (PluginManager * pm, QWidget * parent = 0) explicit
References contextMenu(), and onItemChanged().
hpp::gui::PluginManagerDialog::~PluginManagerDialog ()
Member Function Documentation
void hpp::gui::PluginManagerDialog::contextMenu (const QPoint & pos) slot
References load(), hpp::gui::PluginManager::plugins(), and unload().
Referenced by PluginManagerDialog().
void hpp::gui::PluginManagerDialog::load (const QString & name) slot
References hpp::gui::PluginManager::initPlugin().
Referenced by contextMenu().
void hpp::gui::PluginManagerDialog::onItemChanged (QTableWidgetItem * current, QTableWidgetItem * previous) slot
References hpp::gui::PluginManager::plugins(), and hpp::gui::PluginManager::status().
Referenced by PluginManagerDialog().
void hpp::gui::PluginManagerDialog::unload (const QString & name) slot
References hpp::gui::PluginManager::unloadPlugin().
Referenced by contextMenu().