hpp::gui::MainWindow Class Reference
hpp::gui::MainWindow Class Reference
#include <hpp/gui/mainwindow.hh>
Public Slots
void log (const QString &text)
void logError (const QString &text)
void logJobStarted (int id, const QString &text)
void logJobDone (int id, const QString &text)
void logJobFailed (int id, const QString &text)
OSGWidget * delayedCreateView (QString name="")
void requestRefresh ()
void requestApplyCurrentConfiguration ()
void requestConfigurationValidation ()
void configurationValidationStatusChanged (bool valid)
void configurationValidationStatusChanged (QStringList bodiesInCollision)
void requestSelectJointFromBodyName (const QString bodyName)
void onOpenPluginManager ()
Signals
void sendToBackground (WorkItem *item)
void createView (QString name)
void refresh ()
void applyCurrentConfiguration ()
void configurationValidation ()
void selectJointFromBodyName (const QString bodyName)
Public Member Functions
MainWindow (Settings *settings, QWidget *parent=0)
~MainWindow ()
void insertDockWidget (QDockWidget *dock, Qt::DockWidgetArea area=Qt::AllDockWidgetAreas, Qt::Orientation orientation=Qt::Horizontal)
void removeDockWidget (QDockWidget *dock)
BackgroundQueue & worker ()
WindowsManagerPtr_t osg () const
OSGWidget * centralWidget () const
QList< OSGWidget * > osgWindows () const
BodyTreeWidget * bodyTree () const
PluginManager * pluginManager ()
void emitSendToBackground (WorkItem *item)
Static Public Member Functions
static MainWindow * instance ()
Public Attributes
Settings * settings_
Constructor & Destructor Documentation
hpp::gui::MainWindow::MainWindow (Settings * settings, QWidget * parent = 0) explicit
References createView(), insertDockWidget(), logJobFailed(), osg(), requestRefresh(), sendToBackground(), settings_, hpp::gui::CorbaServer::start(), and hpp::gui::Settings::startGepettoCorbaServer.
hpp::gui::MainWindow::~MainWindow ()
References hpp::gui::CorbaServer::wait().
Member Function Documentation
void hpp::gui::MainWindow::applyCurrentConfiguration () signal
Referenced by requestApplyCurrentConfiguration().
BodyTreeWidget * hpp::gui::MainWindow::bodyTree () const
Referenced by hpp::gui::OSGWidget::loadURDF(), hpp::gui::OSGWidget::OSGWidget(), hpp::gui::PickHandler::PickHandler(), hpp::gui::BodyTreeItem::remove(), and hpp::gui::BodyTreeItem::removeAll().
OSGWidget * hpp::gui::MainWindow::centralWidget () const
void hpp::gui::MainWindow::configurationValidation () signal
Referenced by requestConfigurationValidation().
void hpp::gui::MainWindow::configurationValidationStatusChanged (bool valid) slot
References osg(), and hpp::gui::LedIndicator::switchLed().
void hpp::gui::MainWindow::configurationValidationStatusChanged (QStringList bodiesInCollision) slot
This body is not in collision
This body is still in collision
References osg(), and hpp::gui::LedIndicator::switchLed().
void hpp::gui::MainWindow::createView (QString name) signal
Referenced by delayedCreateView(), and MainWindow().
OSGWidget * hpp::gui::MainWindow::delayedCreateView (QString name = "") slot
References createView().
Referenced by hpp::gui::WindowsManager::createWindow().
void hpp::gui::MainWindow::emitSendToBackground (WorkItem * item)
References sendToBackground().
void hpp::gui::MainWindow::insertDockWidget (QDockWidget * dock, Qt::DockWidgetArea area = Qt::AllDockWidgetAreas, Qt::Orientation orientation = Qt::Horizontal)
Referenced by MainWindow().
MainWindow * hpp::gui::MainWindow::instance () static
Referenced by hpp::gui::BodyTreeItem::addLandmark(), hpp::gui::BodyTreeItem::attachToWindow(), hpp::gui::WindowsManager::createWindow(), hpp::gui::BodyTreeWidget::customContextMenu(), hpp::gui::BodyTreeItem::deleteLandmark(), hpp::gui::BodyTreeWidget::init(), hpp::gui::SafeApplication::notify(), hpp::gui::BackgroundQueue::perform(), hpp::gui::PickHandler::PickHandler(), hpp::gui::PythonWidget::PythonWidget(), hpp::gui::BodyTreeItem::remove(), hpp::gui::BodyTreeItem::removeAll(), hpp::gui::BodyTreeItem::removeFromGroup(), hpp::gui::BodyTreeItem::setViewingMode(), and hpp::gui::BodyTreeItem::setVisibilityMode().
void hpp::gui::MainWindow::log (const QString & text) slot
Referenced by logJobDone(), and logJobStarted().
void hpp::gui::MainWindow::logError (const QString & text) slot
Referenced by logJobFailed().
void hpp::gui::MainWindow::logJobDone (int id, const QString & text) slot
References log().
void hpp::gui::MainWindow::logJobFailed (int id, const QString & text) slot
References logError().
Referenced by MainWindow().
void hpp::gui::MainWindow::logJobStarted (int id, const QString & text) slot
References log().
void hpp::gui::MainWindow::onOpenPluginManager () slot
References pluginManager().
WindowsManagerPtr_t hpp::gui::MainWindow::osg () const
Referenced by hpp::gui::BodyTreeItem::addLandmark(), hpp::gui::BodyTreeItem::attachToWindow(), configurationValidationStatusChanged(), hpp::gui::BodyTreeItem::deleteLandmark(), hpp::gui::BodyTreeWidget::init(), MainWindow(), hpp::gui::BodyTreeItem::remove(), hpp::gui::BodyTreeItem::removeAll(), hpp::gui::BodyTreeItem::removeFromGroup(), hpp::gui::BodyTreeItem::setViewingMode(), and hpp::gui::BodyTreeItem::setVisibilityMode().
QList< OSGWidget * > hpp::gui::MainWindow::osgWindows () const
Referenced by hpp::gui::BodyTreeWidget::customContextMenu().
PluginManager * hpp::gui::MainWindow::pluginManager ()
References hpp::gui::Settings::pluginManager_, and settings_.
Referenced by onOpenPluginManager().
void hpp::gui::MainWindow::refresh () signal
Referenced by requestRefresh().
void hpp::gui::MainWindow::removeDockWidget (QDockWidget * dock)
void hpp::gui::MainWindow::requestApplyCurrentConfiguration () slot
References applyCurrentConfiguration(), and requestConfigurationValidation().
void hpp::gui::MainWindow::requestConfigurationValidation () slot
References configurationValidation().
Referenced by requestApplyCurrentConfiguration().
void hpp::gui::MainWindow::requestRefresh () slot
References refresh().
Referenced by MainWindow().
void hpp::gui::MainWindow::requestSelectJointFromBodyName (const QString bodyName) slot
References selectJointFromBodyName().
void hpp::gui::MainWindow::selectJointFromBodyName (const QString bodyName) signal
Referenced by requestSelectJointFromBodyName().
void hpp::gui::MainWindow::sendToBackground (WorkItem * item) signal
Referenced by emitSendToBackground(), and MainWindow().
BackgroundQueue & hpp::gui::MainWindow::worker ()
Member Data Documentation
Settings* hpp::gui::MainWindow::settings_
Referenced by MainWindow(), hpp::gui::OSGWidget::OSGWidget(), and pluginManager().