bodytreewidget.cc File Reference
bodytreewidget.cc File Reference
#include <hpp/gui/bodytreewidget.hh>
#include <hpp/gui/tree-item.hh>
#include <hpp/gui/mainwindow.hh>
#include <hpp/gui/windows-manager.hh>
#include <hpp/gui/osgwidget.hh>
#include <hpp/gui/meta.hh>
#include <QSignalMapper>
#include <QColorDialog>
Namespaces
hpp
hpp::gui
Functions
static void addSelector (QToolBox *tb, QString title, QStringList display, QStringList command, QObject *receiver, const char *slot)
static void addColorSelector (QToolBox *tb, QString title, QObject *receiver, const char *slot)
static void addSlider (QToolBox *tb, QString title, QObject *receiver, const char *slot)
Function Documentation
static void addColorSelector (QToolBox * tb, QString title, QObject * receiver, const char * slot) static
Referenced by hpp::gui::BodyTreeWidget::init().
static void addSelector (QToolBox * tb, QString title, QStringList display, QStringList command, QObject * receiver, const char * slot) static
Referenced by hpp::gui::BodyTreeWidget::init().
static void addSlider (QToolBox * tb, QString title, QObject * receiver, const char * slot) static
Referenced by hpp::gui::BodyTreeWidget::init().