hpp::gui::OSGWidget Class Reference
hpp::gui::OSGWidget Class Reference
#include <hpp/gui/osgwidget.hh>
Public Types
enum Mode {
CAMERA_MANIPULATION,
NODE_SELECTION,
NODE_MOTION
}
typedef std::list< graphics::NodePtr_t > NodeList
Public Slots
void loadURDF (const QString robotName, const QString urdf_file_path, const QString meshDataRootDir)
virtual void onHome ()
void changeMode (Mode mode)
void selectionMode ()
void cameraManipulationMode ()
void addFloor ()
void attachToWindow (const std::string nodeName)
Signals
void selected (QString name)
void requestMotion (graphics::NodePtr_t node, graphics::Node::Arrow direction, float speed)
Public Member Functions
OSGWidget (WindowsManagerPtr_t wm, std::string name, MainWindow *parent=0, Qt::WindowFlags f=0, osgViewer::ViewerBase::ThreadingModel threadingModel=osgViewer::Viewer::SingleThreaded)
virtual ~OSGWidget ()
WindowsManager::WindowID windowID () const
Protected Member Functions
virtual void paintEvent (QPaintEvent *paintEvent)
Friends
class PickHandler
Member Typedef Documentation
typedef std::list<graphics::NodePtr_t> hpp::gui::OSGWidget::NodeList
Member Enumeration Documentation
enum hpp::gui::OSGWidget::Mode
Enumerator
CAMERA_MANIPULATION
NODE_SELECTION
NODE_MOTION
Constructor & Destructor Documentation
hpp::gui::OSGWidget::OSGWidget (WindowsManagerPtr_t wm, std::string name, MainWindow * parent = 0, Qt::WindowFlags f = 0, osgViewer::ViewerBase::ThreadingModel threadingModel = osgViewer::Viewer::SingleThreaded)
References hpp::gui::MainWindow::bodyTree(), hpp::gui::Settings::captureDirectory, hpp::gui::Settings::captureExtension, hpp::gui::Settings::captureFilename, hpp::gui::Settings::refreshRate, hpp::gui::RenderThread::refreshRate, selected(), hpp::gui::MainWindow::settings_, hpp::gui::RenderThread::viewerPtr, and hpp::gui::RenderThread::wsm_.
hpp::gui::OSGWidget::~OSGWidget () virtual
Member Function Documentation
void hpp::gui::OSGWidget::addFloor () slot
void hpp::gui::OSGWidget::attachToWindow (const std::string nodeName) slot
void hpp::gui::OSGWidget::cameraManipulationMode () slot
References CAMERA_MANIPULATION.
void hpp::gui::OSGWidget::changeMode (Mode mode) slot
void hpp::gui::OSGWidget::loadURDF (const QString robotName, const QString urdf_file_path, const QString meshDataRootDir) slot
References hpp::gui::BodyTreeWidget::addBodyToTree(), and hpp::gui::MainWindow::bodyTree().
void hpp::gui::OSGWidget::onHome () virtual slot
void hpp::gui::OSGWidget::paintEvent (QPaintEvent * paintEvent) protected virtual
void hpp::gui::OSGWidget::requestMotion (graphics::NodePtr_t node, graphics::Node::Arrow direction, float speed) signal
void hpp::gui::OSGWidget::selected (QString name) signal
Referenced by OSGWidget().
void hpp::gui::OSGWidget::selectionMode () slot
References NODE_SELECTION.
graphics::WindowsManager::WindowID hpp::gui::OSGWidget::windowID () const
Referenced by hpp::gui::WindowsManager::createWindow().
Friends And Related Function Documentation
friend class PickHandler friend