hpp::gui::SafeApplication Class Reference
hpp::gui::SafeApplication Class Reference
#include <hpp/gui/safeapplication.hh>
Signals
void log (QString text)
Public Member Functions
SafeApplication (int &argc, char **argv)
virtual bool notify (QObject *receiver, QEvent *e)
Constructor & Destructor Documentation
hpp::gui::SafeApplication::SafeApplication (int & argc, char ** argv) explicit
Member Function Documentation
void hpp::gui::SafeApplication::log (QString text) signal
Referenced by notify().
bool hpp::gui::SafeApplication::notify (QObject * receiver, QEvent * e) virtual
References hpp::gui::CorbaInterface::corbaException(), hpp::gui::MainWindow::instance(), and log().