hpp::walkgen::SplineBased Class Reference
hpp::walkgen::SplineBased Class Reference
Walk motion generator for humanoid legged robot.
#include <hpp/walkgen/bspline-based.hh>
Classes
struct BoundaryCondition
Public Types
typedef std::vector< PiecewisePoly3 > ZmpTrajectory_t
typedef std::vector< ZmpTrajectory_t > ZmpTrajectories_t
typedef std::vector< BoundaryCondition, Eigen::aligned_allocator< BoundaryCondition > > BoundaryConditions_t
typedef std::vector< value_type > StepHeights_t
Public Member Functions
void timeSequence (const Times_t &times)
set time sequence
const Times_t & timeSequence () const
get time sequence
void footPrintSequence (const FootPrints_t &footPrints)
set sequence of foot prints
const FootPrints_t & footPrintSequence () const
get sequence of foot prints
void defaultStepHeight (const value_type &stepHeight)
Set default step height.
const value_type & defaultStepHeight () const
Get default step height.
void stepHeights (const StepHeights_t &stepHeights)
Set sequence of step heights.
const StepHeights_t & stepHeights () const
Get sequence of step heights.
void zmpRefBoundaryConditions (const vector2_t &init, const vector2_t &end)
Specify zmpref boundary conditions.
void add (const BoundaryCondition &boundaryCondition)
Add a boundary condition on center of mass trajectory.
void setInitialComState (const vector2_t &position, const vector2_t &velocity)
Set initial position and velocity of center of mass.
void setEndComState (const vector2_t &position, const vector2_t &velocity)
Set final position and velocity of center of mass.
CubicBSplinePtr_t solve () const
Solve quadratic program and return resulting cubic B spline.
const PathVectorPtr_t & leftFootTrajectory () const
Get trajectory of left foot.
const PathVectorPtr_t & rightFootTrajectory () const
Get trajectory of right foot.
model::DevicePtr_t leftFoot () const
model::DevicePtr_t rightFoot () const
const ZmpTrajectory_t & zmpRefx () const
Getter to representation of zmp ref abscissa.
const ZmpTrajectory_t & zmpRefy () const
Getter to representation of zmp ref abscissa.
value_type cost (const vector_t &controlPoints)
Compute the cost of a com trajectory defined by way points.
value_type cost () const
Compute the cost of the current com trajectory.
const ZmpTrajectories_t & zmpBasisFunctions () const
Get base functions of Zmp.
Static Public Member Functions
static SplineBasedPtr_t create (const value_type &height)
Create instance and return shared pointer.
static value_type integral (value_type lower, value_type upper, const PiecewisePoly3 &P1, const PiecewisePoly3 &P2)
Static Public Attributes
static EIGEN_MAKE_ALIGNED_OPERATOR_NEW value_type gravity = 9.81
static size_type l = 3
Protected Member Functions
SplineBased (const value_type &height)
Constructor.
void init (const SplineBasedWkPtr_t &self)
initialization Store weak pointer to instance
void computeFootTrajectory () const
Compute trajectory of the feet.
Detailed Description
Walk motion generator for humanoid legged robot.
This class computes the reference trajectory of the center of mass of a humanoid robot, given as input a list of time-stamped foot-prints.
The trajectory of the center of mass is obtained by optimization for the linear so called table cart model.
Member Typedef Documentation
typedef std::vector<BoundaryCondition, Eigen::aligned_allocator <BoundaryCondition> > hpp::walkgen::SplineBased::BoundaryConditions_t
typedef std::vector<value_type> hpp::walkgen::SplineBased::StepHeights_t
typedef std::vector<ZmpTrajectory_t> hpp::walkgen::SplineBased::ZmpTrajectories_t
typedef std::vector<PiecewisePoly3> hpp::walkgen::SplineBased::ZmpTrajectory_t
Constructor & Destructor Documentation
hpp::walkgen::SplineBased::SplineBased (const value_type & height) protected
Constructor.
Parameters
height height of the center of mass
Referenced by create().
Member Function Documentation
void hpp::walkgen::SplineBased::add (const BoundaryCondition & boundaryCondition)
Add a boundary condition on center of mass trajectory.
Parameters
t time when position of center of mass is constrained,
position required position of the center of mass.
Note
setting time or step sequence discards boundary conditions.
void hpp::walkgen::SplineBased::computeFootTrajectory () const protected
Compute trajectory of the feet.
Swap the foot
Check if this step was the last one
References hpp::core::PathVector::create(), hpp::walkgen::Step::create(), and hpp::walkgen::SupportFoot::create().
Referenced by solve().
value_type hpp::walkgen::SplineBased::cost (const vector_t & controlPoints)
Compute the cost of a com trajectory defined by way points.
References cost().
value_type hpp::walkgen::SplineBased::cost () const
Compute the cost of the current com trajectory.
References gravity, and integral().
Referenced by cost(), and solve().
SplineBasedPtr_t hpp::walkgen::SplineBased::create (const value_type & height) static
Create instance and return shared pointer.
Parameters
height height of the center of mass
References init(), and SplineBased().
void hpp::walkgen::SplineBased::defaultStepHeight (const value_type & stepHeight) inline
Set default step height.
const value_type& hpp::walkgen::SplineBased::defaultStepHeight () const inline
Get default step height.
void hpp::walkgen::SplineBased::footPrintSequence (const FootPrints_t & footPrints)
set sequence of foot prints
Parameters
footPrints a vector of foot prints
Note
number of foot prints should be set after time sequence and should fit length of time sequence. If is the number of foot prints, the length of the time sequence should be equal to . See this document for details.
Sequence of step heights is set to the default value.
References l.
const FootPrints_t& hpp::walkgen::SplineBased::footPrintSequence () const inline
get sequence of foot prints
void hpp::walkgen::SplineBased::init (const SplineBasedWkPtr_t & self) protected
initialization Store weak pointer to instance
Referenced by create().
value_type hpp::walkgen::SplineBased::integral (value_type lower, value_type upper, const PiecewisePoly3 & P1, const PiecewisePoly3 & P2) static
References hpp::walkgen::PiecewisePoly3::lower, and hpp::walkgen::PiecewisePoly3::upper.
Referenced by cost().
model::DevicePtr_t hpp::walkgen::SplineBased::leftFoot () const inline
const PathVectorPtr_t& hpp::walkgen::SplineBased::leftFootTrajectory () const inline
Get trajectory of left foot.
Method solve should have been called first
model::DevicePtr_t hpp::walkgen::SplineBased::rightFoot () const inline
const PathVectorPtr_t& hpp::walkgen::SplineBased::rightFootTrajectory () const inline
Get trajectory of right foot.
Method solve should have been called first
void hpp::walkgen::SplineBased::setEndComState (const vector2_t & position, const vector2_t & velocity)
Set final position and velocity of center of mass.
Parameters
position position of the center of mass at end
velocity velocity of the center of mass at start
void hpp::walkgen::SplineBased::setInitialComState (const vector2_t & position, const vector2_t & velocity)
Set initial position and velocity of center of mass.
Parameters
position position of the center of mass at start
velocity velocity of the center of mass at start
CubicBSplinePtr_t hpp::walkgen::SplineBased::solve () const
Solve quadratic program and return resulting cubic B spline.
References computeFootTrajectory(), and cost().
void hpp::walkgen::SplineBased::stepHeights (const StepHeights_t & stepHeights) inline
Set sequence of step heights.
Parameters
stepHeights sequence of step heights
Note
Sequence of foot heights should be set after the sequence of foot prints.
const StepHeights_t& hpp::walkgen::SplineBased::stepHeights () const inline
Get sequence of step heights.
void hpp::walkgen::SplineBased::timeSequence (const Times_t & times)
set time sequence
Parameters
times sequence of times corresponding to support phases.
const Times_t& hpp::walkgen::SplineBased::timeSequence () const inline
get time sequence
Returns
sequence of times corresponding to support phases.
const ZmpTrajectories_t& hpp::walkgen::SplineBased::zmpBasisFunctions () const inline
Get base functions of Zmp.
void hpp::walkgen::SplineBased::zmpRefBoundaryConditions (const vector2_t & init, const vector2_t & end) inline
Specify zmpref boundary conditions.
Parameters
init,end initial and end values of zmpref trajectory
Note
If not specified, the middle of the first (respectively last) foot prints.
setting step sequence discards zmp boundary conditions.
References init().
const ZmpTrajectory_t& hpp::walkgen::SplineBased::zmpRefx () const inline
Getter to representation of zmp ref abscissa.
const ZmpTrajectory_t& hpp::walkgen::SplineBased::zmpRefy () const inline
Getter to representation of zmp ref abscissa.
Member Data Documentation
value_type hpp::walkgen::SplineBased::gravity = 9.81 static
Referenced by cost().
size_type hpp::walkgen::SplineBased::l = 3 static
Referenced by footPrintSequence().