se3::SE3Tpl< _Scalar, _Options > Class Template Reference
se3::SE3Tpl< _Scalar, _Options > Class Template Reference
The rigid transform aMb can be seen in two ways:
#include <gepetto/viewer/corba/se3.hh>
Public Types
enum { Options = _Options }
enum {
LINEAR = 0,
ANGULAR = 3
}
typedef _Scalar Scalar
typedef Eigen::Matrix< Scalar, 3, 1, Options > Vector3
typedef Eigen::Matrix< Scalar, 4, 1, Options > Vector4
typedef Eigen::Matrix< Scalar, 3, 3, Options > Matrix3
typedef Eigen::Matrix< Scalar, 6, 1, Options > Vector6
typedef Eigen::Matrix< Scalar, 4, 4, Options > Matrix4
typedef Eigen::Matrix< Scalar, 6, 6, Options > Matrix6
typedef Eigen::Quaternion< Scalar, Options > Quaternion
Public Member Functions
SE3Tpl ()
template<typename M3 , typename v3 >
SE3Tpl (const Eigen::MatrixBase< M3 > &R, const Eigen::MatrixBase< v3 > &p)
SE3Tpl (int)
template<typename S2 , int O2>
SE3Tpl (const SE3Tpl< S2, O2 > clone)
template<typename S2 , int O2>
SE3Tpl & operator= (const SE3Tpl< S2, O2 > &other)
const Matrix3 & rotation () const
const Vector3 & translation () const
Matrix3 & rotation ()
Vector3 & translation ()
void rotation (const Matrix3 &R)
void translation (const Vector3 &p)
Eigen::Matrix< Scalar, 4, 4, Options > toHomogeneousMatrix () const
Matrix6 toActionMatrix () const
Vb.toVector() = bXa.toMatrix() * Va.toVector()
SE3Tpl inverse () const
aXb = bXa.inverse()
void disp (std::ostream &os) const
template<typename D >
internal::ActionReturn< D >::Type act (const D &d) const
ay = aXb.act(by)
template<typename D >
internal::ActionReturn< D >::Type actInv (const D &d) const
by = aXb.actInv(ay)
Vector3 act (const Vector3 &p) const
Vector3 actInv (const Vector3 &p) const
SE3Tpl act (const SE3Tpl &m2) const
SE3Tpl actInv (const SE3Tpl &m2) const
operator Matrix4 () const
operator Matrix6 () const
SE3Tpl operator* (const SE3Tpl &m2) const
Static Public Member Functions
static SE3Tpl Identity ()
static SE3Tpl Random ()
Friends
std::ostream & operator<< (std::ostream &os, const SE3Tpl &X)
Detailed Description
template<typename _Scalar, int _Options>
class se3::SE3Tpl< _Scalar, _Options >
The rigid transform aMb can be seen in two ways:
given a point p expressed in frame B by its coordinate vector Bp, aMb computes its coordinates in frame A by Ap = aMb Bp.
aMb displaces a solid S centered at frame A into the solid centered in B. In particular, the origin of A is displaced at the origin of B: $^aM_b ^aA = ^aB$. The rigid displacement is stored as a rotation matrix and translation vector by: aMb (x) = aRb*x + aAB where aAB is the vector from origin A to origin B expressed in coordinates A.
Member Typedef Documentation
template<typename _Scalar, int _Options> typedef Eigen::Matrix<Scalar,3,3,Options> se3::SE3Tpl< _Scalar, _Options >::Matrix3
template<typename _Scalar, int _Options> typedef Eigen::Matrix<Scalar,4,4,Options> se3::SE3Tpl< _Scalar, _Options >::Matrix4
template<typename _Scalar, int _Options> typedef Eigen::Matrix<Scalar,6,6,Options> se3::SE3Tpl< _Scalar, _Options >::Matrix6
template<typename _Scalar, int _Options> typedef Eigen::Quaternion<Scalar,Options> se3::SE3Tpl< _Scalar, _Options >::Quaternion
template<typename _Scalar, int _Options> typedef _Scalar se3::SE3Tpl< _Scalar, _Options >::Scalar
template<typename _Scalar, int _Options> typedef Eigen::Matrix<Scalar,3,1,Options> se3::SE3Tpl< _Scalar, _Options >::Vector3
template<typename _Scalar, int _Options> typedef Eigen::Matrix<Scalar,4,1,Options> se3::SE3Tpl< _Scalar, _Options >::Vector4
template<typename _Scalar, int _Options> typedef Eigen::Matrix<Scalar,6,1,Options> se3::SE3Tpl< _Scalar, _Options >::Vector6
Member Enumeration Documentation
template<typename _Scalar, int _Options> anonymous enum
Enumerator
Options
template<typename _Scalar, int _Options> anonymous enum
Enumerator
LINEAR
ANGULAR
Constructor & Destructor Documentation
template<typename _Scalar, int _Options> se3::SE3Tpl< _Scalar, _Options >::SE3Tpl () inline
Referenced by se3::SE3Tpl< _Scalar, _Options >::act(), se3::SE3Tpl< _Scalar, _Options >::actInv(), se3::SE3Tpl< _Scalar, _Options >::Identity(), se3::SE3Tpl< _Scalar, _Options >::inverse(), and se3::SE3Tpl< _Scalar, _Options >::Random().
template<typename _Scalar, int _Options> template<typename M3 , typename v3 > se3::SE3Tpl< _Scalar, _Options >::SE3Tpl (const Eigen::MatrixBase< M3 > & R, const Eigen::MatrixBase< v3 > & p) inline
template<typename _Scalar, int _Options> se3::SE3Tpl< _Scalar, _Options >::SE3Tpl (int) inline
template<typename _Scalar, int _Options> template<typename S2 , int O2> se3::SE3Tpl< _Scalar, _Options >::SE3Tpl (const SE3Tpl< S2, O2 > clone) inline
Member Function Documentation
template<typename _Scalar, int _Options> template<typename D > internal::ActionReturn<D>::Type se3::SE3Tpl< _Scalar, _Options >::act (const D & d) const inline
ay = aXb.act(by)
Referenced by se3::SE3Tpl< _Scalar, _Options >::operator*().
template<typename _Scalar, int _Options> Vector3 se3::SE3Tpl< _Scalar, _Options >::act (const Vector3 & p) const inline
template<typename _Scalar, int _Options> SE3Tpl se3::SE3Tpl< _Scalar, _Options >::act (const SE3Tpl< _Scalar, _Options > & m2) const inline
References se3::SE3Tpl< _Scalar, _Options >::SE3Tpl().
template<typename _Scalar, int _Options> template<typename D > internal::ActionReturn<D>::Type se3::SE3Tpl< _Scalar, _Options >::actInv (const D & d) const inline
by = aXb.actInv(ay)
template<typename _Scalar, int _Options> Vector3 se3::SE3Tpl< _Scalar, _Options >::actInv (const Vector3 & p) const inline
template<typename _Scalar, int _Options> SE3Tpl se3::SE3Tpl< _Scalar, _Options >::actInv (const SE3Tpl< _Scalar, _Options > & m2) const inline
References se3::SE3Tpl< _Scalar, _Options >::SE3Tpl().
template<typename _Scalar, int _Options> void se3::SE3Tpl< _Scalar, _Options >::disp (std::ostream & os) const inline
template<typename _Scalar, int _Options> static SE3Tpl se3::SE3Tpl< _Scalar, _Options >::Identity () inline static
References se3::SE3Tpl< _Scalar, _Options >::SE3Tpl().
template<typename _Scalar, int _Options> SE3Tpl se3::SE3Tpl< _Scalar, _Options >::inverse () const inline
aXb = bXa.inverse()
References se3::SE3Tpl< _Scalar, _Options >::SE3Tpl().
template<typename _Scalar, int _Options> se3::SE3Tpl< _Scalar, _Options >::operator Matrix4 () const inline
References se3::SE3Tpl< _Scalar, _Options >::toHomogeneousMatrix().
template<typename _Scalar, int _Options> se3::SE3Tpl< _Scalar, _Options >::operator Matrix6 () const inline
References se3::SE3Tpl< _Scalar, _Options >::toActionMatrix().
template<typename _Scalar, int _Options> SE3Tpl se3::SE3Tpl< _Scalar, _Options >::operator* (const SE3Tpl< _Scalar, _Options > & m2) const inline
References se3::SE3Tpl< _Scalar, _Options >::act().
template<typename _Scalar, int _Options> template<typename S2 , int O2> SE3Tpl& se3::SE3Tpl< _Scalar, _Options >::operator= (const SE3Tpl< S2, O2 > & other) inline
References se3::SE3Tpl< _Scalar, _Options >::rotation(), and se3::SE3Tpl< _Scalar, _Options >::translation().
template<typename _Scalar, int _Options> static SE3Tpl se3::SE3Tpl< _Scalar, _Options >::Random () inline static
References se3::SE3Tpl< _Scalar, _Options >::SE3Tpl().
template<typename _Scalar, int _Options> const Matrix3& se3::SE3Tpl< _Scalar, _Options >::rotation () const inline
Referenced by se3::SE3Tpl< _Scalar, _Options >::operator=().
template<typename _Scalar, int _Options> Matrix3& se3::SE3Tpl< _Scalar, _Options >::rotation () inline
template<typename _Scalar, int _Options> void se3::SE3Tpl< _Scalar, _Options >::rotation (const Matrix3 & R) inline
template<typename _Scalar, int _Options> Matrix6 se3::SE3Tpl< _Scalar, _Options >::toActionMatrix () const inline
Vb.toVector() = bXa.toMatrix() * Va.toVector()
References se3::SE3Tpl< _Scalar, _Options >::ANGULAR, and se3::SE3Tpl< _Scalar, _Options >::LINEAR.
Referenced by se3::SE3Tpl< _Scalar, _Options >::operator Matrix6().
template<typename _Scalar, int _Options> Eigen::Matrix<Scalar,4,4,Options> se3::SE3Tpl< _Scalar, _Options >::toHomogeneousMatrix () const inline
Referenced by se3::SE3Tpl< _Scalar, _Options >::operator Matrix4().
template<typename _Scalar, int _Options> const Vector3& se3::SE3Tpl< _Scalar, _Options >::translation () const inline
Referenced by se3::SE3Tpl< _Scalar, _Options >::operator=().
template<typename _Scalar, int _Options> Vector3& se3::SE3Tpl< _Scalar, _Options >::translation () inline
template<typename _Scalar, int _Options> void se3::SE3Tpl< _Scalar, _Options >::translation (const Vector3 & p) inline
Friends And Related Function Documentation
template<typename _Scalar, int _Options> std::ostream& operator<< (std::ostream & os, const SE3Tpl< _Scalar, _Options > & X) friend